/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crane_dae_get_matrices_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[28] = {4, 5, 0, 4, 8, 12, 16, 20, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s5[3] = {4, 0, 0};
static const casadi_int casadi_s6[7] = {1, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s7[31] = {6, 4, 0, 6, 12, 18, 24, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[17] = {6, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* crane_dae_get_matrices_fun:(i0)->(o0[5x5],o1[5x2],o2[5],o3[5x5],o4[4x5],o5[4x5],o6[4x0],o7[1x2],o8[6x4],o9[5],o10[6x6],o11[6x2],o12,o13) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  a1=1.;
  if (res[0]!=0) res[0][5]=a1;
  a2=-4.0493711676434543e+01;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  a2=1.3803228073658729e+00;
  if (res[0]!=0) res[0][11]=a2;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a1;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a1;
  if (res[3]!=0) res[3][0]=a1;
  if (res[3]!=0) res[3][1]=a0;
  if (res[3]!=0) res[3][2]=a0;
  if (res[3]!=0) res[3][3]=a0;
  if (res[3]!=0) res[3][4]=a0;
  if (res[3]!=0) res[3][5]=a0;
  if (res[3]!=0) res[3][6]=a1;
  if (res[3]!=0) res[3][7]=a0;
  if (res[3]!=0) res[3][8]=a0;
  if (res[3]!=0) res[3][9]=a0;
  if (res[3]!=0) res[3][10]=a0;
  if (res[3]!=0) res[3][11]=a0;
  if (res[3]!=0) res[3][12]=a1;
  if (res[3]!=0) res[3][13]=a0;
  if (res[3]!=0) res[3][14]=a0;
  if (res[3]!=0) res[3][15]=a0;
  if (res[3]!=0) res[3][16]=a0;
  if (res[3]!=0) res[3][17]=a0;
  if (res[3]!=0) res[3][18]=a1;
  if (res[3]!=0) res[3][19]=a0;
  if (res[3]!=0) res[3][20]=a0;
  if (res[3]!=0) res[3][21]=a0;
  if (res[3]!=0) res[3][22]=a0;
  if (res[3]!=0) res[3][23]=a0;
  if (res[3]!=0) res[3][24]=a1;
  if (res[4]!=0) res[4][0]=a1;
  if (res[4]!=0) res[4][1]=a0;
  if (res[4]!=0) res[4][2]=a0;
  if (res[4]!=0) res[4][3]=a0;
  if (res[4]!=0) res[4][4]=a0;
  if (res[4]!=0) res[4][5]=a1;
  if (res[4]!=0) res[4][6]=a0;
  if (res[4]!=0) res[4][7]=a0;
  if (res[4]!=0) res[4][8]=a0;
  if (res[4]!=0) res[4][9]=a0;
  if (res[4]!=0) res[4][10]=a0;
  if (res[4]!=0) res[4][11]=a0;
  if (res[4]!=0) res[4][12]=a0;
  if (res[4]!=0) res[4][13]=a0;
  if (res[4]!=0) res[4][14]=a1;
  if (res[4]!=0) res[4][15]=a0;
  if (res[4]!=0) res[4][16]=a0;
  if (res[4]!=0) res[4][17]=a0;
  if (res[4]!=0) res[4][18]=a0;
  if (res[4]!=0) res[4][19]=a1;
  if (res[5]!=0) res[5][0]=a0;
  if (res[5]!=0) res[5][1]=a0;
  if (res[5]!=0) res[5][2]=a0;
  if (res[5]!=0) res[5][3]=a0;
  if (res[5]!=0) res[5][4]=a0;
  if (res[5]!=0) res[5][5]=a0;
  if (res[5]!=0) res[5][6]=a0;
  if (res[5]!=0) res[5][7]=a0;
  if (res[5]!=0) res[5][8]=a0;
  if (res[5]!=0) res[5][9]=a0;
  if (res[5]!=0) res[5][10]=a0;
  if (res[5]!=0) res[5][11]=a0;
  if (res[5]!=0) res[5][12]=a0;
  if (res[5]!=0) res[5][13]=a0;
  if (res[5]!=0) res[5][14]=a0;
  if (res[5]!=0) res[5][15]=a0;
  if (res[5]!=0) res[5][16]=a0;
  if (res[5]!=0) res[5][17]=a0;
  if (res[5]!=0) res[5][18]=a0;
  if (res[5]!=0) res[5][19]=a0;
  if (res[7]!=0) res[7][0]=a1;
  if (res[7]!=0) res[7][1]=a0;
  if (res[8]!=0) res[8][0]=a0;
  if (res[8]!=0) res[8][1]=a0;
  if (res[8]!=0) res[8][2]=a0;
  if (res[8]!=0) res[8][3]=a0;
  if (res[8]!=0) res[8][4]=a0;
  if (res[8]!=0) res[8][5]=a0;
  if (res[8]!=0) res[8][6]=a1;
  a2=-7.8182378879940387e+01;
  if (res[8]!=0) res[8][7]=a2;
  if (res[8]!=0) res[8][8]=a0;
  if (res[8]!=0) res[8][9]=a0;
  if (res[8]!=0) res[8][10]=a0;
  if (res[8]!=0) res[8][11]=a0;
  if (res[8]!=0) res[8][12]=a0;
  a2=3.7072679182318851e+00;
  if (res[8]!=0) res[8][13]=a2;
  if (res[8]!=0) res[8][14]=a0;
  if (res[8]!=0) res[8][15]=a0;
  if (res[8]!=0) res[8][16]=a0;
  if (res[8]!=0) res[8][17]=a0;
  if (res[8]!=0) res[8][18]=a0;
  if (res[8]!=0) res[8][19]=a0;
  if (res[8]!=0) res[8][20]=a0;
  if (res[8]!=0) res[8][21]=a0;
  a2=-8.;
  if (res[8]!=0) res[8][22]=a2;
  if (res[8]!=0) res[8][23]=a0;
  if (res[9]!=0) res[9][0]=a0;
  if (res[9]!=0) res[9][1]=a0;
  if (res[9]!=0) res[9][2]=a0;
  if (res[9]!=0) res[9][3]=a0;
  if (res[9]!=0) res[9][4]=a0;
  if (res[10]!=0) res[10][0]=a1;
  if (res[10]!=0) res[10][1]=a0;
  if (res[10]!=0) res[10][2]=a0;
  if (res[10]!=0) res[10][3]=a0;
  if (res[10]!=0) res[10][4]=a0;
  if (res[10]!=0) res[10][5]=a0;
  if (res[10]!=0) res[10][6]=a0;
  if (res[10]!=0) res[10][7]=a1;
  if (res[10]!=0) res[10][8]=a0;
  if (res[10]!=0) res[10][9]=a0;
  if (res[10]!=0) res[10][10]=a0;
  if (res[10]!=0) res[10][11]=a0;
  if (res[10]!=0) res[10][12]=a0;
  if (res[10]!=0) res[10][13]=a0;
  if (res[10]!=0) res[10][14]=a1;
  if (res[10]!=0) res[10][15]=a0;
  if (res[10]!=0) res[10][16]=a0;
  if (res[10]!=0) res[10][17]=a0;
  if (res[10]!=0) res[10][18]=a0;
  if (res[10]!=0) res[10][19]=a0;
  if (res[10]!=0) res[10][20]=a0;
  if (res[10]!=0) res[10][21]=a1;
  if (res[10]!=0) res[10][22]=a0;
  if (res[10]!=0) res[10][23]=a0;
  if (res[10]!=0) res[10][24]=a0;
  if (res[10]!=0) res[10][25]=a0;
  if (res[10]!=0) res[10][26]=a0;
  if (res[10]!=0) res[10][27]=a1;
  a2=-1.;
  if (res[10]!=0) res[10][28]=a2;
  if (res[10]!=0) res[10][29]=a0;
  if (res[10]!=0) res[10][30]=a0;
  if (res[10]!=0) res[10][31]=a0;
  if (res[10]!=0) res[10][32]=a0;
  if (res[10]!=0) res[10][33]=a0;
  if (res[10]!=0) res[10][34]=a0;
  a2=-2.;
  if (res[10]!=0) res[10][35]=a2;
  if (res[11]!=0) res[11][0]=a0;
  if (res[11]!=0) res[11][1]=a0;
  if (res[11]!=0) res[11][2]=a1;
  if (res[11]!=0) res[11][3]=a0;
  if (res[11]!=0) res[11][4]=a0;
  if (res[11]!=0) res[11][5]=a0;
  if (res[11]!=0) res[11][6]=a0;
  if (res[11]!=0) res[11][7]=a0;
  if (res[11]!=0) res[11][8]=a0;
  if (res[11]!=0) res[11][9]=a0;
  if (res[11]!=0) res[11][10]=a0;
  if (res[11]!=0) res[11][11]=a0;
  if (res[12]!=0) res[12][0]=a1;
  if (res[13]!=0) res[13][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int crane_dae_get_matrices_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void crane_dae_get_matrices_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void crane_dae_get_matrices_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crane_dae_get_matrices_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int crane_dae_get_matrices_fun_n_out(void) { return 14;}

CASADI_SYMBOL_EXPORT const char* crane_dae_get_matrices_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crane_dae_get_matrices_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    case 5: return "o5";
    case 6: return "o6";
    case 7: return "o7";
    case 8: return "o8";
    case 9: return "o9";
    case 10: return "o10";
    case 11: return "o11";
    case 12: return "o12";
    case 13: return "o13";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crane_dae_get_matrices_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crane_dae_get_matrices_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    case 5: return casadi_s4;
    case 6: return casadi_s5;
    case 7: return casadi_s6;
    case 8: return casadi_s7;
    case 9: return casadi_s3;
    case 10: return casadi_s8;
    case 11: return casadi_s9;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crane_dae_get_matrices_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
