/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) impl_ode_fun_chain_nm3_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* casadi_impl_ode_fun_chain_nm3:(i0[12],i1[12],i2[3])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1] ? arg[1][0] : 0;
  a1=arg[0] ? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  a1=arg[0] ? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1] ? arg[1][2] : 0;
  a1=arg[0] ? arg[0][5] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1] ? arg[1][3] : 0;
  a1=3.3333333333333336e+01;
  a2=1.;
  a3=3.3000000000000002e-02;
  a4=arg[0] ? arg[0][6] : 0;
  a5=arg[0] ? arg[0][0] : 0;
  a4=(a4-a5);
  a6=casadi_sq(a4);
  a7=arg[0] ? arg[0][7] : 0;
  a8=arg[0] ? arg[0][1] : 0;
  a7=(a7-a8);
  a9=casadi_sq(a7);
  a6=(a6+a9);
  a9=arg[0] ? arg[0][8] : 0;
  a10=arg[0] ? arg[0][2] : 0;
  a9=(a9-a10);
  a11=casadi_sq(a9);
  a6=(a6+a11);
  a6=sqrt(a6);
  a6=(a3/a6);
  a6=(a2-a6);
  a4=(a6*a4);
  a11=casadi_sq(a5);
  a12=casadi_sq(a8);
  a11=(a11+a12);
  a12=casadi_sq(a10);
  a11=(a11+a12);
  a11=sqrt(a11);
  a3=(a3/a11);
  a2=(a2-a3);
  a5=(a2*a5);
  a4=(a4-a5);
  a4=(a1*a4);
  a0=(a0-a4);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1] ? arg[1][4] : 0;
  a7=(a6*a7);
  a8=(a2*a8);
  a7=(a7-a8);
  a7=(a1*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1] ? arg[1][5] : 0;
  a6=(a6*a9);
  a2=(a2*a10);
  a6=(a6-a2);
  a1=(a1*a6);
  a6=9.8100000000000005e+00;
  a1=(a1-a6);
  a0=(a0-a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1] ? arg[1][6] : 0;
  a1=arg[0] ? arg[0][9] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1] ? arg[1][7] : 0;
  a1=arg[0] ? arg[0][10] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1] ? arg[1][8] : 0;
  a1=arg[0] ? arg[0][11] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1] ? arg[1][9] : 0;
  a1=arg[2] ? arg[2][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1] ? arg[1][10] : 0;
  a1=arg[2] ? arg[2][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1] ? arg[1][11] : 0;
  a1=arg[2] ? arg[2][2] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int casadi_impl_ode_fun_chain_nm3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void casadi_impl_ode_fun_chain_nm3_incref(void) {
}

CASADI_SYMBOL_EXPORT void casadi_impl_ode_fun_chain_nm3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int casadi_impl_ode_fun_chain_nm3_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int casadi_impl_ode_fun_chain_nm3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* casadi_impl_ode_fun_chain_nm3_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* casadi_impl_ode_fun_chain_nm3_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* casadi_impl_ode_fun_chain_nm3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* casadi_impl_ode_fun_chain_nm3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int casadi_impl_ode_fun_chain_nm3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
