/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) astrobee_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s6[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* astrobee_expl_vde_adj:(i0[12],i1[12],i2[6],i3[46])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+15, *w2=w+24, *w3=w+27, *w4=w+36, *w5=w+39, *w6=w+42, *w7=w+51, *w8=w+63, *w9=w+66, *w10=w+69, *w11=w+72, w12, w13, *w14=w+77, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+91, w27, *w28=w+98, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = input[3][3] */
  casadi_copy(arg[3] ? arg[3]+25 : 0, 3, w4);
  /* #5: @5 = @4[:3] */
  for (rr=w5, ss=w4+0; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #6: @3 = (@5\@3) */
  rr = w3;
  ss = w5;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[3], r[3], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s1, v, casadi_s1, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s1, v, casadi_s1, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #7: @6 = @3' */
  for (i=0, rr=w6, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #8: @7 = input[1][0] */
  casadi_copy(arg[1], 12, w7);
  /* #9: {@4, @8, @9, @10} = vertsplit(@7) */
  casadi_copy(w7, 3, w4);
  casadi_copy(w7+3, 3, w8);
  casadi_copy(w7+6, 3, w9);
  casadi_copy(w7+9, 3, w10);
  /* #10: @2 = mac(@6,@10,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #11: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #12: @7 = input[0][0] */
  casadi_copy(arg[0], 12, w7);
  /* #13: @11 = @7[9:12] */
  for (rr=w11, ss=w7+9; ss!=w7+12; ss+=1) *rr++ = *ss;
  /* #14: @10 = mac(@5,@11,@10) */
  casadi_mtimes(w5, casadi_s1, w11, casadi_s2, w10, casadi_s2, w, 0);
  /* #15: @10 = @10' */
  /* #16: @1 = mac(@2,@10,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w10+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #17: @12 = @1[5] */
  for (rr=(&w12), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #18: @13 = 0 */
  w13 = 0.;
  /* #19: (@1[5] = @13) */
  for (rr=w1+5, ss=(&w13); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #20: @13 = @1[7] */
  for (rr=(&w13), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #21: @12 = (@12-@13) */
  w12 -= w13;
  /* #22: (@0[9] += @12) */
  for (rr=w0+9, ss=(&w12); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #23: @12 = 0 */
  w12 = 0.;
  /* #24: (@1[7] = @12) */
  for (rr=w1+7, ss=(&w12); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #25: @12 = 0 */
  w12 = 0.;
  /* #26: @6 = @1; (@6[2] = @12) */
  casadi_copy(w1, 9, w6);
  for (rr=w6+2, ss=(&w12); rr!=w6+3; rr+=1) *rr = *ss++;
  /* #27: @12 = @6[6] */
  for (rr=(&w12), ss=w6+6; ss!=w6+7; ss+=1) *rr++ = *ss;
  /* #28: @13 = @1[2] */
  for (rr=(&w13), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #29: @12 = (@12-@13) */
  w12 -= w13;
  /* #30: (@0[10] += @12) */
  for (rr=w0+10, ss=(&w12); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #31: @12 = 0 */
  w12 = 0.;
  /* #32: (@6[6] = @12) */
  for (rr=w6+6, ss=(&w12); rr!=w6+7; rr+=1) *rr = *ss++;
  /* #33: @12 = @6[1] */
  for (rr=(&w12), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #34: @13 = 0 */
  w13 = 0.;
  /* #35: (@6[1] = @13) */
  for (rr=w6+1, ss=(&w13); rr!=w6+2; rr+=1) *rr = *ss++;
  /* #36: @13 = @6[3] */
  for (rr=(&w13), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #37: @12 = (@12-@13) */
  w12 -= w13;
  /* #38: (@0[11] += @12) */
  for (rr=w0+11, ss=(&w12); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #39: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #40: @14 = @5' */
  casadi_trans(w5,casadi_s1, w14, casadi_s1, iw);
  /* #41: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #42: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #43: @12 = @7[11] */
  for (rr=(&w12), ss=w7+11; ss!=w7+12; ss+=1) *rr++ = *ss;
  /* #44: @13 = (-@12) */
  w13 = (- w12 );
  /* #45: (@6[3] = @13) */
  for (rr=w6+3, ss=(&w13); rr!=w6+4; rr+=1) *rr = *ss++;
  /* #46: (@6[1] = @12) */
  for (rr=w6+1, ss=(&w12); rr!=w6+2; rr+=1) *rr = *ss++;
  /* #47: @12 = @7[10] */
  for (rr=(&w12), ss=w7+10; ss!=w7+11; ss+=1) *rr++ = *ss;
  /* #48: (@6[6] = @12) */
  for (rr=w6+6, ss=(&w12); rr!=w6+7; rr+=1) *rr = *ss++;
  /* #49: @12 = (-@12) */
  w12 = (- w12 );
  /* #50: (@6[2] = @12) */
  for (rr=w6+2, ss=(&w12); rr!=w6+3; rr+=1) *rr = *ss++;
  /* #51: @12 = @7[9] */
  for (rr=(&w12), ss=w7+9; ss!=w7+10; ss+=1) *rr++ = *ss;
  /* #52: @13 = (-@12) */
  w13 = (- w12 );
  /* #53: (@6[7] = @13) */
  for (rr=w6+7, ss=(&w13); rr!=w6+8; rr+=1) *rr = *ss++;
  /* #54: (@6[5] = @12) */
  for (rr=w6+5, ss=(&w12); rr!=w6+6; rr+=1) *rr = *ss++;
  /* #55: @1 = @6' */
  for (i=0, rr=w1, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #56: @5 = mac(@1,@2,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @10 = mac(@14,@5,@10) */
  casadi_mtimes(w14, casadi_s1, w5, casadi_s2, w10, casadi_s2, w, 0);
  /* #58: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #59: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #60: @12 = 1 */
  w12 = 1.;
  /* #61: (@1[0] = @12) */
  for (rr=w1+0, ss=(&w12); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #62: @12 = @7[6] */
  for (rr=(&w12), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #63: @13 = sin(@12) */
  w13 = sin( w12 );
  /* #64: @15 = @7[7] */
  for (rr=(&w15), ss=w7+7; ss!=w7+8; ss+=1) *rr++ = *ss;
  /* #65: @16 = tan(@15) */
  w16 = tan( w15 );
  /* #66: @17 = (@13*@16) */
  w17  = (w13*w16);
  /* #67: (@1[3] = @17) */
  for (rr=w1+3, ss=(&w17); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #68: @17 = cos(@12) */
  w17 = cos( w12 );
  /* #69: @18 = tan(@15) */
  w18 = tan( w15 );
  /* #70: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #71: (@1[6] = @19) */
  for (rr=w1+6, ss=(&w19); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #72: @19 = cos(@12) */
  w19 = cos( w12 );
  /* #73: (@1[4] = @19) */
  for (rr=w1+4, ss=(&w19); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #74: @19 = sin(@12) */
  w19 = sin( w12 );
  /* #75: @19 = (-@19) */
  w19 = (- w19 );
  /* #76: (@1[7] = @19) */
  for (rr=w1+7, ss=(&w19); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #77: @19 = sin(@12) */
  w19 = sin( w12 );
  /* #78: @20 = cos(@15) */
  w20 = cos( w15 );
  /* #79: @19 = (@19/@20) */
  w19 /= w20;
  /* #80: (@1[5] = @19) */
  for (rr=w1+5, ss=(&w19); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #81: @21 = cos(@12) */
  w21 = cos( w12 );
  /* #82: @22 = cos(@15) */
  w22 = cos( w15 );
  /* #83: @21 = (@21/@22) */
  w21 /= w22;
  /* #84: (@1[8] = @21) */
  for (rr=w1+8, ss=(&w21); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #85: @6 = @1' */
  for (i=0, rr=w6, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #86: @14 = mac(@6,@9,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #87: @10 = (@10+@14) */
  for (i=0, rr=w10, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #88: (@0[9:12] += @10) */
  for (rr=w0+9, ss=w10; rr!=w0+12; rr+=1) *rr += *ss++;
  /* #89: @23 = sin(@15) */
  w23 = sin( w15 );
  /* #90: @21 = (@21/@22) */
  w21 /= w22;
  /* #91: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #92: @11 = @11' */
  /* #93: @6 = mac(@9,@11,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w11+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #94: @24 = @6[8] */
  for (rr=(&w24), ss=w6+8; ss!=w6+9; ss+=1) *rr++ = *ss;
  /* #95: @21 = (@21*@24) */
  w21 *= w24;
  /* #96: @23 = (@23*@21) */
  w23 *= w21;
  /* #97: @21 = sin(@15) */
  w21 = sin( w15 );
  /* #98: @19 = (@19/@20) */
  w19 /= w20;
  /* #99: @25 = 0 */
  w25 = 0.;
  /* #100: (@6[8] = @25) */
  for (rr=w6+8, ss=(&w25); rr!=w6+9; rr+=1) *rr = *ss++;
  /* #101: @25 = @6[5] */
  for (rr=(&w25), ss=w6+5; ss!=w6+6; ss+=1) *rr++ = *ss;
  /* #102: @19 = (@19*@25) */
  w19 *= w25;
  /* #103: @21 = (@21*@19) */
  w21 *= w19;
  /* #104: @23 = (@23+@21) */
  w23 += w21;
  /* #105: @21 = 0 */
  w21 = 0.;
  /* #106: (@6[5] = @21) */
  for (rr=w6+5, ss=(&w21); rr!=w6+6; rr+=1) *rr = *ss++;
  /* #107: @21 = 0 */
  w21 = 0.;
  /* #108: @1 = @6; (@1[7] = @21) */
  casadi_copy(w6, 9, w1);
  for (rr=w1+7, ss=(&w21); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #109: @21 = 0 */
  w21 = 0.;
  /* #110: @3 = @1; (@3[4] = @21) */
  casadi_copy(w1, 9, w3);
  for (rr=w3+4, ss=(&w21); rr!=w3+5; rr+=1) *rr = *ss++;
  /* #111: @21 = @3[6] */
  for (rr=(&w21), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #112: @17 = (@17*@21) */
  w17 *= w21;
  /* #113: @19 = cos(@15) */
  w19 = cos( w15 );
  /* #114: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #115: @17 = (@17/@19) */
  w17 /= w19;
  /* #116: @23 = (@23+@17) */
  w23 += w17;
  /* #117: @17 = 0 */
  w17 = 0.;
  /* #118: (@3[6] = @17) */
  for (rr=w3+6, ss=(&w17); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #119: @17 = @3[3] */
  for (rr=(&w17), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #120: @13 = (@13*@17) */
  w13 *= w17;
  /* #121: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #122: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #123: @13 = (@13/@15) */
  w13 /= w15;
  /* #124: @23 = (@23+@13) */
  w23 += w13;
  /* #125: (@0[7] += @23) */
  for (rr=w0+7, ss=(&w23); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #126: @23 = cos(@12) */
  w23 = cos( w12 );
  /* #127: @25 = (@25/@20) */
  w25 /= w20;
  /* #128: @23 = (@23*@25) */
  w23 *= w25;
  /* #129: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #130: @24 = (@24/@22) */
  w24 /= w22;
  /* #131: @25 = (@25*@24) */
  w25 *= w24;
  /* #132: @23 = (@23-@25) */
  w23 -= w25;
  /* #133: @25 = cos(@12) */
  w25 = cos( w12 );
  /* #134: @24 = @6[7] */
  for (rr=(&w24), ss=w6+7; ss!=w6+8; ss+=1) *rr++ = *ss;
  /* #135: @25 = (@25*@24) */
  w25 *= w24;
  /* #136: @23 = (@23-@25) */
  w23 -= w25;
  /* #137: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #138: @24 = @1[4] */
  for (rr=(&w24), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #139: @25 = (@25*@24) */
  w25 *= w24;
  /* #140: @23 = (@23-@25) */
  w23 -= w25;
  /* #141: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #142: @18 = (@18*@21) */
  w18 *= w21;
  /* #143: @25 = (@25*@18) */
  w25 *= w18;
  /* #144: @23 = (@23-@25) */
  w23 -= w25;
  /* #145: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #146: @16 = (@16*@17) */
  w16 *= w17;
  /* #147: @12 = (@12*@16) */
  w12 *= w16;
  /* #148: @23 = (@23+@12) */
  w23 += w12;
  /* #149: (@0[6] += @23) */
  for (rr=w0+6, ss=(&w23); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #150: @23 = @7[6] */
  for (rr=(&w23), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #151: @12 = cos(@23) */
  w12 = cos( w23 );
  /* #152: @16 = @7[7] */
  for (rr=(&w16), ss=w7+7; ss!=w7+8; ss+=1) *rr++ = *ss;
  /* #153: @17 = cos(@16) */
  w17 = cos( w16 );
  /* #154: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #155: @25 = input[3][2] */
  w25 = arg[3] ? arg[3][24] : 0;
  /* #156: @8 = (@8/@25) */
  for (i=0, rr=w8; i<3; ++i) (*rr++) /= w25;
  /* #157: @26 = input[2][0] */
  casadi_copy(arg[2], 6, w26);
  /* #158: @9 = @26[:3] */
  for (rr=w9, ss=w26+0; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #159: @9 = @9' */
  /* #160: @1 = mac(@8,@9,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w9+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #161: @25 = 0 */
  w25 = 0.;
  /* #162: @6 = @1; (@6[8] = @25) */
  casadi_copy(w1, 9, w6);
  for (rr=w6+8, ss=(&w25); rr!=w6+9; rr+=1) *rr = *ss++;
  /* #163: @25 = @6[5] */
  for (rr=(&w25), ss=w6+5; ss!=w6+6; ss+=1) *rr++ = *ss;
  /* #164: @18 = (@17*@25) */
  w18  = (w17*w25);
  /* #165: @21 = @7[8] */
  for (rr=(&w21), ss=w7+8; ss!=w7+9; ss+=1) *rr++ = *ss;
  /* #166: @24 = cos(@21) */
  w24 = cos( w21 );
  /* #167: @22 = 0 */
  w22 = 0.;
  /* #168: (@6[5] = @22) */
  for (rr=w6+5, ss=(&w22); rr!=w6+6; rr+=1) *rr = *ss++;
  /* #169: @22 = 0 */
  w22 = 0.;
  /* #170: @3 = @6; (@3[2] = @22) */
  casadi_copy(w6, 9, w3);
  for (rr=w3+2, ss=(&w22); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #171: @22 = @3[7] */
  for (rr=(&w22), ss=w3+7; ss!=w3+8; ss+=1) *rr++ = *ss;
  /* #172: @20 = (@24*@22) */
  w20  = (w24*w22);
  /* #173: @18 = (@18-@20) */
  w18 -= w20;
  /* #174: @20 = sin(@21) */
  w20 = sin( w21 );
  /* #175: @13 = sin(@16) */
  w13 = sin( w16 );
  /* #176: @15 = (@20*@13) */
  w15  = (w20*w13);
  /* #177: @19 = 0 */
  w19 = 0.;
  /* #178: (@3[7] = @19) */
  for (rr=w3+7, ss=(&w19); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #179: @19 = @3[4] */
  for (rr=(&w19), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #180: @27 = (@15*@19) */
  w27  = (w15*w19);
  /* #181: @18 = (@18+@27) */
  w18 += w27;
  /* #182: @27 = 0 */
  w27 = 0.;
  /* #183: (@3[4] = @27) */
  for (rr=w3+4, ss=(&w27); rr!=w3+5; rr+=1) *rr = *ss++;
  /* #184: @27 = 0 */
  w27 = 0.;
  /* #185: @28 = @3; (@28[1] = @27) */
  casadi_copy(w3, 9, w28);
  for (rr=w28+1, ss=(&w27); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #186: @27 = @28[6] */
  for (rr=(&w27), ss=w28+6; ss!=w28+7; ss+=1) *rr++ = *ss;
  /* #187: @29 = (@20*@27) */
  w29  = (w20*w27);
  /* #188: @18 = (@18+@29) */
  w18 += w29;
  /* #189: @29 = (@24*@13) */
  w29  = (w24*w13);
  /* #190: @30 = 0 */
  w30 = 0.;
  /* #191: (@28[6] = @30) */
  for (rr=w28+6, ss=(&w30); rr!=w28+7; rr+=1) *rr = *ss++;
  /* #192: @30 = @28[3] */
  for (rr=(&w30), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #193: @31 = (@29*@30) */
  w31  = (w29*w30);
  /* #194: @18 = (@18+@31) */
  w18 += w31;
  /* #195: @12 = (@12*@18) */
  w12 *= w18;
  /* #196: @18 = sin(@23) */
  w18 = sin( w23 );
  /* #197: @31 = @1[8] */
  for (rr=(&w31), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #198: @32 = (@17*@31) */
  w32  = (w17*w31);
  /* #199: @33 = (@20*@13) */
  w33  = (w20*w13);
  /* #200: @34 = (@33*@22) */
  w34  = (w33*w22);
  /* #201: @32 = (@32+@34) */
  w32 += w34;
  /* #202: @34 = (@24*@19) */
  w34  = (w24*w19);
  /* #203: @32 = (@32+@34) */
  w32 += w34;
  /* #204: @34 = (@24*@13) */
  w34  = (w24*w13);
  /* #205: @35 = (@34*@27) */
  w35  = (w34*w27);
  /* #206: @32 = (@32+@35) */
  w32 += w35;
  /* #207: @35 = (@20*@30) */
  w35  = (w20*w30);
  /* #208: @32 = (@32-@35) */
  w32 -= w35;
  /* #209: @18 = (@18*@32) */
  w18 *= w32;
  /* #210: @12 = (@12-@18) */
  w12 -= w18;
  /* #211: (@0[6] += @12) */
  for (rr=w0+6, ss=(&w12); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #212: @12 = cos(@16) */
  w12 = cos( w16 );
  /* #213: @18 = cos(@23) */
  w18 = cos( w23 );
  /* #214: @32 = (@18*@22) */
  w32  = (w18*w22);
  /* #215: @35 = (@20*@32) */
  w35  = (w20*w32);
  /* #216: @36 = @6[2] */
  for (rr=(&w36), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #217: @35 = (@35-@36) */
  w35 -= w36;
  /* #218: @23 = sin(@23) */
  w23 = sin( w23 );
  /* #219: @36 = (@23*@19) */
  w36  = (w23*w19);
  /* #220: @37 = (@20*@36) */
  w37  = (w20*w36);
  /* #221: @35 = (@35+@37) */
  w35 += w37;
  /* #222: @37 = (@18*@27) */
  w37  = (w18*w27);
  /* #223: @38 = (@24*@37) */
  w38  = (w24*w37);
  /* #224: @35 = (@35+@38) */
  w35 += w38;
  /* #225: @38 = (@23*@30) */
  w38  = (w23*w30);
  /* #226: @39 = (@24*@38) */
  w39  = (w24*w38);
  /* #227: @35 = (@35+@39) */
  w35 += w39;
  /* #228: @12 = (@12*@35) */
  w12 *= w35;
  /* #229: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #230: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #231: @25 = (@23*@25) */
  w25  = (w23*w25);
  /* #232: @31 = (@31+@25) */
  w31 += w25;
  /* #233: @25 = @3[1] */
  for (rr=(&w25), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #234: @35 = (@20*@25) */
  w35  = (w20*w25);
  /* #235: @31 = (@31+@35) */
  w31 += w35;
  /* #236: @35 = 0 */
  w35 = 0.;
  /* #237: (@28[3] = @35) */
  for (rr=w28+3, ss=(&w35); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #238: @35 = @28[0] */
  for (rr=(&w35), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #239: @39 = (@24*@35) */
  w39  = (w24*w35);
  /* #240: @31 = (@31+@39) */
  w31 += w39;
  /* #241: @16 = (@16*@31) */
  w16 *= w31;
  /* #242: @12 = (@12-@16) */
  w12 -= w16;
  /* #243: (@0[7] += @12) */
  for (rr=w0+7, ss=(&w12); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #244: @12 = cos(@21) */
  w12 = cos( w21 );
  /* #245: @32 = (@13*@32) */
  w32  = (w13*w32);
  /* #246: @36 = (@13*@36) */
  w36  = (w13*w36);
  /* #247: @32 = (@32+@36) */
  w32 += w36;
  /* #248: @25 = (@17*@25) */
  w25  = (w17*w25);
  /* #249: @32 = (@32+@25) */
  w32 += w25;
  /* #250: @27 = (@23*@27) */
  w27  = (w23*w27);
  /* #251: @32 = (@32+@27) */
  w32 += w27;
  /* #252: @30 = (@18*@30) */
  w30  = (w18*w30);
  /* #253: @32 = (@32-@30) */
  w32 -= w30;
  /* #254: @12 = (@12*@32) */
  w12 *= w32;
  /* #255: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #256: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #257: @22 = (@23*@22) */
  w22  = (w23*w22);
  /* #258: @19 = (@19-@22) */
  w19 -= w22;
  /* #259: @37 = (@13*@37) */
  w37  = (w13*w37);
  /* #260: @19 = (@19+@37) */
  w19 += w37;
  /* #261: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #262: @19 = (@19+@38) */
  w19 += w38;
  /* #263: @35 = (@17*@35) */
  w35  = (w17*w35);
  /* #264: @19 = (@19+@35) */
  w19 += w35;
  /* #265: @21 = (@21*@19) */
  w21 *= w19;
  /* #266: @12 = (@12-@21) */
  w12 -= w21;
  /* #267: (@0[8] += @12) */
  for (rr=w0+8, ss=(&w12); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #268: (@0[3:6] += @4) */
  for (rr=w0+3, ss=w4; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #269: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #270: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #271: (@26[3:6] += @2) */
  for (rr=w26+3, ss=w2; rr!=w26+6; rr+=1) *rr += *ss++;
  /* #272: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #273: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #274: @12 = (@24*@17) */
  w12  = (w24*w17);
  /* #275: (@28[0] = @12) */
  for (rr=w28+0, ss=(&w12); rr!=w28+1; rr+=1) *rr = *ss++;
  /* #276: @29 = (@29*@23) */
  w29 *= w23;
  /* #277: @12 = (@20*@18) */
  w12  = (w20*w18);
  /* #278: @29 = (@29-@12) */
  w29 -= w12;
  /* #279: (@28[3] = @29) */
  for (rr=w28+3, ss=(&w29); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #280: @34 = (@34*@18) */
  w34 *= w18;
  /* #281: @29 = (@20*@23) */
  w29  = (w20*w23);
  /* #282: @34 = (@34+@29) */
  w34 += w29;
  /* #283: (@28[6] = @34) */
  for (rr=w28+6, ss=(&w34); rr!=w28+7; rr+=1) *rr = *ss++;
  /* #284: @20 = (@20*@17) */
  w20 *= w17;
  /* #285: (@28[1] = @20) */
  for (rr=w28+1, ss=(&w20); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #286: @15 = (@15*@23) */
  w15 *= w23;
  /* #287: @20 = (@24*@18) */
  w20  = (w24*w18);
  /* #288: @15 = (@15+@20) */
  w15 += w20;
  /* #289: (@28[4] = @15) */
  for (rr=w28+4, ss=(&w15); rr!=w28+5; rr+=1) *rr = *ss++;
  /* #290: @33 = (@33*@18) */
  w33 *= w18;
  /* #291: @24 = (@24*@23) */
  w24 *= w23;
  /* #292: @33 = (@33-@24) */
  w33 -= w24;
  /* #293: (@28[7] = @33) */
  for (rr=w28+7, ss=(&w33); rr!=w28+8; rr+=1) *rr = *ss++;
  /* #294: @13 = (-@13) */
  w13 = (- w13 );
  /* #295: (@28[2] = @13) */
  for (rr=w28+2, ss=(&w13); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #296: @23 = (@17*@23) */
  w23  = (w17*w23);
  /* #297: (@28[5] = @23) */
  for (rr=w28+5, ss=(&w23); rr!=w28+6; rr+=1) *rr = *ss++;
  /* #298: @17 = (@17*@18) */
  w17 *= w18;
  /* #299: (@28[8] = @17) */
  for (rr=w28+8, ss=(&w17); rr!=w28+9; rr+=1) *rr = *ss++;
  /* #300: @3 = @28' */
  for (i=0, rr=w3, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #301: @2 = mac(@3,@8,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #302: (@26[:3] += @2) */
  for (rr=w26+0, ss=w2; rr!=w26+3; rr+=1) *rr += *ss++;
  /* #303: output[0][1] = @26 */
  if (res[0]) casadi_copy(w26, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real astrobee_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 118;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
