/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) astrobee_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* astrobee_expl_ode_fun:(i0[12],i1[6],i2[46])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+15, *w2=w+18, w3, w4, w5, w6, w7, w8, w9, w10, *w11=w+35, *w12=w+41, *w13=w+44, *w14=w+47, *w15=w+50, *w16=w+53, *w17=w+62;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 12, w0);
  /* #1: @1 = @0[3:6] */
  for (rr=w1, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #4: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #5: @3 = @0[8] */
  for (rr=(&w3), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #6: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #7: @5 = @0[7] */
  for (rr=(&w5), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #8: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #9: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #10: (@2[0] = @7) */
  for (rr=w2+0, ss=(&w7); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #11: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #12: @7 = (@4*@5) */
  w7  = (w4*w5);
  /* #13: @8 = @0[6] */
  for (rr=(&w8), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #14: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #15: @7 = (@7*@9) */
  w7 *= w9;
  /* #16: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #17: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #18: @10 = (@3*@8) */
  w10  = (w3*w8);
  /* #19: @7 = (@7-@10) */
  w7 -= w10;
  /* #20: (@2[3] = @7) */
  for (rr=w2+3, ss=(&w7); rr!=w2+4; rr+=1) *rr = *ss++;
  /* #21: @7 = (@4*@5) */
  w7  = (w4*w5);
  /* #22: @7 = (@7*@8) */
  w7 *= w8;
  /* #23: @10 = (@3*@9) */
  w10  = (w3*w9);
  /* #24: @7 = (@7+@10) */
  w7 += w10;
  /* #25: (@2[6] = @7) */
  for (rr=w2+6, ss=(&w7); rr!=w2+7; rr+=1) *rr = *ss++;
  /* #26: @7 = (@3*@6) */
  w7  = (w3*w6);
  /* #27: (@2[1] = @7) */
  for (rr=w2+1, ss=(&w7); rr!=w2+2; rr+=1) *rr = *ss++;
  /* #28: @7 = (@3*@5) */
  w7  = (w3*w5);
  /* #29: @7 = (@7*@9) */
  w7 *= w9;
  /* #30: @10 = (@4*@8) */
  w10  = (w4*w8);
  /* #31: @7 = (@7+@10) */
  w7 += w10;
  /* #32: (@2[4] = @7) */
  for (rr=w2+4, ss=(&w7); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #33: @3 = (@3*@5) */
  w3 *= w5;
  /* #34: @3 = (@3*@8) */
  w3 *= w8;
  /* #35: @4 = (@4*@9) */
  w4 *= w9;
  /* #36: @3 = (@3-@4) */
  w3 -= w4;
  /* #37: (@2[7] = @3) */
  for (rr=w2+7, ss=(&w3); rr!=w2+8; rr+=1) *rr = *ss++;
  /* #38: @5 = (-@5) */
  w5 = (- w5 );
  /* #39: (@2[2] = @5) */
  for (rr=w2+2, ss=(&w5); rr!=w2+3; rr+=1) *rr = *ss++;
  /* #40: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #41: (@2[5] = @9) */
  for (rr=w2+5, ss=(&w9); rr!=w2+6; rr+=1) *rr = *ss++;
  /* #42: @6 = (@6*@8) */
  w6 *= w8;
  /* #43: (@2[8] = @6) */
  for (rr=w2+8, ss=(&w6); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #44: @11 = input[1][0] */
  casadi_copy(arg[1], 6, w11);
  /* #45: @12 = @11[:3] */
  for (rr=w12, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #46: @1 = mac(@2,@12,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #47: @6 = input[2][2] */
  w6 = arg[2] ? arg[2][24] : 0;
  /* #48: @1 = (@1/@6) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w6;
  /* #49: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+3);
  /* #50: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #51: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #52: @6 = 1 */
  w6 = 1.;
  /* #53: (@2[0] = @6) */
  for (rr=w2+0, ss=(&w6); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #54: @6 = @0[6] */
  for (rr=(&w6), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #55: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #56: @9 = @0[7] */
  for (rr=(&w9), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #57: @5 = tan(@9) */
  w5 = tan( w9 );
  /* #58: @8 = (@8*@5) */
  w8 *= w5;
  /* #59: (@2[3] = @8) */
  for (rr=w2+3, ss=(&w8); rr!=w2+4; rr+=1) *rr = *ss++;
  /* #60: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #61: @5 = tan(@9) */
  w5 = tan( w9 );
  /* #62: @8 = (@8*@5) */
  w8 *= w5;
  /* #63: (@2[6] = @8) */
  for (rr=w2+6, ss=(&w8); rr!=w2+7; rr+=1) *rr = *ss++;
  /* #64: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #65: (@2[4] = @8) */
  for (rr=w2+4, ss=(&w8); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #66: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #67: @8 = (-@8) */
  w8 = (- w8 );
  /* #68: (@2[7] = @8) */
  for (rr=w2+7, ss=(&w8); rr!=w2+8; rr+=1) *rr = *ss++;
  /* #69: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #70: @5 = cos(@9) */
  w5 = cos( w9 );
  /* #71: @8 = (@8/@5) */
  w8 /= w5;
  /* #72: (@2[5] = @8) */
  for (rr=w2+5, ss=(&w8); rr!=w2+6; rr+=1) *rr = *ss++;
  /* #73: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #74: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #75: @6 = (@6/@9) */
  w6 /= w9;
  /* #76: (@2[8] = @6) */
  for (rr=w2+8, ss=(&w6); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #77: @12 = @0[9:12] */
  for (rr=w12, ss=w0+9; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #78: @1 = mac(@2,@12,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #79: output[0][2] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+6);
  /* #80: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #81: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w2);
  /* #82: @13 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+25 : 0, 3, w13);
  /* #83: @14 = @13[:3] */
  for (rr=w14, ss=w13+0; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #84: @2 = (@14\@2) */
  rr = w2;
  ss = w14;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[3], r[3], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s1, v, casadi_s1, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s1, v, casadi_s1, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #85: @13 = @11[3:6] */
  for (rr=w13, ss=w11+3; ss!=w11+6; ss+=1) *rr++ = *ss;
  /* #86: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #87: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #88: @6 = @0[11] */
  for (rr=(&w6), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #89: @9 = (-@6) */
  w9 = (- w6 );
  /* #90: (@16[3] = @9) */
  for (rr=w16+3, ss=(&w9); rr!=w16+4; rr+=1) *rr = *ss++;
  /* #91: (@16[1] = @6) */
  for (rr=w16+1, ss=(&w6); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #92: @6 = @0[10] */
  for (rr=(&w6), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #93: (@16[6] = @6) */
  for (rr=w16+6, ss=(&w6); rr!=w16+7; rr+=1) *rr = *ss++;
  /* #94: @6 = (-@6) */
  w6 = (- w6 );
  /* #95: (@16[2] = @6) */
  for (rr=w16+2, ss=(&w6); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #96: @6 = @0[9] */
  for (rr=(&w6), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #97: @9 = (-@6) */
  w9 = (- w6 );
  /* #98: (@16[7] = @9) */
  for (rr=w16+7, ss=(&w9); rr!=w16+8; rr+=1) *rr = *ss++;
  /* #99: (@16[5] = @6) */
  for (rr=w16+5, ss=(&w6); rr!=w16+6; rr+=1) *rr = *ss++;
  /* #100: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #101: @17 = mac(@14,@12,@17) */
  casadi_mtimes(w14, casadi_s1, w12, casadi_s2, w17, casadi_s2, w, 0);
  /* #102: @15 = mac(@16,@17,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #103: @13 = (@13+@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #104: @1 = mac(@2,@13,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #105: output[0][3] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+9);
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int astrobee_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int astrobee_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real astrobee_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int astrobee_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 65;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
