#!/usr/bin/python
#
# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import sys
import os
import os.path
import math
import time

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/../../ekf_bag/scripts')
import environment

def run_ekf(astrobee_map, astrobee_bag, output_file):
  os.system('rosrun ekf_video ekf_to_video %s %s %s' % (astrobee_map, astrobee_bag, output_file))

astrobee_map = None
astrobee_bag = None
if len(sys.argv) >= 2:
  astrobee_bag = sys.argv[1]
if len(sys.argv) >= 3:
  astrobee_map = sys.argv[2]

(astrobee_map, astrobee_bag) = environment.initialize_environment(astrobee_map, astrobee_bag)

video_name = astrobee_bag[:astrobee_bag.rfind('.')] + '.mkv'

start = time.time()
run_ekf(astrobee_map, astrobee_bag, video_name)
run_time = time.time() - start
print 'Complete! Video output to %s. Run time: %g\n' % (video_name, run_time)

