/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) astrobee_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[27] = {1, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[16] = {1, 12, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[16] = {1, 12, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[16] = {1, 12, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s5[16] = {1, 12, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s6[16] = {1, 12, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s7[16] = {1, 12, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s8[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s9[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s10[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s11[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s12[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[16] = {1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s15[3] = {0, 0, 0};
static const casadi_int casadi_s16[32] = {28, 1, 0, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};
static const casadi_int casadi_s17[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s18[15] = {0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[144] = {4.5447331925463963e+01, 0., 0., 9.6000632360892411e+01, 0., 0., -5.6672076873272334e-14, 0., 0., -1.3994858503097251e-15, 0., 0., 0., 4.5447331925462635e+01, 0., 0., 9.6000632360885362e+01, 0., 0., -4.7580418882194603e-14, 0., 0., -1.1678728764420225e-14, 0., 0., 0., 4.5447331925461548e+01, 0., 0., 9.6000632360882491e+01, 0., 0., 3.0278396528136100e-14, 0., 0., 4.1541107317822559e-15, 9.6000632360892411e+01, 0., 0., 4.3199880818351102e+02, 0., 0., -1.2043042187350050e-13, 0., 0., 1.3065113819072846e-14, 0., 0., 0., 9.6000632360885362e+01, 0., 0., 4.3199880818348214e+02, 0., 0., -4.5785586415410353e-14, 0., 0., -3.1044165663922353e-14, 0., 0., 0., 9.6000632360882491e+01, 0., 0., 4.3199880818347549e+02, 0., 0., 1.7512892696740252e-14, 0., 0., -2.3575775415097003e-15, -5.6672076873272334e-14, 0., 0., -1.2043042187350050e-13, 0., 0., 1.2011523240350419e+01, 0., 0., 1.6132583656564552e+00, 0., 0., 0., -4.7580418882194603e-14, 0., 0., -4.5785586415410353e-14, 0., 0., 1.1923126517603416e+01, 0., 0., 1.5118909718587272e+00, 0., 0., 0., 3.0278396528136100e-14, 0., 0., 1.7512892696740252e-14, 0., 0., 1.2084990066039289e+01, 0., 0., 1.6980997415114403e+00, -1.3994858503097251e-15, 0., 0., 1.3065113819072846e-14, 0., 0., 1.6132583656564552e+00, 0., 0., 2.3572791540227636e+00, 0., 0., 0., -1.1678728764420225e-14, 0., 0., -3.1044165663922353e-14, 0., 0., 1.5118909718587272e+00, 0., 0., 2.2272237119943163e+00, 0., 0., 0., 4.1541107317822559e-15, 0., 0., -2.3575775415097003e-15, 0., 0., 1.6980997415114403e+00, 0., 0., 2.4674211649171536e+00};

/* astrobee_cost_ext_cost_e_fun_jac_hess:(i0[12],i1[],i2[],i3[28])->(o0,o1[12],o2[12x12],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, *w2=w+14, *w3=w+26, *w4=w+38, *w5=w+50, *w6=w+62, *w7=w+206, *w8=w+350;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 12, w2);
  /* #3: @3 = @2' */
  casadi_copy(w2, 12, w3);
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 12, w4);
  /* #5: @5 = @4' */
  casadi_copy(w4, 12, w5);
  /* #6: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<12; ++i) (*rr++) -= (*cs++);
  /* #7: @6 = 
  [[45.4473, 0, 0, 96.0006, 0, 0, -5.66721e-14, 0, 0, -1.39949e-15, 0, 0], 
   [0, 45.4473, 0, 0, 96.0006, 0, 0, -4.75804e-14, 0, 0, -1.16787e-14, 0], 
   [0, 0, 45.4473, 0, 0, 96.0006, 0, 0, 3.02784e-14, 0, 0, 4.15411e-15], 
   [96.0006, 0, 0, 431.999, 0, 0, -1.2043e-13, 0, 0, 1.30651e-14, 0, 0], 
   [0, 96.0006, 0, 0, 431.999, 0, 0, -4.57856e-14, 0, 0, -3.10442e-14, 0], 
   [0, 0, 96.0006, 0, 0, 431.999, 0, 0, 1.75129e-14, 0, 0, -2.35758e-15], 
   [-5.66721e-14, 0, 0, -1.2043e-13, 0, 0, 12.0115, 0, 0, 1.61326, 0, 0], 
   [0, -4.75804e-14, 0, 0, -4.57856e-14, 0, 0, 11.9231, 0, 0, 1.51189, 0], 
   [0, 0, 3.02784e-14, 0, 0, 1.75129e-14, 0, 0, 12.085, 0, 0, 1.6981], 
   [-1.39949e-15, 0, 0, 1.30651e-14, 0, 0, 1.61326, 0, 0, 2.35728, 0, 0], 
   [0, -1.16787e-14, 0, 0, -3.10442e-14, 0, 0, 1.51189, 0, 0, 2.22722, 0], 
   [0, 0, 4.15411e-15, 0, 0, -2.35758e-15, 0, 0, 1.6981, 0, 0, 2.46742]] */
  casadi_copy(casadi_c0, 144, w6);
  /* #8: @1 = mac(@3,@6,@1) */
  for (i=0, rr=w1; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w6+i*12; k<12; ++k) *rr += ss[k*1]**tt++;
  /* #9: @2 = (@2-@4) */
  for (i=0, rr=w2, cs=w4; i<12; ++i) (*rr++) -= (*cs++);
  /* #10: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*12; k<12; ++k) *rr += ss[k*1]**tt++;
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #12: @1 = @1' */
  /* #13: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #14: @2 = @2' */
  /* #15: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #16: @4 = mac(@2,@7,@4) */
  for (i=0, rr=w4; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w7+i*12; k<12; ++k) *rr += ss[k*1]**tt++;
  /* #17: @4 = @4' */
  /* #18: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #19: output[1][0] = @1 */
  casadi_copy(w1, 12, res[1]);
  /* #20: @8 = zeros(12x12) */
  casadi_clear(w8, 144);
  /* #21: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #22: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #23: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s2, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #24: @1 = @1' */
  /* #25: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #26: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #27: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s2, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #28: @4 = @4' */
  /* #29: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #30: (@8[:12] = @1) */
  for (rr=w8+0, ss=w1; rr!=w8+12; rr+=1) *rr = *ss++;
  /* #31: (@8[:144:12] = @1) */
  for (rr=w8+0, ss=w1; rr!=w8+144; rr+=12) *rr = *ss++;
  /* #32: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #33: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #34: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s3, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #35: @1 = @1' */
  /* #36: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #37: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #38: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s3, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #39: @4 = @4' */
  /* #40: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #41: (@8[12:24] = @1) */
  for (rr=w8+12, ss=w1; rr!=w8+24; rr+=1) *rr = *ss++;
  /* #42: (@8[1:145:12] = @1) */
  for (rr=w8+1, ss=w1; rr!=w8+145; rr+=12) *rr = *ss++;
  /* #43: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #44: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #45: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s4, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #46: @1 = @1' */
  /* #47: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #48: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #49: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s4, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #50: @4 = @4' */
  /* #51: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #52: (@8[24:36] = @1) */
  for (rr=w8+24, ss=w1; rr!=w8+36; rr+=1) *rr = *ss++;
  /* #53: (@8[2:146:12] = @1) */
  for (rr=w8+2, ss=w1; rr!=w8+146; rr+=12) *rr = *ss++;
  /* #54: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #55: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #56: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s5, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #57: @1 = @1' */
  /* #58: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #59: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #60: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s5, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #61: @4 = @4' */
  /* #62: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #63: (@8[36:48] = @1) */
  for (rr=w8+36, ss=w1; rr!=w8+48; rr+=1) *rr = *ss++;
  /* #64: (@8[3:147:12] = @1) */
  for (rr=w8+3, ss=w1; rr!=w8+147; rr+=12) *rr = *ss++;
  /* #65: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #66: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #67: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s6, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #68: @1 = @1' */
  /* #69: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #70: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #71: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s6, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #72: @4 = @4' */
  /* #73: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #74: (@8[48:60] = @1) */
  for (rr=w8+48, ss=w1; rr!=w8+60; rr+=1) *rr = *ss++;
  /* #75: (@8[4:148:12] = @1) */
  for (rr=w8+4, ss=w1; rr!=w8+148; rr+=12) *rr = *ss++;
  /* #76: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #77: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #78: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s7, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #79: @1 = @1' */
  /* #80: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #81: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #82: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s7, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #83: @4 = @4' */
  /* #84: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #85: (@8[60:72] = @1) */
  for (rr=w8+60, ss=w1; rr!=w8+72; rr+=1) *rr = *ss++;
  /* #86: (@8[5:149:12] = @1) */
  for (rr=w8+5, ss=w1; rr!=w8+149; rr+=12) *rr = *ss++;
  /* #87: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #88: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #89: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s8, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #90: @1 = @1' */
  /* #91: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #92: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #93: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s8, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #94: @4 = @4' */
  /* #95: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #96: (@8[72:84] = @1) */
  for (rr=w8+72, ss=w1; rr!=w8+84; rr+=1) *rr = *ss++;
  /* #97: (@8[6:150:12] = @1) */
  for (rr=w8+6, ss=w1; rr!=w8+150; rr+=12) *rr = *ss++;
  /* #98: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #99: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #100: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s9, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #101: @1 = @1' */
  /* #102: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #103: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #104: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s9, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #105: @4 = @4' */
  /* #106: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #107: (@8[84:96] = @1) */
  for (rr=w8+84, ss=w1; rr!=w8+96; rr+=1) *rr = *ss++;
  /* #108: (@8[7:151:12] = @1) */
  for (rr=w8+7, ss=w1; rr!=w8+151; rr+=12) *rr = *ss++;
  /* #109: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #110: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #111: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s10, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #112: @1 = @1' */
  /* #113: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #114: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #115: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s10, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #116: @4 = @4' */
  /* #117: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #118: (@8[96:108] = @1) */
  for (rr=w8+96, ss=w1; rr!=w8+108; rr+=1) *rr = *ss++;
  /* #119: (@8[8:152:12] = @1) */
  for (rr=w8+8, ss=w1; rr!=w8+152; rr+=12) *rr = *ss++;
  /* #120: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #121: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #122: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s11, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #123: @1 = @1' */
  /* #124: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #125: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #126: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s11, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #127: @4 = @4' */
  /* #128: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #129: (@8[108:120] = @1) */
  for (rr=w8+108, ss=w1; rr!=w8+120; rr+=1) *rr = *ss++;
  /* #130: (@8[9:153:12] = @1) */
  for (rr=w8+9, ss=w1; rr!=w8+153; rr+=12) *rr = *ss++;
  /* #131: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #132: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #133: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s12, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #134: @1 = @1' */
  /* #135: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #136: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #137: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s12, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #138: @4 = @4' */
  /* #139: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #140: (@8[120:132] = @1) */
  for (rr=w8+120, ss=w1; rr!=w8+132; rr+=1) *rr = *ss++;
  /* #141: (@8[10:154:12] = @1) */
  for (rr=w8+10, ss=w1; rr!=w8+154; rr+=12) *rr = *ss++;
  /* #142: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #143: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #144: @1 = mac(@0,@6,@1) */
  casadi_mtimes((&w0), casadi_s13, w6, casadi_s1, w1, casadi_s0, w, 0);
  /* #145: @1 = @1' */
  /* #146: @4 = zeros(1x12) */
  casadi_clear(w4, 12);
  /* #147: @0 = ones(1x12,1nz) */
  w0 = 1.;
  /* #148: @4 = mac(@0,@7,@4) */
  casadi_mtimes((&w0), casadi_s13, w7, casadi_s1, w4, casadi_s0, w, 0);
  /* #149: @4 = @4' */
  /* #150: @1 = (@1+@4) */
  for (i=0, rr=w1, cs=w4; i<12; ++i) (*rr++) += (*cs++);
  /* #151: (@8[132:144] = @1) */
  for (rr=w8+132, ss=w1; rr!=w8+144; rr+=1) *rr = *ss++;
  /* #152: (@8[11:155:12] = @1) */
  for (rr=w8+11, ss=w1; rr!=w8+155; rr+=12) *rr = *ss++;
  /* #153: @7 = @8' */
  for (i=0, rr=w7, cs=w8; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #154: output[2][0] = @7 */
  casadi_copy(w7, 144, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int astrobee_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int astrobee_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void astrobee_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void astrobee_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int astrobee_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int astrobee_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real astrobee_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s14;
    case 2: return casadi_s1;
    case 3: return casadi_s15;
    case 4: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int astrobee_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 494;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
