@startuml

skinparam componentStyle uml2
'skinparam dpi 300

!include "colors.puml"

!define COLOR_MPROC COLOR_6PASTEL_5
!define COLOR_PSOM COLOR_6PASTEL_3

skinparam component {
  backgroundColor COLOR_6PASTEL_2
  borderColor COLOR_6DARK_2
  arrowColor #MidnightBlue
}

skinparam interface {
 borderColor<<wired>> COLOR_6DARK_4
 backgroundColor<<wired>> COLOR_6PASTEL_4
 borderColor<<wifi>> COLOR_6DARK_6
 backgroundColor<<wifi>> COLOR_6PASTEL_6
}

title Astrobee Hardware Deployement Diagram

frame Dock {
  interface "Network Switch\n(to each berth)" <<wired>> as ethd
  node "Dock Computer\n // Ubuntu 16.04//" <<Wandboard>> as DockBoard COLOR_PSOM
  node "Dock Controller" <<PIC>> as DockControl COLOR_MPROC
  node ["DockActuator (2x)"] as DA
  DockControl -- DA
}

frame Astrobee {

  interface "Network Switch" <<wired>> as etha

  node "**      HLP**\n //Android 7.0//" <<Inforce>> as HLP COLOR_PSOM
  node "**      MLP**\n //Ubuntu 16.04//" <<Inforce>> as MLP COLOR_PSOM
  node "**       LLP**\n //Ubuntu 16.04//" <<Wandboard>> as LLP COLOR_PSOM
  node "PMC (2x)" <<PIC>> as PMC COLOR_MPROC
  node "SignalLight (2x)" <<PIC>> as SL COLOR_MPROC
  node Speedcam <<ARM Cortex>> COLOR_6PASTEL_1
  node EPS <<PIC>> COLOR_MPROC

  node PerchArm <<PIC>> COLOR_MPROC

  [Scicam] -- HLP : MIPI-CSI
  [TouchScreen] -- HLP : MIPI-DSI
  [Microphone] -- HLP : audio
  [Speaker] -- HLP : audio

  [IMU] -- LLP : SPI
  [Laser] -- LLP : GPIO
  [FrontLight] --o LLP : I2C (i2c-1)
  [BackLight] --o LLP : I2C (i2c-1)

  [Navcam] -- MLP : USB
  [Dockcam] -- MLP : USB
  [Hazcam] -- MLP : USB
  [Perchcam] -- MLP : USB

  EPS -- [StatusLights] : GPIO
  EPS o-- [SmartBatteries] : I2C/SMbus
}

interface "ISS Wifi" <<wifi>> as wifi
interface "ISS Payload LAN" <<wired>> as wired

etha -right- ethd
DockBoard -left- ethd
wired -down- ethd
DockBoard o-- DockControl  : I2C
EPS o-right- DockControl : "I2C (2x)"

HLP -- etha
MLP -- etha
wifi .left. MLP

MLP -- PerchArm : USB

etha -l- LLP

LLP "2" o-- PMC : I2C (i2c-2)
LLP "2" o-- SL : I2C (i2c-1)
LLP -- Speedcam : USB
LLP o-- EPS : I2C (i2c-1)

' To help get a nice layout:
PMC -[hidden]- SL
PMC -[hidden]> Speedcam
Speedcam -[hidden]> EPS

MLP --[hidden]-- LLP
HLP --[hidden]-- MLP

' Notation used in the diagram:
node ProcessorLegend COLOR_PSOM
node MicrocontrollerLegend COLOR_MPROC
ProcessorLegend -- [DeviceLegend] : communication protocol\n indicated

ProcessorLegend o-- MicrocontrollerLegend : losange indicates master\n if I2C device
note top of ProcessorLegend
Microprocessor
(System On Chip computer)
end note

note bottom of [DeviceLegend]
Hardware component (sensor
or actuator
end note

note bottom of MicrocontrollerLegend
Microntroller with custom
firmware
end note

@enduml
