@startuml

skinparam componentStyle uml2
'skinparam dpi 300

title MLP Freeflyer Nodes and Nodelet Managers

!define SHOW_MLP true
!define SHOW_ALL_TYPES true
!define SHOW_MANAGERS true

!include "nodes.puml"

@enduml
