@startuml

!include "colors.puml"

left to right direction

skinparam component {
    backgroundColor COLOR_9PASTEL_9
    borderColor COLOR_9SETONE_9
}


' Color definitions:
' BAC = Background / BOR = Border
' DEF = Default /  DIR = Direct / SEC = Secondary / MET = color inside color
!define BAC_DEF COLOR_9PASTEL_7     
!define BOR_DEF COLOR_9SETONE_7
!define BAC_DIR COLOR_9PASTEL_5
!define BOR_DIR COLOR_9SETONE_5
!define BAC_SEC COLOR_9PASTEL_4
!define BOR_SEC COLOR_9SETONE_4
!define BAC_MET COLOR_9PASTEL_9
!define BOR_MET COLOR_9SETONE_9

skinparam frame {
    backgroundColor BAC_DEF
    borderColor BOR_DEF 
    backgroundColor<<direct>> BAC_DIR
    borderColor<<direct>> BOR_DIR
    backgroundColor<<secondary>> BAC_SEC
    borderColor<<secondary>> BOR_SEC
}

skinparam file {
    backgroundColor BAC_MET
    borderColor BOR_MET 
    backgroundColor<<direct>> BAC_DIR
    borderColor<<direct>> BOR_DIR
    backgroundColor<<secondary>> BAC_SEC
    borderColor<<secondary>> BOR_SEC
}

skinparam package {
    backgroundColor COLOR_9PASTEL_7
 }

skinparam component {
    backgroundColor BAC_MET
    borderColor COLOR_9SETONE_9 
    backgroundColor<<direct>> BAC_DIR
    borderColor<<direct>> BOR_DIR
    backgroundColor<<secondary>> BAC_SEC
    borderColor<<secondary>> BOR_SEC
}

package "Astrobee Robot Software" as ars BAC_MET {

    frame "ARS Software" as ars_base {
        [hardware]
        [gnc]
        [localization]
        [mobility]
        [monitors]
        [management]
        [behaviors]
        [communications]
        frame "custom firmware" as avionics BAC_MET
    }

    frame "ARS Configuration" as ars_conf {
        file "robot parameters"
        frame "DDS configuration" {
            file "DDS QoS" <<secondary>>
            file "DDS Proxy IPs" <<secondary>>
        }
    }

    frame "Data (/res)" as data {
        file Maps
        file Zones
    }

    'layout: we use "left to right direction", so hints are orthogonals!
    ars_conf -[hidden]down- ars_base
    ars_conf -[hidden]up- data
}

package "ARS Dependencies" as ars_deps BAC_MET {

    frame DDS <<secondary>> 
    frame "ROS (only direct key packages listed)" as ROS {
        [ros_core]
        [ros_msgs]
        [ros_comm]
        [nodelet]
        [tf2]
        [geometry2]
        [image_common]
        [vision_opencv]
        [octomap]
    }
    frame OpenCV
    frame Eigen
    frame ALVAR
    frame BRISK
    frame DBoW2
    frame OpenMVG
    frame JsonCPP
    frame LuaJIT
    frame Video4Linux2
    frame MAVLink
    frame PicoFlexx
}

package "Ubuntu LTS (16.04)" as ubuntu BAC_MET {
    frame "ARS Custom (/etc)" as custom {
        file "Network Configuration" <<direct>>
        file "Wireless Configuration" <<direct>>
        file "Firewall Configuration"
        file "Robot Configuration"
    }
    frame "Anti Virus Software" as virus {
        [clamav engine]
        file "clamav database"
    }
 
    frame "Linux Comm Utilities" as tools {
        [ssh]
        [rsync]
        component "Samba Client" <<direct>>
        component "NTP Client" <<direct>>
        '[TreK Library]
    }
    
    frame "Linux OS" as ubu_os {
        component "core packages"
        component "utilities"
    }

    'layout
    custom -[hidden]up- ubu_os
    tools -[hidden]up- virus
}

frame "Linux \n**Kernel**" <<direct>> as kernel

ars --> ars_deps

ars_deps --> ubuntu

ubuntu -left-> kernel
' using right to left direction, so left is down!

!ifdef SHOW_LEGEND
package legend #FFFFFF {
    frame Library
    note right of Library
 Software or configuration without
 any effect on ISS systems or Crew
    end note
    frame Direct <<direct>>
    note right of Direct
Software or configuration with direct
interaction with ISS services or Crew
    end note
    frame Secondary <<secondary>>
    note right of Secondary
Software or tools with secondary effect only
on ISS services or Crew. Example: command
message can change, but transport layer remains
the same.
    end note
}
!endif

legend
  ROS : Robot Operating System
  DDS: Data Distribution Service
end legend

!ifdef SHOW_LEGEND
ars_deps -[hidden]- legend
!endif

@enduml

