# This will set up an Astrobee docker container using the non-NASA install instructions.
# You must set the docker context to be the repository root directory

FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu16.04

# try to suppress certain warnings during apt-get calls
ARG DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# install of apt-utils suppresses bogus warnings later
RUN apt-get update \
  && apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed" \
  && apt-get install -y \
    build-essential \
    git \
    lsb-release \
    sudo \
    wget \
  && rm -rf /var/lib/apt/lists/*
COPY ./scripts/setup/*.sh /setup/freeflyer/
COPY ./scripts/setup/debians /setup/freeflyer/debians

# this command is expected to have output on stderr, so redirect to suppress warning
RUN /setup/freeflyer/add_ros_repository.sh >/dev/null 2>&1

RUN apt-get update && apt-get install -y \
  libtinyxml-dev \
  ros-kinetic-opencv3 \
  python-rosdep \
  && rm -rf /var/lib/apt/lists/*

# suppress detached head warnings later
RUN git config --global advice.detachedHead false

RUN apt-get update \
  && /setup/freeflyer/debians/build_install_debians.sh \
  && rm -rf /var/lib/apt/lists/*

COPY ./scripts/setup/packages_*.lst /setup/freeflyer/
# note apt-get update is run within the following shell script
RUN /setup/freeflyer/install_desktop_16_04_packages.sh \
  && rm -rf /var/lib/apt/lists/*

COPY . /src/astrobee
RUN /src/astrobee/scripts/configure.sh -l -F -D -p /opt/astrobee -b /build/astrobee
RUN cd /build/astrobee && make install -j`nproc`
COPY ./astrobee/resources /opt/astrobee/share/astrobee/resources

#Add new sudo user
ENV USERNAME astrobee
RUN useradd -m $USERNAME && \
        echo "$USERNAME:$USERNAME" | chpasswd && \
        usermod --shell /bin/bash $USERNAME && \
        usermod -aG sudo $USERNAME && \
        echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME && \
        chmod 0440 /etc/sudoers.d/$USERNAME && \
        # Replace 1000 with your user/group id
        usermod  --uid 1000 $USERNAME && \
        groupmod --gid 1000 $USERNAME

#Add the entrypoint for docker
RUN echo "#!/bin/bash\nset -e\n\nsource \"/opt/ros/kinetic/setup.bash\"\nsource \"/build/astrobee/devel/setup.bash\"\nexport ASTROBEE_CONFIG_DIR=\"/src/astrobee/astrobee/config\"\nexec \"\$@\"" > /freeflyer_init.sh && \
  chmod +x /freeflyer_init.sh && \
  rosdep init && \
  rosdep update 2>&1 | egrep -v 'as root|fix-permissions'
