# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Get the calibration information for a lighthouse

string serial                         # Lighthouse serial number
uint8 id                              # ID in light callback
time timestamp                        # Time of last update
ff_msgs/ViveMotor vertical            # Vertical motor calibration data
ff_msgs/ViveMotor horizontal          # Horiztonal motor calibration data
