/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      struct ComponentInfoConfig {
        String32 name;
        KeyTypeSequence16 metadata;
      };

      typedef sequence<ComponentInfoConfig, 16> ComponentInfoConfigSequence16;

      //@copy-c-declaration class ComponentConfigTypeSupport;
      //@copy-c-declaration class ComponentConfigDataWriter;
      //@copy-c-declaration class ComponentConfigDataReader;
      //@copy-c-declaration struct ComponentConfigSeq;

      //@copy-declaration /**
      //@copy-declaration   * A list of valid components to listen for states
      //@copy-declaration   */
      valuetype ComponentConfig : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef ComponentConfigTypeSupport TypeSupport;
        //@copy-c-declaration typedef ComponentConfigDataWriter DataWriter;
        //@copy-c-declaration typedef ComponentConfigDataReader DataReader;
        //@copy-c-declaration typedef ComponentConfigSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef ComponentConfig Type;

        public ComponentInfoConfigSequence16 components;
      };
    };
  };
};
