/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      struct ComponentInfo {
        boolean present;
        boolean powered;
        float temperature;
        float current;

        ValueSequence16 metadata;
      };

      typedef sequence<ComponentInfo, 16> ComponentInfoSequence16;

      //@copy-c-declaration class ComponentStateTypeSupport;
      //@copy-c-declaration class ComponentStateDataWriter;
      //@copy-c-declaration class ComponentStateDataReader;
      //@copy-c-declaration struct ComponentStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * The state of a hardware component within Astrobee
      //@copy-declaration   * A state message is sent for each different component
      //@copy-declaration   */
      valuetype ComponentState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef ComponentStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef ComponentStateDataWriter DataWriter;
        //@copy-c-declaration typedef ComponentStateDataReader DataReader;
        //@copy-c-declaration typedef ComponentStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef ComponentState Type;

        public ComponentInfoSequence16 components;
      };

    };
  };
};
