#include "Message.idl"

module rapid
{
  module ext
  {
    module astrobee
    {
      //@copy-c-declaration class CompressedFileAckTypeSupport;
      //@copy-c-declaration class CompressedFileAckDataWriter;
      //@copy-c-declaration class CompressedFileAckDataReader;
      //@copy-c-declaration struct CompressedFileAckSeq;

      //@copy-declaration /**
      //@copy-declaration  * CompressedFileAck message delivers a compressed file, with the compression format used
      //@copy-declaration  */
      valuetype CompressedFileAck : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef CompressedFileAckTypeSupport TypeSupport;
        //@copy-c-declaration typedef CompressedFileAckDataWriter DataWriter;
        //@copy-c-declaration typedef CompressedFileAckDataReader DataReader;
        //@copy-c-declaration typedef CompressedFileAckSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef CompressedFileAck Type;

        //@copy-declaration /** ID of the sent CompressedFile */
        public long id;
	  };
	};
  };
};
