/*
 * Copyright 2017 (c) 2017 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      //@copy-declaration /**
      //@copy-declaration   * The stats on one of the cpus
      //@copy-declaration   * - total_load: total load percentage for the cpu
      //@copy-declaration   * - frequency: current operating frequency in Hz
      //@copy-declaration   */
      struct CpuInfo {
        float total_load;
        unsigned long frequency;
      };

      typedef sequence<CpuInfo, 8> CpuInfoSequence8;

      //@copy-declaration /**
      //@copy-declaration   * The stats of one of the machines
      //@copy-declaration   * - name: machine name
      //@copy-declaration   * - avg_total_load: average total load percentage
      //@copy-declaration   * - temperature: average of all thermal zones
      //@copy-declaration   * - cpus: array with info for each cpu
      //@copy-declaration   */
      struct MachineInfo {
        float avg_total_load;
        float temperature;
        CpuInfoSequence8 cpus;
      };

      typedef sequence<MachineInfo, 8> MachineInfoSequence8;

      //@copy-c-declaration class CpuStateTypeSupport;
      //@copy-c-declaration class CpuStateDataWriter;
      //@copy-c-declaration class CpuStateDataReader;
      //@copy-c-declaration struct CpuStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * The state of the cpus on Astrobee
      //@copy-declaration   */
      valuetype CpuState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4 && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4 && RTI_DDS_VERSION_MINOR == 5 && RTI_DDS_VERSION_RELEASE != 'f')
        //@copy-c-declaration typedef CpuStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef CpuStateDataWriter DataWriter;
        //@copy-c-declaration typedef CpuStateDataReader DataReader;
        //@copy-c-declaration typedef CpuStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef CpuState Type;

        //@copy-declaration /** Array with info for each machine */
        public MachineInfoSequence8 machines;
      };
    };
  };
};
