/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      //@copy-declaration /**
      //@copy-declaration  * DownlinkOption indicates if and when the data in this rostopic is downlinked
      //@copy-declaration  * <ul>
      //@copy-declaration  *   <li>NONE: topic is not saved to disk
      //@copy-declaration  *   <li>IMMEDIATE: topic saved to disk; upon docking it is downlinked
      //@copy-declaration  *   <li>DELAYED: topic saved to disk; upon docking it is transferred to ISS server for later downlink
      //@copy-declaration  * </ul>
      //@copy-declaration  */
      enum DownlinkOption {
        DATA_IMMEDIATE,
        DATA_DELAYED
      };

      //@copy-declaration /** Whether and how to save data from a rostopic
      //@copy-declaration   * - topicName: Name of rostopic
      //@copy-declaration   * - downlinkOption: when and if the topic should be downlinked
      //@copy-declaration   * - frequency: times per second to save the data (Hz)
      //@copy-declaration   */
      struct SaveSetting {
        String128 topicName;
        DownlinkOption downlinkOption;
        float frequency;
      };

      typedef sequence<SaveSetting, 64> SaveSettingSequence64;

      //@copy-c-declaration class DataToDiskStateTypeSupport;
      //@copy-c-declaration class DataToDiskStateDataWriter;
      //@copy-c-declaration class DataToDiskStateDataReader;
      //@copy-c-declaration struct DataToDiskStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * Save and downlink settings for all available rostopics
      //@copy-declaration   */
      valuetype DataToDiskState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef DataToDiskStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef DataToDiskStateDataWriter DataWriter;
        //@copy-c-declaration typedef DataToDiskStateDataReader DataReader;
        //@copy-c-declaration typedef DataToDiskStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef DataToDiskState Type;
	
        public String128 name;
        public boolean recording;
        public SaveSettingSequence64 topicSaveSettings;
      };

    };
  };
};
