/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      //@copy-declaration /** The stats on a disk within Astrobee
      //@copy-declaration   * - used: number of bytes used
      //@copy-declaration   */
      struct DiskInfo {
        long long used;
      };

      typedef sequence<DiskInfo, 8> DiskInfoSequence8;

      //@copy-c-declaration class DiskStateTypeSupport;
      //@copy-c-declaration class DiskStateDataWriter;
      //@copy-c-declaration class DiskStateDataReader;
      //@copy-c-declaration struct DiskStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * The state of the data partitions on Astrobee
      //@copy-declaration   */
      valuetype DiskState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef DiskStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef DiskStateDataWriter DataWriter;
        //@copy-c-declaration typedef DiskStateDataReader DataReader;
        //@copy-c-declaration typedef DiskStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef DiskState Type;

        public DiskInfoSequence8 filesystems;
      };

    };
  };
};
