/*
 * Copyright (c) 2015 United States Government as represented by the 
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      //@copy-declaration /** Information specific to the fault.
      //@copy-declaration   * - subsystem: index into the subsystems sequence
      //@copy-declaration   *              in the fault config message
      //@copy-declaration   * - node: index into the nodes sequence in the 
      //@copy-declaration   *         fault config message
      //@copy-declaration   * - faultId: id of the fault
      //@copy-declaration   * - warning: Whether the fault is a warning or not
      //@copy-declaration   * - faultDescription: short description of the fault
      //@copy-declaration   */
      struct FaultInfo {
        short subsystem;
        short node;
        long faultId;
        boolean warning;
        String64 faultDescription;
      };

      typedef sequence<FaultInfo, 256> FaultInfoSequence256;

      //@copy-c-declaration class FaultConfigTypeSupport;
      //@copy-c-declaration class FaultConfigDataWriter;
      //@copy-c-declaration class FaultConfigDataReader;
      //@copy-c-declaration struct FaultConfigSeq;

      //@copy-declaration /**
      //@copy-declaration   * The Fault config for Astrobee
      //@copy-declaration   */
      valuetype FaultConfig : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef FaultConfigTypeSupport TypeSupport;
        //@copy-c-declaration typedef FaultConfigDataWriter DataWriter;
        //@copy-c-declaration typedef FaultConfigDataReader DataReader;
        //@copy-c-declaration typedef FaultConfigSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef FaultConfig Type;

        //@copy-declaration /** Names of the subsystems in Astrobee */
        public String32Sequence16 subsystems;
        //@copy-declaration /** Names of the nodes in Astrobee */
        public String32Sequence128 nodes;
        //@copy-declaration /** A list of faults */ 
        public FaultInfoSequence256 faults; 
      };

    };
  };
};
