/*
 * Copyright 2017 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      struct Twist {
        Vec3d linear;
        Vec3d angular;
      };

      //@copy-c-declaration class GncControlStateTypeSupport;
      //@copy-c-declaration class GncControlStateDataWriter;
      //@copy-c-declaration class GncControlStateDataReader;
      //@copy-c-declaration struct GncControlSeq;

      //@copy-declaration /**
      //@copy-declaration   * The control state of the GNC.
      //@copy-declaration   */
      valuetype GncControlState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4 && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4 && RTI_DDS_VERSION_MINOR == 5 && RTI_DDS_VERSION_RELEASE != 'f')
        //@copy-c-declaration typedef GncControlStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef GncControlStateDataWriter DataWriter;
        //@copy-c-declaration typedef GncControlStateDataReader DataReader;
        //@copy-c-declaration typedef GncControlStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef GncControlState Type;

        public Transform3D pose;

        public Twist twist;

        public Twist accel;
      };
    };
  };
}; 

