/* 
 * Copyright 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      
      struct GuestScienceCommand {
        //@copy-declaration /** Name of command */
        String32 name;
        //@copy-declaration /** Actual syntax of the command */
        String128 command;
      };
      typedef sequence<GuestScienceCommand,32> GuestScienceCommandSequence32;

      struct GuestScienceApk {
        //@copy-declaration /** Full apk name */
        String128 apkName;
        //@copy-declaration /** Short name of apk */
        String32 shortName;
        //@copy-declaration /** Whether the apk is primary or secondary */
        boolean primary;
        //@copy-declaration /** A list of commands the apk will accept */
        GuestScienceCommandSequence32 commands;
      };
      typedef sequence<GuestScienceApk,32> GuestScienceApkSequence32;

      //@copy-c-declaration class GuestScienceConfigTypeSupport;
      //@copy-c-declaration class GuestScienceConfigDataWriter;
      //@copy-c-declaration class GuestScienceConfigDataReader;
      //@copy-c-declaration struct GuestScienceConfigSeq;

      //@copy-declaration /** 
      //@copy-declaration   * State message for guest science apk
      //@copy-declaration   */
      valuetype GuestScienceConfig : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef GuestScienceConfigTypeSupport TypeSupport;
        //@copy-c-declaration typedef GuestScienceConfigDataWriter DataWriter;
        //@copy-c-declaration typedef GuestScienceConfigDataReader DataReader;
        //@copy-c-declaration typedef GuestScienceConfigSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef GuestScienceConfig Type;

        //@copy-declaration /** List of apk states */
        public GuestScienceApkSequence32 apkStates;
      };
    };
  };
};
