/* 
 * Copyright 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      //@copy-declaration /**
      //@copy-declaration   * Guest Science Data Type - used to express the type
      //@copy-declaration   * of data stored in the data octet
      //@copy-declaration   */
      enum GuestScienceDataType {
        GUEST_SCIENCE_STRING,
        GUEST_SCIENCE_JSON,
        GUEST_SCIENCE_BINARY
      };

      //@copy-c-declaration class GuestScienceDataTypeSupport;
      //@copy-c-declaration class GuestScienceDataDataWriter;
      //@copy-c-declaration class GuestScienceDataDataReader;
      //@copy-c-declaration struct GuestScienceDataSeq;

      //@copy-declaration /**
      //@copy-declaration   * Guest science data sent to the ground
      //@copy-declaration   */
      valuetype GuestScienceData : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef GuestScienceDataTypeSupport TypeSupport;
        //@copy-c-declaration typedef GuestScienceDataWriter DataWriter;
        //@copy-c-declaration typedef GuestScienceDataReader DataReader;
        //@copy-c-declaration typedef GuestScienceDataSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef GuestScienceData Type;

        //@copy-declaration /** Full name of apk */ 
        public String128 apkName;
        //@copy-declaration /** Type of data being sent */
        public GuestScienceDataType type;
        //@copy-declaration /** String to classify the kind of data */
        public String32 topic;
        //@copy-declaration /** Data from the apk */
        public OctetSequence2K data;
      };
    };
  };
};
