/* 
 * Copyright 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      typedef sequence<boolean, 32> BooleanSequence32;

      //@copy-c-declaration class GuestScienceStateTypeSupport;
      //@copy-c-declaration class GuestScienceStateDataWriter;
      //@copy-c-declaration class GuestScienceStateDataReader;
      //@copy-c-declaration struct GuestScienceStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * Guest science state, list of whether apks are 
      //@copy-declaration   * running or not
      //@copy-declaration   */
      valuetype GuestScienceState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef GuestScienceStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef GuestScienceStateDataWriter DataWriter;
        //@copy-c-declaration typedef GuestScienceStateDataReader DataReader;
        //@copy-c-declaration typedef GuestScienceStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef GuestScienceState Type;

        //@copy-declaration /** A list of whether an apk is running or not */
        public BooleanSequence32 runningApks;
      };
    };
  };
};
