/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      //@copy-c-declaration class InertialPropertiesTypeSupport;
      //@copy-c-declaration class InertialPropertiesDataWriter;
      //@copy-c-declaration class InertialPropertiesDataReader;
      //@copy-c-declaration struct InertialPropertiesSeq;

      //@copy-declaration /**
      //@copy-declaration   * Network state of Astrobee
      //@copy-declaration   */
      valuetype InertialProperties : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef InertialPropertiesTypeSupport TypeSupport;
        //@copy-c-declaration typedef InertialPropertiesDataWriter DataWriter;
        //@copy-c-declaration typedef InertialPropertiesDataReader DataReader;
        //@copy-c-declaration typedef InertialPropertiesSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef InertialProperties Type;

	//@copy-declaration /** Name of this set of mass properties */
	public String32 name;

        //@copy-declaration /** Mass of the Astrobee in kg, used for control calculations */
        public float mass;

        //@copy-declaration /** Center of mass of thhe Astrobee, used for control calculations */
        public Vec3d centerOfMass;

        //@copy-declaration /** Inertia matrix of Astrobee, used for control calculations */
        public Mat33f matrix;
      };
    };
  };
};
