/*
 * Copyright (c) 2015 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {

      //@copy-declaration /**
      //@copy-declaration  * Severity level constants
      //@copy-declaration  * <ul>
      //@copy-declaration  *   <li>DEBUG: debug level
      //@copy-declaration  *   <li>INFO: general level
      //@copy-declaration  *   <li>WARN: warning level
      //@copy-declaration  *   <li>ERROR: error level
      //@copy-declaration  *   <li>FATAL: fatal/critical level
      //@copy-declaration  * </ul>
      //@copy-declaration  */
      enum SeverityLevel {
        SEVERITY_LEVEL_DEBUG,
        SEVERITY_LEVEL_INFO,
        SEVERITY_LEVEL_WARN,
        SEVERITY_LEVEL_ERROR,
        SEVERITY_LEVEL_FATAL
      };

      //@copy-c-declaration class LogSampleTypeSupport;
      //@copy-c-declaration class LogSampleDataWriter;
      //@copy-c-declaration class LogSampleDataReader;
      //@copy-c-declaration struct LogSampleSeg;

      //@copy-declaration /**
      //@copy-declaration   * Message containing ros output.
      //@copy-declaration   */
      valuetype LogSample : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef LogSampleTypeSupport TypeSupport;
        //@copy-c-declaration typedef LogSampleDataWriter DataWriter;
        //@copy-c-declaration typedef LogSampleDataReader DataReader;
        //@copy-c-declaration typedef LogSampleSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef LogSample Type;

        //@copy-declaration /**  @see SeverityLevel */
        public SeverityLevel level;

        //@copy-declaration /**  Name of node publishing message */
        public String64 name;

        //@copy-declaration /**  Message */
        public String1K msg;
      };

    };
  };
};
