/*
 * Copyright 2015 (c) 2015 Intelligent Robotics Group, NASA ARC
 */

#include "Message.idl"

module rapid {
  module ext {
    module astrobee {
      typedef sequence<boolean, 4> BooleanSequence4;

      //@copy-c-declaration class PayloadStateTypeSupport;
      //@copy-c-declaration class PayloadStateDataWriter;
      //@copy-c-declaration class PayloadStateDataReader;
      //@copy-c-declaration struct PayloadStateSeq;

      //@copy-declaration /**
      //@copy-declaration   * The state of Astrobee's payloads
      //@copy-declaration   */
      valuetype PayloadState : Message {
        //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
        //@copy-c-declaration typedef PayloadStateTypeSupport TypeSupport;
        //@copy-c-declaration typedef PayloadStateDataWriter DataWriter;
        //@copy-c-declaration typedef PayloadStateDataReader DataReader;
        //@copy-c-declaration typedef PayloadStateSeq Seq;
        //@copy-c-declaration #endif
        //@copy-c-declaration typedef PayloadState Type;

        public BooleanSequence4 powered;
      };
    };
  };
};
