/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_erk4_chain_nm3_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[198] = {12, 15, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[30] = {12, 15, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[63] = {3, 15, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[21] = {3, 15, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
static const casadi_int casadi_s4[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[5] = {12, 1, 0, 1, 0};
static const casadi_int casadi_s6[5] = {12, 1, 0, 1, 1};
static const casadi_int casadi_s7[5] = {12, 1, 0, 1, 2};
static const casadi_int casadi_s8[5] = {12, 1, 0, 1, 3};
static const casadi_int casadi_s9[5] = {12, 1, 0, 1, 4};
static const casadi_int casadi_s10[5] = {12, 1, 0, 1, 5};
static const casadi_int casadi_s11[5] = {12, 1, 0, 1, 6};
static const casadi_int casadi_s12[5] = {12, 1, 0, 1, 7};
static const casadi_int casadi_s13[5] = {12, 1, 0, 1, 8};
static const casadi_int casadi_s14[5] = {12, 1, 0, 1, 9};
static const casadi_int casadi_s15[5] = {12, 1, 0, 1, 10};
static const casadi_int casadi_s16[5] = {12, 1, 0, 1, 11};
static const casadi_int casadi_s17[8] = {0, 1, 2, 3, 4, 5, 6, 9};
static const casadi_int casadi_s18[8] = {0, 15, 30, 45, 60, 75, 90, 99};
static const casadi_int casadi_s19[8] = {0, 1, 2, 3, 4, 5, 7, 10};
static const casadi_int casadi_s20[8] = {1, 16, 31, 46, 61, 76, 93, 101};
static const casadi_int casadi_s21[8] = {0, 1, 2, 3, 4, 5, 8, 11};
static const casadi_int casadi_s22[8] = {2, 17, 32, 47, 62, 77, 96, 103};
static const casadi_int casadi_s23[7] = {9, 24, 39, 54, 69, 84, 91};
static const casadi_int casadi_s24[7] = {0, 1, 2, 3, 4, 5, 7};
static const casadi_int casadi_s25[7] = {10, 25, 40, 55, 70, 85, 94};
static const casadi_int casadi_s26[7] = {0, 1, 2, 3, 4, 5, 8};
static const casadi_int casadi_s27[7] = {11, 26, 41, 56, 71, 86, 97};
static const casadi_int casadi_s28[8] = {12, 27, 42, 57, 72, 87, 92, 100};
static const casadi_int casadi_s29[8] = {13, 28, 43, 58, 73, 88, 95, 102};
static const casadi_int casadi_s30[8] = {14, 29, 44, 59, 74, 89, 98, 104};
static const casadi_int casadi_s31[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s32[120] = {15, 12, 0, 15, 30, 45, 60, 75, 90, 93, 96, 99, 101, 103, 105, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 9, 12, 1, 10, 13, 2, 11, 14, 0, 12, 1, 13, 2, 14};

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

/* f:(i0[12],i1[3])->(o0[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=3.3333333333333336e+01;
  a1=1.;
  a2=3.3000000000000002e-02;
  a3=arg[0] ? arg[0][6] : 0;
  a4=arg[0] ? arg[0][0] : 0;
  a3=(a3-a4);
  a5=casadi_sq(a3);
  a6=arg[0] ? arg[0][7] : 0;
  a7=arg[0] ? arg[0][1] : 0;
  a6=(a6-a7);
  a8=casadi_sq(a6);
  a5=(a5+a8);
  a8=arg[0] ? arg[0][8] : 0;
  a9=arg[0] ? arg[0][2] : 0;
  a8=(a8-a9);
  a10=casadi_sq(a8);
  a5=(a5+a10);
  a5=sqrt(a5);
  a5=(a2/a5);
  a5=(a1-a5);
  a3=(a5*a3);
  a10=casadi_sq(a4);
  a11=casadi_sq(a7);
  a10=(a10+a11);
  a11=casadi_sq(a9);
  a10=(a10+a11);
  a10=sqrt(a10);
  a2=(a2/a10);
  a1=(a1-a2);
  a4=(a1*a4);
  a3=(a3-a4);
  a3=(a0*a3);
  if (res[0]!=0) res[0][3]=a3;
  a6=(a5*a6);
  a7=(a1*a7);
  a6=(a6-a7);
  a6=(a0*a6);
  if (res[0]!=0) res[0][4]=a6;
  a5=(a5*a8);
  a1=(a1*a9);
  a5=(a5-a1);
  a0=(a0*a5);
  a5=9.8100000000000005e+00;
  a0=(a0-a5);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0] ? arg[0][9] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0] ? arg[0][10] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0] ? arg[0][11] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1] ? arg[1][2] : 0;
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

/* fwd15_f:(i0[12],i1[3],out_o0[12x1,0nz],fwd_i0[12x15],fwd_i1[3x15])->(fwd_o0[12x15]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3] ? arg[3][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3] ? arg[3][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3] ? arg[3][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=3.3333333333333336e+01;
  a1=arg[0] ? arg[0][6] : 0;
  a2=arg[0] ? arg[0][0] : 0;
  a1=(a1-a2);
  a3=3.3000000000000002e-02;
  a4=casadi_sq(a1);
  a5=arg[0] ? arg[0][7] : 0;
  a6=arg[0] ? arg[0][1] : 0;
  a5=(a5-a6);
  a7=casadi_sq(a5);
  a4=(a4+a7);
  a7=arg[0] ? arg[0][8] : 0;
  a8=arg[0] ? arg[0][2] : 0;
  a7=(a7-a8);
  a9=casadi_sq(a7);
  a4=(a4+a9);
  a4=sqrt(a4);
  a9=(a3/a4);
  a10=(a9/a4);
  a11=(a1+a1);
  a12=arg[3] ? arg[3][6] : 0;
  a13=arg[3] ? arg[3][0] : 0;
  a12=(a12-a13);
  a14=(a11*a12);
  a15=(a5+a5);
  a16=arg[3] ? arg[3][7] : 0;
  a17=arg[3] ? arg[3][1] : 0;
  a16=(a16-a17);
  a18=(a15*a16);
  a14=(a14+a18);
  a18=(a7+a7);
  a19=arg[3] ? arg[3][8] : 0;
  a20=arg[3] ? arg[3][2] : 0;
  a19=(a19-a20);
  a21=(a18*a19);
  a14=(a14+a21);
  a4=(a4+a4);
  a14=(a14/a4);
  a14=(a10*a14);
  a21=(a1*a14);
  a22=1.;
  a9=(a22-a9);
  a12=(a9*a12);
  a21=(a21+a12);
  a12=casadi_sq(a2);
  a23=casadi_sq(a6);
  a12=(a12+a23);
  a23=casadi_sq(a8);
  a12=(a12+a23);
  a12=sqrt(a12);
  a3=(a3/a12);
  a23=(a3/a12);
  a24=(a2+a2);
  a25=(a24*a13);
  a26=(a6+a6);
  a27=(a26*a17);
  a25=(a25+a27);
  a27=(a8+a8);
  a28=(a27*a20);
  a25=(a25+a28);
  a12=(a12+a12);
  a25=(a25/a12);
  a25=(a23*a25);
  a28=(a2*a25);
  a22=(a22-a3);
  a13=(a22*a13);
  a28=(a28+a13);
  a21=(a21-a28);
  a21=(a0*a21);
  if (res[0]!=0) res[0][3]=a21;
  a21=(a5*a14);
  a16=(a9*a16);
  a21=(a21+a16);
  a16=(a6*a25);
  a17=(a22*a17);
  a16=(a16+a17);
  a21=(a21-a16);
  a21=(a0*a21);
  if (res[0]!=0) res[0][4]=a21;
  a14=(a7*a14);
  a19=(a9*a19);
  a14=(a14+a19);
  a25=(a8*a25);
  a20=(a22*a20);
  a25=(a25+a20);
  a14=(a14-a25);
  a14=(a0*a14);
  if (res[0]!=0) res[0][5]=a14;
  a14=arg[3] ? arg[3][9] : 0;
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[3] ? arg[3][10] : 0;
  if (res[0]!=0) res[0][7]=a14;
  a14=arg[3] ? arg[3][11] : 0;
  if (res[0]!=0) res[0][8]=a14;
  a14=arg[4] ? arg[4][0] : 0;
  if (res[0]!=0) res[0][9]=a14;
  a14=arg[4] ? arg[4][1] : 0;
  if (res[0]!=0) res[0][10]=a14;
  a14=arg[4] ? arg[4][2] : 0;
  if (res[0]!=0) res[0][11]=a14;
  a14=arg[3] ? arg[3][15] : 0;
  if (res[0]!=0) res[0][12]=a14;
  a14=arg[3] ? arg[3][16] : 0;
  if (res[0]!=0) res[0][13]=a14;
  a14=arg[3] ? arg[3][17] : 0;
  if (res[0]!=0) res[0][14]=a14;
  a14=arg[3] ? arg[3][18] : 0;
  a25=arg[3] ? arg[3][12] : 0;
  a14=(a14-a25);
  a20=(a11*a14);
  a19=arg[3] ? arg[3][19] : 0;
  a21=arg[3] ? arg[3][13] : 0;
  a19=(a19-a21);
  a16=(a15*a19);
  a20=(a20+a16);
  a16=arg[3] ? arg[3][20] : 0;
  a17=arg[3] ? arg[3][14] : 0;
  a16=(a16-a17);
  a28=(a18*a16);
  a20=(a20+a28);
  a20=(a20/a4);
  a20=(a10*a20);
  a28=(a1*a20);
  a14=(a9*a14);
  a28=(a28+a14);
  a14=(a24*a25);
  a13=(a26*a21);
  a14=(a14+a13);
  a13=(a27*a17);
  a14=(a14+a13);
  a14=(a14/a12);
  a14=(a23*a14);
  a13=(a2*a14);
  a25=(a22*a25);
  a13=(a13+a25);
  a28=(a28-a13);
  a28=(a0*a28);
  if (res[0]!=0) res[0][15]=a28;
  a28=(a5*a20);
  a19=(a9*a19);
  a28=(a28+a19);
  a19=(a6*a14);
  a21=(a22*a21);
  a19=(a19+a21);
  a28=(a28-a19);
  a28=(a0*a28);
  if (res[0]!=0) res[0][16]=a28;
  a20=(a7*a20);
  a16=(a9*a16);
  a20=(a20+a16);
  a14=(a8*a14);
  a17=(a22*a17);
  a14=(a14+a17);
  a20=(a20-a14);
  a20=(a0*a20);
  if (res[0]!=0) res[0][17]=a20;
  a20=arg[3] ? arg[3][21] : 0;
  if (res[0]!=0) res[0][18]=a20;
  a20=arg[3] ? arg[3][22] : 0;
  if (res[0]!=0) res[0][19]=a20;
  a20=arg[3] ? arg[3][23] : 0;
  if (res[0]!=0) res[0][20]=a20;
  a20=arg[4] ? arg[4][3] : 0;
  if (res[0]!=0) res[0][21]=a20;
  a20=arg[4] ? arg[4][4] : 0;
  if (res[0]!=0) res[0][22]=a20;
  a20=arg[4] ? arg[4][5] : 0;
  if (res[0]!=0) res[0][23]=a20;
  a20=arg[3] ? arg[3][27] : 0;
  if (res[0]!=0) res[0][24]=a20;
  a20=arg[3] ? arg[3][28] : 0;
  if (res[0]!=0) res[0][25]=a20;
  a20=arg[3] ? arg[3][29] : 0;
  if (res[0]!=0) res[0][26]=a20;
  a20=arg[3] ? arg[3][30] : 0;
  a14=arg[3] ? arg[3][24] : 0;
  a20=(a20-a14);
  a17=(a11*a20);
  a16=arg[3] ? arg[3][31] : 0;
  a28=arg[3] ? arg[3][25] : 0;
  a16=(a16-a28);
  a19=(a15*a16);
  a17=(a17+a19);
  a19=arg[3] ? arg[3][32] : 0;
  a21=arg[3] ? arg[3][26] : 0;
  a19=(a19-a21);
  a13=(a18*a19);
  a17=(a17+a13);
  a17=(a17/a4);
  a17=(a10*a17);
  a13=(a1*a17);
  a20=(a9*a20);
  a13=(a13+a20);
  a20=(a24*a14);
  a25=(a26*a28);
  a20=(a20+a25);
  a25=(a27*a21);
  a20=(a20+a25);
  a20=(a20/a12);
  a20=(a23*a20);
  a25=(a2*a20);
  a14=(a22*a14);
  a25=(a25+a14);
  a13=(a13-a25);
  a13=(a0*a13);
  if (res[0]!=0) res[0][27]=a13;
  a13=(a5*a17);
  a16=(a9*a16);
  a13=(a13+a16);
  a16=(a6*a20);
  a28=(a22*a28);
  a16=(a16+a28);
  a13=(a13-a16);
  a13=(a0*a13);
  if (res[0]!=0) res[0][28]=a13;
  a17=(a7*a17);
  a19=(a9*a19);
  a17=(a17+a19);
  a20=(a8*a20);
  a21=(a22*a21);
  a20=(a20+a21);
  a17=(a17-a20);
  a17=(a0*a17);
  if (res[0]!=0) res[0][29]=a17;
  a17=arg[3] ? arg[3][33] : 0;
  if (res[0]!=0) res[0][30]=a17;
  a17=arg[3] ? arg[3][34] : 0;
  if (res[0]!=0) res[0][31]=a17;
  a17=arg[3] ? arg[3][35] : 0;
  if (res[0]!=0) res[0][32]=a17;
  a17=arg[4] ? arg[4][6] : 0;
  if (res[0]!=0) res[0][33]=a17;
  a17=arg[4] ? arg[4][7] : 0;
  if (res[0]!=0) res[0][34]=a17;
  a17=arg[4] ? arg[4][8] : 0;
  if (res[0]!=0) res[0][35]=a17;
  a17=arg[3] ? arg[3][39] : 0;
  if (res[0]!=0) res[0][36]=a17;
  a17=arg[3] ? arg[3][40] : 0;
  if (res[0]!=0) res[0][37]=a17;
  a17=arg[3] ? arg[3][41] : 0;
  if (res[0]!=0) res[0][38]=a17;
  a17=arg[3] ? arg[3][42] : 0;
  a20=arg[3] ? arg[3][36] : 0;
  a17=(a17-a20);
  a21=(a11*a17);
  a19=arg[3] ? arg[3][43] : 0;
  a13=arg[3] ? arg[3][37] : 0;
  a19=(a19-a13);
  a16=(a15*a19);
  a21=(a21+a16);
  a16=arg[3] ? arg[3][44] : 0;
  a28=arg[3] ? arg[3][38] : 0;
  a16=(a16-a28);
  a25=(a18*a16);
  a21=(a21+a25);
  a21=(a21/a4);
  a21=(a10*a21);
  a25=(a1*a21);
  a17=(a9*a17);
  a25=(a25+a17);
  a17=(a24*a20);
  a14=(a26*a13);
  a17=(a17+a14);
  a14=(a27*a28);
  a17=(a17+a14);
  a17=(a17/a12);
  a17=(a23*a17);
  a14=(a2*a17);
  a20=(a22*a20);
  a14=(a14+a20);
  a25=(a25-a14);
  a25=(a0*a25);
  if (res[0]!=0) res[0][39]=a25;
  a25=(a5*a21);
  a19=(a9*a19);
  a25=(a25+a19);
  a19=(a6*a17);
  a13=(a22*a13);
  a19=(a19+a13);
  a25=(a25-a19);
  a25=(a0*a25);
  if (res[0]!=0) res[0][40]=a25;
  a21=(a7*a21);
  a16=(a9*a16);
  a21=(a21+a16);
  a17=(a8*a17);
  a28=(a22*a28);
  a17=(a17+a28);
  a21=(a21-a17);
  a21=(a0*a21);
  if (res[0]!=0) res[0][41]=a21;
  a21=arg[3] ? arg[3][45] : 0;
  if (res[0]!=0) res[0][42]=a21;
  a21=arg[3] ? arg[3][46] : 0;
  if (res[0]!=0) res[0][43]=a21;
  a21=arg[3] ? arg[3][47] : 0;
  if (res[0]!=0) res[0][44]=a21;
  a21=arg[4] ? arg[4][9] : 0;
  if (res[0]!=0) res[0][45]=a21;
  a21=arg[4] ? arg[4][10] : 0;
  if (res[0]!=0) res[0][46]=a21;
  a21=arg[4] ? arg[4][11] : 0;
  if (res[0]!=0) res[0][47]=a21;
  a21=arg[3] ? arg[3][51] : 0;
  if (res[0]!=0) res[0][48]=a21;
  a21=arg[3] ? arg[3][52] : 0;
  if (res[0]!=0) res[0][49]=a21;
  a21=arg[3] ? arg[3][53] : 0;
  if (res[0]!=0) res[0][50]=a21;
  a21=arg[3] ? arg[3][54] : 0;
  a17=arg[3] ? arg[3][48] : 0;
  a21=(a21-a17);
  a28=(a11*a21);
  a16=arg[3] ? arg[3][55] : 0;
  a25=arg[3] ? arg[3][49] : 0;
  a16=(a16-a25);
  a19=(a15*a16);
  a28=(a28+a19);
  a19=arg[3] ? arg[3][56] : 0;
  a13=arg[3] ? arg[3][50] : 0;
  a19=(a19-a13);
  a14=(a18*a19);
  a28=(a28+a14);
  a28=(a28/a4);
  a28=(a10*a28);
  a14=(a1*a28);
  a21=(a9*a21);
  a14=(a14+a21);
  a21=(a24*a17);
  a20=(a26*a25);
  a21=(a21+a20);
  a20=(a27*a13);
  a21=(a21+a20);
  a21=(a21/a12);
  a21=(a23*a21);
  a20=(a2*a21);
  a17=(a22*a17);
  a20=(a20+a17);
  a14=(a14-a20);
  a14=(a0*a14);
  if (res[0]!=0) res[0][51]=a14;
  a14=(a5*a28);
  a16=(a9*a16);
  a14=(a14+a16);
  a16=(a6*a21);
  a25=(a22*a25);
  a16=(a16+a25);
  a14=(a14-a16);
  a14=(a0*a14);
  if (res[0]!=0) res[0][52]=a14;
  a28=(a7*a28);
  a19=(a9*a19);
  a28=(a28+a19);
  a21=(a8*a21);
  a13=(a22*a13);
  a21=(a21+a13);
  a28=(a28-a21);
  a28=(a0*a28);
  if (res[0]!=0) res[0][53]=a28;
  a28=arg[3] ? arg[3][57] : 0;
  if (res[0]!=0) res[0][54]=a28;
  a28=arg[3] ? arg[3][58] : 0;
  if (res[0]!=0) res[0][55]=a28;
  a28=arg[3] ? arg[3][59] : 0;
  if (res[0]!=0) res[0][56]=a28;
  a28=arg[4] ? arg[4][12] : 0;
  if (res[0]!=0) res[0][57]=a28;
  a28=arg[4] ? arg[4][13] : 0;
  if (res[0]!=0) res[0][58]=a28;
  a28=arg[4] ? arg[4][14] : 0;
  if (res[0]!=0) res[0][59]=a28;
  a28=arg[3] ? arg[3][63] : 0;
  if (res[0]!=0) res[0][60]=a28;
  a28=arg[3] ? arg[3][64] : 0;
  if (res[0]!=0) res[0][61]=a28;
  a28=arg[3] ? arg[3][65] : 0;
  if (res[0]!=0) res[0][62]=a28;
  a28=arg[3] ? arg[3][66] : 0;
  a21=arg[3] ? arg[3][60] : 0;
  a28=(a28-a21);
  a13=(a11*a28);
  a19=arg[3] ? arg[3][67] : 0;
  a14=arg[3] ? arg[3][61] : 0;
  a19=(a19-a14);
  a16=(a15*a19);
  a13=(a13+a16);
  a16=arg[3] ? arg[3][68] : 0;
  a25=arg[3] ? arg[3][62] : 0;
  a16=(a16-a25);
  a20=(a18*a16);
  a13=(a13+a20);
  a13=(a13/a4);
  a13=(a10*a13);
  a20=(a1*a13);
  a28=(a9*a28);
  a20=(a20+a28);
  a28=(a24*a21);
  a17=(a26*a14);
  a28=(a28+a17);
  a17=(a27*a25);
  a28=(a28+a17);
  a28=(a28/a12);
  a28=(a23*a28);
  a17=(a2*a28);
  a21=(a22*a21);
  a17=(a17+a21);
  a20=(a20-a17);
  a20=(a0*a20);
  if (res[0]!=0) res[0][63]=a20;
  a20=(a5*a13);
  a19=(a9*a19);
  a20=(a20+a19);
  a19=(a6*a28);
  a14=(a22*a14);
  a19=(a19+a14);
  a20=(a20-a19);
  a20=(a0*a20);
  if (res[0]!=0) res[0][64]=a20;
  a13=(a7*a13);
  a16=(a9*a16);
  a13=(a13+a16);
  a28=(a8*a28);
  a25=(a22*a25);
  a28=(a28+a25);
  a13=(a13-a28);
  a13=(a0*a13);
  if (res[0]!=0) res[0][65]=a13;
  a13=arg[3] ? arg[3][69] : 0;
  if (res[0]!=0) res[0][66]=a13;
  a13=arg[3] ? arg[3][70] : 0;
  if (res[0]!=0) res[0][67]=a13;
  a13=arg[3] ? arg[3][71] : 0;
  if (res[0]!=0) res[0][68]=a13;
  a13=arg[4] ? arg[4][15] : 0;
  if (res[0]!=0) res[0][69]=a13;
  a13=arg[4] ? arg[4][16] : 0;
  if (res[0]!=0) res[0][70]=a13;
  a13=arg[4] ? arg[4][17] : 0;
  if (res[0]!=0) res[0][71]=a13;
  a13=arg[3] ? arg[3][75] : 0;
  if (res[0]!=0) res[0][72]=a13;
  a13=arg[3] ? arg[3][76] : 0;
  if (res[0]!=0) res[0][73]=a13;
  a13=arg[3] ? arg[3][77] : 0;
  if (res[0]!=0) res[0][74]=a13;
  a13=arg[3] ? arg[3][78] : 0;
  a28=arg[3] ? arg[3][72] : 0;
  a13=(a13-a28);
  a25=(a11*a13);
  a16=arg[3] ? arg[3][79] : 0;
  a20=arg[3] ? arg[3][73] : 0;
  a16=(a16-a20);
  a19=(a15*a16);
  a25=(a25+a19);
  a19=arg[3] ? arg[3][80] : 0;
  a14=arg[3] ? arg[3][74] : 0;
  a19=(a19-a14);
  a17=(a18*a19);
  a25=(a25+a17);
  a25=(a25/a4);
  a25=(a10*a25);
  a17=(a1*a25);
  a13=(a9*a13);
  a17=(a17+a13);
  a13=(a24*a28);
  a21=(a26*a20);
  a13=(a13+a21);
  a21=(a27*a14);
  a13=(a13+a21);
  a13=(a13/a12);
  a13=(a23*a13);
  a21=(a2*a13);
  a28=(a22*a28);
  a21=(a21+a28);
  a17=(a17-a21);
  a17=(a0*a17);
  if (res[0]!=0) res[0][75]=a17;
  a17=(a5*a25);
  a16=(a9*a16);
  a17=(a17+a16);
  a16=(a6*a13);
  a20=(a22*a20);
  a16=(a16+a20);
  a17=(a17-a16);
  a17=(a0*a17);
  if (res[0]!=0) res[0][76]=a17;
  a25=(a7*a25);
  a19=(a9*a19);
  a25=(a25+a19);
  a13=(a8*a13);
  a14=(a22*a14);
  a13=(a13+a14);
  a25=(a25-a13);
  a25=(a0*a25);
  if (res[0]!=0) res[0][77]=a25;
  a25=arg[3] ? arg[3][81] : 0;
  if (res[0]!=0) res[0][78]=a25;
  a25=arg[3] ? arg[3][82] : 0;
  if (res[0]!=0) res[0][79]=a25;
  a25=arg[3] ? arg[3][83] : 0;
  if (res[0]!=0) res[0][80]=a25;
  a25=arg[4] ? arg[4][18] : 0;
  if (res[0]!=0) res[0][81]=a25;
  a25=arg[4] ? arg[4][19] : 0;
  if (res[0]!=0) res[0][82]=a25;
  a25=arg[4] ? arg[4][20] : 0;
  if (res[0]!=0) res[0][83]=a25;
  a25=arg[3] ? arg[3][87] : 0;
  if (res[0]!=0) res[0][84]=a25;
  a25=arg[3] ? arg[3][88] : 0;
  if (res[0]!=0) res[0][85]=a25;
  a25=arg[3] ? arg[3][89] : 0;
  if (res[0]!=0) res[0][86]=a25;
  a25=arg[3] ? arg[3][90] : 0;
  a13=arg[3] ? arg[3][84] : 0;
  a25=(a25-a13);
  a14=(a11*a25);
  a19=arg[3] ? arg[3][91] : 0;
  a17=arg[3] ? arg[3][85] : 0;
  a19=(a19-a17);
  a16=(a15*a19);
  a14=(a14+a16);
  a16=arg[3] ? arg[3][92] : 0;
  a20=arg[3] ? arg[3][86] : 0;
  a16=(a16-a20);
  a21=(a18*a16);
  a14=(a14+a21);
  a14=(a14/a4);
  a14=(a10*a14);
  a21=(a1*a14);
  a25=(a9*a25);
  a21=(a21+a25);
  a25=(a24*a13);
  a28=(a26*a17);
  a25=(a25+a28);
  a28=(a27*a20);
  a25=(a25+a28);
  a25=(a25/a12);
  a25=(a23*a25);
  a28=(a2*a25);
  a13=(a22*a13);
  a28=(a28+a13);
  a21=(a21-a28);
  a21=(a0*a21);
  if (res[0]!=0) res[0][87]=a21;
  a21=(a5*a14);
  a19=(a9*a19);
  a21=(a21+a19);
  a19=(a6*a25);
  a17=(a22*a17);
  a19=(a19+a17);
  a21=(a21-a19);
  a21=(a0*a21);
  if (res[0]!=0) res[0][88]=a21;
  a14=(a7*a14);
  a16=(a9*a16);
  a14=(a14+a16);
  a25=(a8*a25);
  a20=(a22*a20);
  a25=(a25+a20);
  a14=(a14-a25);
  a14=(a0*a14);
  if (res[0]!=0) res[0][89]=a14;
  a14=arg[3] ? arg[3][93] : 0;
  if (res[0]!=0) res[0][90]=a14;
  a14=arg[3] ? arg[3][94] : 0;
  if (res[0]!=0) res[0][91]=a14;
  a14=arg[3] ? arg[3][95] : 0;
  if (res[0]!=0) res[0][92]=a14;
  a14=arg[4] ? arg[4][21] : 0;
  if (res[0]!=0) res[0][93]=a14;
  a14=arg[4] ? arg[4][22] : 0;
  if (res[0]!=0) res[0][94]=a14;
  a14=arg[4] ? arg[4][23] : 0;
  if (res[0]!=0) res[0][95]=a14;
  a14=arg[3] ? arg[3][99] : 0;
  if (res[0]!=0) res[0][96]=a14;
  a14=arg[3] ? arg[3][100] : 0;
  if (res[0]!=0) res[0][97]=a14;
  a14=arg[3] ? arg[3][101] : 0;
  if (res[0]!=0) res[0][98]=a14;
  a14=arg[3] ? arg[3][102] : 0;
  a25=arg[3] ? arg[3][96] : 0;
  a14=(a14-a25);
  a20=(a11*a14);
  a16=arg[3] ? arg[3][103] : 0;
  a21=arg[3] ? arg[3][97] : 0;
  a16=(a16-a21);
  a19=(a15*a16);
  a20=(a20+a19);
  a19=arg[3] ? arg[3][104] : 0;
  a17=arg[3] ? arg[3][98] : 0;
  a19=(a19-a17);
  a28=(a18*a19);
  a20=(a20+a28);
  a20=(a20/a4);
  a20=(a10*a20);
  a28=(a1*a20);
  a14=(a9*a14);
  a28=(a28+a14);
  a14=(a24*a25);
  a13=(a26*a21);
  a14=(a14+a13);
  a13=(a27*a17);
  a14=(a14+a13);
  a14=(a14/a12);
  a14=(a23*a14);
  a13=(a2*a14);
  a25=(a22*a25);
  a13=(a13+a25);
  a28=(a28-a13);
  a28=(a0*a28);
  if (res[0]!=0) res[0][99]=a28;
  a28=(a5*a20);
  a16=(a9*a16);
  a28=(a28+a16);
  a16=(a6*a14);
  a21=(a22*a21);
  a16=(a16+a21);
  a28=(a28-a16);
  a28=(a0*a28);
  if (res[0]!=0) res[0][100]=a28;
  a20=(a7*a20);
  a19=(a9*a19);
  a20=(a20+a19);
  a14=(a8*a14);
  a17=(a22*a17);
  a14=(a14+a17);
  a20=(a20-a14);
  a20=(a0*a20);
  if (res[0]!=0) res[0][101]=a20;
  a20=arg[3] ? arg[3][105] : 0;
  if (res[0]!=0) res[0][102]=a20;
  a20=arg[3] ? arg[3][106] : 0;
  if (res[0]!=0) res[0][103]=a20;
  a20=arg[3] ? arg[3][107] : 0;
  if (res[0]!=0) res[0][104]=a20;
  a20=arg[4] ? arg[4][24] : 0;
  if (res[0]!=0) res[0][105]=a20;
  a20=arg[4] ? arg[4][25] : 0;
  if (res[0]!=0) res[0][106]=a20;
  a20=arg[4] ? arg[4][26] : 0;
  if (res[0]!=0) res[0][107]=a20;
  a20=arg[3] ? arg[3][111] : 0;
  if (res[0]!=0) res[0][108]=a20;
  a20=arg[3] ? arg[3][112] : 0;
  if (res[0]!=0) res[0][109]=a20;
  a20=arg[3] ? arg[3][113] : 0;
  if (res[0]!=0) res[0][110]=a20;
  a20=arg[3] ? arg[3][114] : 0;
  a14=arg[3] ? arg[3][108] : 0;
  a20=(a20-a14);
  a17=(a11*a20);
  a19=arg[3] ? arg[3][115] : 0;
  a28=arg[3] ? arg[3][109] : 0;
  a19=(a19-a28);
  a16=(a15*a19);
  a17=(a17+a16);
  a16=arg[3] ? arg[3][116] : 0;
  a21=arg[3] ? arg[3][110] : 0;
  a16=(a16-a21);
  a13=(a18*a16);
  a17=(a17+a13);
  a17=(a17/a4);
  a17=(a10*a17);
  a13=(a1*a17);
  a20=(a9*a20);
  a13=(a13+a20);
  a20=(a24*a14);
  a25=(a26*a28);
  a20=(a20+a25);
  a25=(a27*a21);
  a20=(a20+a25);
  a20=(a20/a12);
  a20=(a23*a20);
  a25=(a2*a20);
  a14=(a22*a14);
  a25=(a25+a14);
  a13=(a13-a25);
  a13=(a0*a13);
  if (res[0]!=0) res[0][111]=a13;
  a13=(a5*a17);
  a19=(a9*a19);
  a13=(a13+a19);
  a19=(a6*a20);
  a28=(a22*a28);
  a19=(a19+a28);
  a13=(a13-a19);
  a13=(a0*a13);
  if (res[0]!=0) res[0][112]=a13;
  a17=(a7*a17);
  a16=(a9*a16);
  a17=(a17+a16);
  a20=(a8*a20);
  a21=(a22*a21);
  a20=(a20+a21);
  a17=(a17-a20);
  a17=(a0*a17);
  if (res[0]!=0) res[0][113]=a17;
  a17=arg[3] ? arg[3][117] : 0;
  if (res[0]!=0) res[0][114]=a17;
  a17=arg[3] ? arg[3][118] : 0;
  if (res[0]!=0) res[0][115]=a17;
  a17=arg[3] ? arg[3][119] : 0;
  if (res[0]!=0) res[0][116]=a17;
  a17=arg[4] ? arg[4][27] : 0;
  if (res[0]!=0) res[0][117]=a17;
  a17=arg[4] ? arg[4][28] : 0;
  if (res[0]!=0) res[0][118]=a17;
  a17=arg[4] ? arg[4][29] : 0;
  if (res[0]!=0) res[0][119]=a17;
  a17=arg[3] ? arg[3][123] : 0;
  if (res[0]!=0) res[0][120]=a17;
  a17=arg[3] ? arg[3][124] : 0;
  if (res[0]!=0) res[0][121]=a17;
  a17=arg[3] ? arg[3][125] : 0;
  if (res[0]!=0) res[0][122]=a17;
  a17=arg[3] ? arg[3][126] : 0;
  a20=arg[3] ? arg[3][120] : 0;
  a17=(a17-a20);
  a21=(a11*a17);
  a16=arg[3] ? arg[3][127] : 0;
  a13=arg[3] ? arg[3][121] : 0;
  a16=(a16-a13);
  a19=(a15*a16);
  a21=(a21+a19);
  a19=arg[3] ? arg[3][128] : 0;
  a28=arg[3] ? arg[3][122] : 0;
  a19=(a19-a28);
  a25=(a18*a19);
  a21=(a21+a25);
  a21=(a21/a4);
  a21=(a10*a21);
  a25=(a1*a21);
  a17=(a9*a17);
  a25=(a25+a17);
  a17=(a24*a20);
  a14=(a26*a13);
  a17=(a17+a14);
  a14=(a27*a28);
  a17=(a17+a14);
  a17=(a17/a12);
  a17=(a23*a17);
  a14=(a2*a17);
  a20=(a22*a20);
  a14=(a14+a20);
  a25=(a25-a14);
  a25=(a0*a25);
  if (res[0]!=0) res[0][123]=a25;
  a25=(a5*a21);
  a16=(a9*a16);
  a25=(a25+a16);
  a16=(a6*a17);
  a13=(a22*a13);
  a16=(a16+a13);
  a25=(a25-a16);
  a25=(a0*a25);
  if (res[0]!=0) res[0][124]=a25;
  a21=(a7*a21);
  a19=(a9*a19);
  a21=(a21+a19);
  a17=(a8*a17);
  a28=(a22*a28);
  a17=(a17+a28);
  a21=(a21-a17);
  a21=(a0*a21);
  if (res[0]!=0) res[0][125]=a21;
  a21=arg[3] ? arg[3][129] : 0;
  if (res[0]!=0) res[0][126]=a21;
  a21=arg[3] ? arg[3][130] : 0;
  if (res[0]!=0) res[0][127]=a21;
  a21=arg[3] ? arg[3][131] : 0;
  if (res[0]!=0) res[0][128]=a21;
  a21=arg[4] ? arg[4][30] : 0;
  if (res[0]!=0) res[0][129]=a21;
  a21=arg[4] ? arg[4][31] : 0;
  if (res[0]!=0) res[0][130]=a21;
  a21=arg[4] ? arg[4][32] : 0;
  if (res[0]!=0) res[0][131]=a21;
  a21=arg[3] ? arg[3][135] : 0;
  if (res[0]!=0) res[0][132]=a21;
  a21=arg[3] ? arg[3][136] : 0;
  if (res[0]!=0) res[0][133]=a21;
  a21=arg[3] ? arg[3][137] : 0;
  if (res[0]!=0) res[0][134]=a21;
  a21=arg[3] ? arg[3][138] : 0;
  a17=arg[3] ? arg[3][132] : 0;
  a21=(a21-a17);
  a28=(a11*a21);
  a19=arg[3] ? arg[3][139] : 0;
  a25=arg[3] ? arg[3][133] : 0;
  a19=(a19-a25);
  a16=(a15*a19);
  a28=(a28+a16);
  a16=arg[3] ? arg[3][140] : 0;
  a13=arg[3] ? arg[3][134] : 0;
  a16=(a16-a13);
  a14=(a18*a16);
  a28=(a28+a14);
  a28=(a28/a4);
  a28=(a10*a28);
  a14=(a1*a28);
  a21=(a9*a21);
  a14=(a14+a21);
  a21=(a24*a17);
  a20=(a26*a25);
  a21=(a21+a20);
  a20=(a27*a13);
  a21=(a21+a20);
  a21=(a21/a12);
  a21=(a23*a21);
  a20=(a2*a21);
  a17=(a22*a17);
  a20=(a20+a17);
  a14=(a14-a20);
  a14=(a0*a14);
  if (res[0]!=0) res[0][135]=a14;
  a14=(a5*a28);
  a19=(a9*a19);
  a14=(a14+a19);
  a19=(a6*a21);
  a25=(a22*a25);
  a19=(a19+a25);
  a14=(a14-a19);
  a14=(a0*a14);
  if (res[0]!=0) res[0][136]=a14;
  a28=(a7*a28);
  a16=(a9*a16);
  a28=(a28+a16);
  a21=(a8*a21);
  a13=(a22*a13);
  a21=(a21+a13);
  a28=(a28-a21);
  a28=(a0*a28);
  if (res[0]!=0) res[0][137]=a28;
  a28=arg[3] ? arg[3][141] : 0;
  if (res[0]!=0) res[0][138]=a28;
  a28=arg[3] ? arg[3][142] : 0;
  if (res[0]!=0) res[0][139]=a28;
  a28=arg[3] ? arg[3][143] : 0;
  if (res[0]!=0) res[0][140]=a28;
  a28=arg[4] ? arg[4][33] : 0;
  if (res[0]!=0) res[0][141]=a28;
  a28=arg[4] ? arg[4][34] : 0;
  if (res[0]!=0) res[0][142]=a28;
  a28=arg[4] ? arg[4][35] : 0;
  if (res[0]!=0) res[0][143]=a28;
  a28=arg[3] ? arg[3][147] : 0;
  if (res[0]!=0) res[0][144]=a28;
  a28=arg[3] ? arg[3][148] : 0;
  if (res[0]!=0) res[0][145]=a28;
  a28=arg[3] ? arg[3][149] : 0;
  if (res[0]!=0) res[0][146]=a28;
  a28=arg[3] ? arg[3][150] : 0;
  a21=arg[3] ? arg[3][144] : 0;
  a28=(a28-a21);
  a13=(a11*a28);
  a16=arg[3] ? arg[3][151] : 0;
  a14=arg[3] ? arg[3][145] : 0;
  a16=(a16-a14);
  a19=(a15*a16);
  a13=(a13+a19);
  a19=arg[3] ? arg[3][152] : 0;
  a25=arg[3] ? arg[3][146] : 0;
  a19=(a19-a25);
  a20=(a18*a19);
  a13=(a13+a20);
  a13=(a13/a4);
  a13=(a10*a13);
  a20=(a1*a13);
  a28=(a9*a28);
  a20=(a20+a28);
  a28=(a24*a21);
  a17=(a26*a14);
  a28=(a28+a17);
  a17=(a27*a25);
  a28=(a28+a17);
  a28=(a28/a12);
  a28=(a23*a28);
  a17=(a2*a28);
  a21=(a22*a21);
  a17=(a17+a21);
  a20=(a20-a17);
  a20=(a0*a20);
  if (res[0]!=0) res[0][147]=a20;
  a20=(a5*a13);
  a16=(a9*a16);
  a20=(a20+a16);
  a16=(a6*a28);
  a14=(a22*a14);
  a16=(a16+a14);
  a20=(a20-a16);
  a20=(a0*a20);
  if (res[0]!=0) res[0][148]=a20;
  a13=(a7*a13);
  a19=(a9*a19);
  a13=(a13+a19);
  a28=(a8*a28);
  a25=(a22*a25);
  a28=(a28+a25);
  a13=(a13-a28);
  a13=(a0*a13);
  if (res[0]!=0) res[0][149]=a13;
  a13=arg[3] ? arg[3][153] : 0;
  if (res[0]!=0) res[0][150]=a13;
  a13=arg[3] ? arg[3][154] : 0;
  if (res[0]!=0) res[0][151]=a13;
  a13=arg[3] ? arg[3][155] : 0;
  if (res[0]!=0) res[0][152]=a13;
  a13=arg[4] ? arg[4][36] : 0;
  if (res[0]!=0) res[0][153]=a13;
  a13=arg[4] ? arg[4][37] : 0;
  if (res[0]!=0) res[0][154]=a13;
  a13=arg[4] ? arg[4][38] : 0;
  if (res[0]!=0) res[0][155]=a13;
  a13=arg[3] ? arg[3][159] : 0;
  if (res[0]!=0) res[0][156]=a13;
  a13=arg[3] ? arg[3][160] : 0;
  if (res[0]!=0) res[0][157]=a13;
  a13=arg[3] ? arg[3][161] : 0;
  if (res[0]!=0) res[0][158]=a13;
  a13=arg[3] ? arg[3][162] : 0;
  a28=arg[3] ? arg[3][156] : 0;
  a13=(a13-a28);
  a25=(a11*a13);
  a19=arg[3] ? arg[3][163] : 0;
  a20=arg[3] ? arg[3][157] : 0;
  a19=(a19-a20);
  a16=(a15*a19);
  a25=(a25+a16);
  a16=arg[3] ? arg[3][164] : 0;
  a14=arg[3] ? arg[3][158] : 0;
  a16=(a16-a14);
  a17=(a18*a16);
  a25=(a25+a17);
  a25=(a25/a4);
  a25=(a10*a25);
  a17=(a1*a25);
  a13=(a9*a13);
  a17=(a17+a13);
  a13=(a24*a28);
  a21=(a26*a20);
  a13=(a13+a21);
  a21=(a27*a14);
  a13=(a13+a21);
  a13=(a13/a12);
  a13=(a23*a13);
  a21=(a2*a13);
  a28=(a22*a28);
  a21=(a21+a28);
  a17=(a17-a21);
  a17=(a0*a17);
  if (res[0]!=0) res[0][159]=a17;
  a17=(a5*a25);
  a19=(a9*a19);
  a17=(a17+a19);
  a19=(a6*a13);
  a20=(a22*a20);
  a19=(a19+a20);
  a17=(a17-a19);
  a17=(a0*a17);
  if (res[0]!=0) res[0][160]=a17;
  a25=(a7*a25);
  a16=(a9*a16);
  a25=(a25+a16);
  a13=(a8*a13);
  a14=(a22*a14);
  a13=(a13+a14);
  a25=(a25-a13);
  a25=(a0*a25);
  if (res[0]!=0) res[0][161]=a25;
  a25=arg[3] ? arg[3][165] : 0;
  if (res[0]!=0) res[0][162]=a25;
  a25=arg[3] ? arg[3][166] : 0;
  if (res[0]!=0) res[0][163]=a25;
  a25=arg[3] ? arg[3][167] : 0;
  if (res[0]!=0) res[0][164]=a25;
  a25=arg[4] ? arg[4][39] : 0;
  if (res[0]!=0) res[0][165]=a25;
  a25=arg[4] ? arg[4][40] : 0;
  if (res[0]!=0) res[0][166]=a25;
  a25=arg[4] ? arg[4][41] : 0;
  if (res[0]!=0) res[0][167]=a25;
  a25=arg[3] ? arg[3][171] : 0;
  if (res[0]!=0) res[0][168]=a25;
  a25=arg[3] ? arg[3][172] : 0;
  if (res[0]!=0) res[0][169]=a25;
  a25=arg[3] ? arg[3][173] : 0;
  if (res[0]!=0) res[0][170]=a25;
  a25=arg[3] ? arg[3][174] : 0;
  a13=arg[3] ? arg[3][168] : 0;
  a25=(a25-a13);
  a11=(a11*a25);
  a14=arg[3] ? arg[3][175] : 0;
  a16=arg[3] ? arg[3][169] : 0;
  a14=(a14-a16);
  a15=(a15*a14);
  a11=(a11+a15);
  a15=arg[3] ? arg[3][176] : 0;
  a17=arg[3] ? arg[3][170] : 0;
  a15=(a15-a17);
  a18=(a18*a15);
  a11=(a11+a18);
  a11=(a11/a4);
  a10=(a10*a11);
  a1=(a1*a10);
  a25=(a9*a25);
  a1=(a1+a25);
  a24=(a24*a13);
  a26=(a26*a16);
  a24=(a24+a26);
  a27=(a27*a17);
  a24=(a24+a27);
  a24=(a24/a12);
  a23=(a23*a24);
  a2=(a2*a23);
  a13=(a22*a13);
  a2=(a2+a13);
  a1=(a1-a2);
  a1=(a0*a1);
  if (res[0]!=0) res[0][171]=a1;
  a5=(a5*a10);
  a14=(a9*a14);
  a5=(a5+a14);
  a6=(a6*a23);
  a16=(a22*a16);
  a6=(a6+a16);
  a5=(a5-a6);
  a5=(a0*a5);
  if (res[0]!=0) res[0][172]=a5;
  a7=(a7*a10);
  a9=(a9*a15);
  a7=(a7+a9);
  a8=(a8*a23);
  a22=(a22*a17);
  a8=(a8+a22);
  a7=(a7-a8);
  a0=(a0*a7);
  if (res[0]!=0) res[0][173]=a0;
  a0=arg[3] ? arg[3][177] : 0;
  if (res[0]!=0) res[0][174]=a0;
  a0=arg[3] ? arg[3][178] : 0;
  if (res[0]!=0) res[0][175]=a0;
  a0=arg[3] ? arg[3][179] : 0;
  if (res[0]!=0) res[0][176]=a0;
  a0=arg[4] ? arg[4][42] : 0;
  if (res[0]!=0) res[0][177]=a0;
  a0=arg[4] ? arg[4][43] : 0;
  if (res[0]!=0) res[0][178]=a0;
  a0=arg[4] ? arg[4][44] : 0;
  if (res[0]!=0) res[0][179]=a0;
  return 0;
}

/* casadi_erk4_chain_nm3:(x0[12],p[3])->(xf[12],sensxu[15x12,105nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+2, *cr, *cs;
  casadi_real *w0=w+29, w1, *w2=w+42, *w3=w+45, w4, *w5=w+58, *w6=w+70, *w7=w+82, w8, *w9=w+95, w10, w11, w12, *w13=w+110, *w14=w+122, *w15=w+134, w16, *w17=w+147, w18, *w19=w+160, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, *w37=w+278, w38, w39, w40, *w50=w+461, *w51=w+464, *w52=w+509, *w53=w+689, *w54=w+701, *w55=w+713, *w56=w+725, *w57=w+737, *w58=w+749, *w59=w+761, *w60=w+773, *w61=w+785, *w62=w+797, *w63=w+809, *w64=w+821, *w65=w+833, *w66=w+845, *w67=w+857, *w68=w+869, *w69=w+881, *w70=w+893, *w71=w+905, *w72=w+917, *w73=w+929, *w74=w+941, *w75=w+953, *w76=w+965, *w77=w+977, *w78=w+989, *w79=w+1001, *w80=w+1013, *w81=w+1025, *w82=w+1037, *w83=w+1049, *w84=w+1061, *w85=w+1073, *w86=w+1085, *w87=w+1097, *w88=w+1109, *w89=w+1121, *w90=w+1133, *w91=w+1145, *w92=w+1157, *w93=w+1169, *w94=w+1181, *w95=w+1193, *w96=w+1205, *w97=w+1217, *w98=w+1229, *w99=w+1241, *w100=w+1253, *w101=w+1265, *w102=w+1277, *w103=w+1289, *w104=w+1301, *w105=w+1313, *w106=w+1325, *w107=w+1337, *w108=w+1349, *w109=w+1361, *w110=w+1373, *w111=w+1385, *w112=w+1397, *w113=w+1409, *w114=w+1421, *w115=w+1433, *w116=w+1445, *w117=w+1457, *w118=w+1465, *w119=w+1471;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 12, w0);
  /* #1: @1 = 0.0208333 */
  w1 = 2.0833333333333332e-02;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 3, w2);
  /* #3: @3 = f(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 0.0625 */
  w4 = 6.2500000000000000e-02;
  /* #5: @5 = (@4*@3) */
  for (i=0, rr=w5, cs=w3; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #6: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #7: @6 = f(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: @7 = (2.*@6) */
  for (i=0, rr=w7, cs=w6; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #9: @3 = (@3+@7) */
  for (i=0, rr=w3, cs=w7; i<12; ++i) (*rr++) += (*cs++);
  /* #10: @8 = 0.0625 */
  w8 = 6.2500000000000000e-02;
  /* #11: @6 = (@8*@6) */
  for (i=0, rr=w6, cs=w6; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #12: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #13: @7 = f(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w7;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: @9 = (2.*@7) */
  for (i=0, rr=w9, cs=w7; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #15: @3 = (@3+@9) */
  for (i=0, rr=w3, cs=w9; i<12; ++i) (*rr++) += (*cs++);
  /* #16: @10 = 0.125 */
  w10 = 1.2500000000000000e-01;
  /* #17: @7 = (@10*@7) */
  for (i=0, rr=w7, cs=w7; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #18: @7 = (@0+@7) */
  for (i=0, rr=w7, cr=w0, cs=w7; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #19: @9 = f(@7, @2) */
  arg1[0]=w7;
  arg1[1]=w2;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: @3 = (@3+@9) */
  for (i=0, rr=w3, cs=w9; i<12; ++i) (*rr++) += (*cs++);
  /* #21: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #22: @3 = (@0+@3) */
  for (i=0, rr=w3, cr=w0, cs=w3; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #23: @11 = 0.0208333 */
  w11 = 2.0833333333333332e-02;
  /* #24: @9 = f(@3, @2) */
  arg1[0]=w3;
  arg1[1]=w2;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @12 = 0.0625 */
  w12 = 6.2500000000000000e-02;
  /* #26: @13 = (@12*@9) */
  for (i=0, rr=w13, cs=w9; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #27: @13 = (@3+@13) */
  for (i=0, rr=w13, cr=w3, cs=w13; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #28: @14 = f(@13, @2) */
  arg1[0]=w13;
  arg1[1]=w2;
  res1[0]=w14;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #29: @15 = (2.*@14) */
  for (i=0, rr=w15, cs=w14; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #30: @9 = (@9+@15) */
  for (i=0, rr=w9, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #31: @16 = 0.0625 */
  w16 = 6.2500000000000000e-02;
  /* #32: @14 = (@16*@14) */
  for (i=0, rr=w14, cs=w14; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #33: @14 = (@3+@14) */
  for (i=0, rr=w14, cr=w3, cs=w14; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #34: @15 = f(@14, @2) */
  arg1[0]=w14;
  arg1[1]=w2;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #35: @17 = (2.*@15) */
  for (i=0, rr=w17, cs=w15; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #36: @9 = (@9+@17) */
  for (i=0, rr=w9, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #37: @18 = 0.125 */
  w18 = 1.2500000000000000e-01;
  /* #38: @15 = (@18*@15) */
  for (i=0, rr=w15, cs=w15; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #39: @15 = (@3+@15) */
  for (i=0, rr=w15, cr=w3, cs=w15; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #40: @17 = f(@15, @2) */
  arg1[0]=w15;
  arg1[1]=w2;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #41: @9 = (@9+@17) */
  for (i=0, rr=w9, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #42: @9 = (@11*@9) */
  for (i=0, rr=w9, cs=w9; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #43: @9 = (@3+@9) */
  for (i=0, rr=w9, cr=w3, cs=w9; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #44: output[0][0] = @9 */
  casadi_copy(w9, 12, res[0]);
  /* #45: @19 = zeros(15x12,105nz) */
  casadi_fill(w19, 105, 0.);
  /* #46: @20 = zeros(12x1,0nz) */
  /* #47: @21 = zeros(12x1,0nz) */
  /* #48: @22 = zeros(12x1,0nz) */
  /* #49: @23 = zeros(12x1,0nz) */
  /* #50: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #51: {NULL, @25} = vertsplit(@24) */
  w25 = w24;
  /* #52: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #53: {NULL, @26} = vertsplit(@24) */
  w26 = w24;
  /* #54: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #55: {NULL, @27} = vertsplit(@24) */
  w27 = w24;
  /* #56: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #57: {NULL, @28} = vertsplit(@24) */
  w28 = w24;
  /* #58: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #59: {NULL, @29} = vertsplit(@24) */
  w29 = w24;
  /* #60: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #61: {NULL, @30} = vertsplit(@24) */
  w30 = w24;
  /* #62: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #63: {NULL, @31} = vertsplit(@24) */
  w31 = w24;
  /* #64: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #65: {NULL, @32} = vertsplit(@24) */
  w32 = w24;
  /* #66: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #67: {NULL, @33} = vertsplit(@24) */
  w33 = w24;
  /* #68: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #69: {NULL, @34} = vertsplit(@24) */
  w34 = w24;
  /* #70: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #71: {NULL, @35} = vertsplit(@24) */
  w35 = w24;
  /* #72: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #73: {NULL, @36} = vertsplit(@24) */
  w36 = w24;
  /* #74: @9 = horzcat(@21, @22, @23, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36) */
  rr=w9;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  /* #75: @37 = dense(@9) */
  casadi_project(w9, casadi_s1, w37, casadi_s0, w);
  /* #76: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #77: {@38, NULL} = vertsplit(@24) */
  w38 = w24;
  /* #78: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #79: {@39, NULL} = vertsplit(@24) */
  w39 = w24;
  /* #80: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #81: {@40, NULL} = vertsplit(@24) */
  w40 = w24;
  /* #82: @21 = zeros(3x1,0nz) */
  /* #83: @22 = zeros(3x1,0nz) */
  /* #84: @23 = zeros(3x1,0nz) */
  /* #85: @41 = zeros(3x1,0nz) */
  /* #86: @42 = zeros(3x1,0nz) */
  /* #87: @43 = zeros(3x1,0nz) */
  /* #88: @44 = zeros(3x1,0nz) */
  /* #89: @45 = zeros(3x1,0nz) */
  /* #90: @46 = zeros(3x1,0nz) */
  /* #91: @47 = zeros(3x1,0nz) */
  /* #92: @48 = zeros(3x1,0nz) */
  /* #93: @49 = zeros(3x1,0nz) */
  /* #94: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #95: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #96: @52 = fwd15_f(@0, @2, @20, @37, @51) */
  arg1[0]=w0;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w37;
  arg1[4]=w51;
  res1[0]=w52;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #97: {@0, @9, @17, @53, @54, @55, @56, @57, @58, @59, @60, @61, @62, @63, @64} = horzsplit(@52) */
  casadi_copy(w52, 12, w0);
  casadi_copy(w52+12, 12, w9);
  casadi_copy(w52+24, 12, w17);
  casadi_copy(w52+36, 12, w53);
  casadi_copy(w52+48, 12, w54);
  casadi_copy(w52+60, 12, w55);
  casadi_copy(w52+72, 12, w56);
  casadi_copy(w52+84, 12, w57);
  casadi_copy(w52+96, 12, w58);
  casadi_copy(w52+108, 12, w59);
  casadi_copy(w52+120, 12, w60);
  casadi_copy(w52+132, 12, w61);
  casadi_copy(w52+144, 12, w62);
  casadi_copy(w52+156, 12, w63);
  casadi_copy(w52+168, 12, w64);
  /* #98: @20 = zeros(12x1,0nz) */
  /* #99: @65 = (@4*@0) */
  for (i=0, rr=w65, cs=w0; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #100: @66 = (@4*@9) */
  for (i=0, rr=w66, cs=w9; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #101: @67 = (@4*@17) */
  for (i=0, rr=w67, cs=w17; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #102: @68 = dense(@25) */
  casadi_project((&w25), casadi_s5, w68, casadi_s4, w);
  /* #103: @69 = (@4*@53) */
  for (i=0, rr=w69, cs=w53; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #104: @68 = (@68+@69) */
  for (i=0, rr=w68, cs=w69; i<12; ++i) (*rr++) += (*cs++);
  /* #105: @69 = dense(@26) */
  casadi_project((&w26), casadi_s6, w69, casadi_s4, w);
  /* #106: @70 = (@4*@54) */
  for (i=0, rr=w70, cs=w54; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #107: @69 = (@69+@70) */
  for (i=0, rr=w69, cs=w70; i<12; ++i) (*rr++) += (*cs++);
  /* #108: @70 = dense(@27) */
  casadi_project((&w27), casadi_s7, w70, casadi_s4, w);
  /* #109: @71 = (@4*@55) */
  for (i=0, rr=w71, cs=w55; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #110: @70 = (@70+@71) */
  for (i=0, rr=w70, cs=w71; i<12; ++i) (*rr++) += (*cs++);
  /* #111: @71 = dense(@28) */
  casadi_project((&w28), casadi_s8, w71, casadi_s4, w);
  /* #112: @72 = (@4*@56) */
  for (i=0, rr=w72, cs=w56; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #113: @71 = (@71+@72) */
  for (i=0, rr=w71, cs=w72; i<12; ++i) (*rr++) += (*cs++);
  /* #114: @72 = dense(@29) */
  casadi_project((&w29), casadi_s9, w72, casadi_s4, w);
  /* #115: @73 = (@4*@57) */
  for (i=0, rr=w73, cs=w57; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #116: @72 = (@72+@73) */
  for (i=0, rr=w72, cs=w73; i<12; ++i) (*rr++) += (*cs++);
  /* #117: @73 = dense(@30) */
  casadi_project((&w30), casadi_s10, w73, casadi_s4, w);
  /* #118: @74 = (@4*@58) */
  for (i=0, rr=w74, cs=w58; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #119: @73 = (@73+@74) */
  for (i=0, rr=w73, cs=w74; i<12; ++i) (*rr++) += (*cs++);
  /* #120: @74 = dense(@31) */
  casadi_project((&w31), casadi_s11, w74, casadi_s4, w);
  /* #121: @75 = (@4*@59) */
  for (i=0, rr=w75, cs=w59; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #122: @74 = (@74+@75) */
  for (i=0, rr=w74, cs=w75; i<12; ++i) (*rr++) += (*cs++);
  /* #123: @75 = dense(@32) */
  casadi_project((&w32), casadi_s12, w75, casadi_s4, w);
  /* #124: @76 = (@4*@60) */
  for (i=0, rr=w76, cs=w60; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #125: @75 = (@75+@76) */
  for (i=0, rr=w75, cs=w76; i<12; ++i) (*rr++) += (*cs++);
  /* #126: @76 = dense(@33) */
  casadi_project((&w33), casadi_s13, w76, casadi_s4, w);
  /* #127: @77 = (@4*@61) */
  for (i=0, rr=w77, cs=w61; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #128: @76 = (@76+@77) */
  for (i=0, rr=w76, cs=w77; i<12; ++i) (*rr++) += (*cs++);
  /* #129: @77 = dense(@34) */
  casadi_project((&w34), casadi_s14, w77, casadi_s4, w);
  /* #130: @78 = (@4*@62) */
  for (i=0, rr=w78, cs=w62; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #131: @77 = (@77+@78) */
  for (i=0, rr=w77, cs=w78; i<12; ++i) (*rr++) += (*cs++);
  /* #132: @78 = dense(@35) */
  casadi_project((&w35), casadi_s15, w78, casadi_s4, w);
  /* #133: @79 = (@4*@63) */
  for (i=0, rr=w79, cs=w63; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #134: @78 = (@78+@79) */
  for (i=0, rr=w78, cs=w79; i<12; ++i) (*rr++) += (*cs++);
  /* #135: @79 = dense(@36) */
  casadi_project((&w36), casadi_s16, w79, casadi_s4, w);
  /* #136: @80 = (@4*@64) */
  for (i=0, rr=w80, cs=w64; i<12; ++i) (*rr++)  = (w4*(*cs++));
  /* #137: @79 = (@79+@80) */
  for (i=0, rr=w79, cs=w80; i<12; ++i) (*rr++) += (*cs++);
  /* #138: @52 = horzcat(@65, @66, @67, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79) */
  rr=w52;
  for (i=0, cs=w65; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w66; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w69; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w72; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w75; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w76; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w77; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w78; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w79; i<12; ++i) *rr++ = *cs++;
  /* #139: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #140: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #141: @37 = fwd15_f(@5, @2, @20, @52, @51) */
  arg1[0]=w5;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w52;
  arg1[4]=w51;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #142: {@5, @65, @66, @67, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78} = horzsplit(@37) */
  casadi_copy(w37, 12, w5);
  casadi_copy(w37+12, 12, w65);
  casadi_copy(w37+24, 12, w66);
  casadi_copy(w37+36, 12, w67);
  casadi_copy(w37+48, 12, w68);
  casadi_copy(w37+60, 12, w69);
  casadi_copy(w37+72, 12, w70);
  casadi_copy(w37+84, 12, w71);
  casadi_copy(w37+96, 12, w72);
  casadi_copy(w37+108, 12, w73);
  casadi_copy(w37+120, 12, w74);
  casadi_copy(w37+132, 12, w75);
  casadi_copy(w37+144, 12, w76);
  casadi_copy(w37+156, 12, w77);
  casadi_copy(w37+168, 12, w78);
  /* #143: @79 = (2.*@5) */
  for (i=0, rr=w79, cs=w5; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #144: @0 = (@0+@79) */
  for (i=0, rr=w0, cs=w79; i<12; ++i) (*rr++) += (*cs++);
  /* #145: @20 = zeros(12x1,0nz) */
  /* #146: @5 = (@8*@5) */
  for (i=0, rr=w5, cs=w5; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #147: @79 = (@8*@65) */
  for (i=0, rr=w79, cs=w65; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #148: @80 = (@8*@66) */
  for (i=0, rr=w80, cs=w66; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #149: @81 = dense(@25) */
  casadi_project((&w25), casadi_s5, w81, casadi_s4, w);
  /* #150: @82 = (@8*@67) */
  for (i=0, rr=w82, cs=w67; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #151: @81 = (@81+@82) */
  for (i=0, rr=w81, cs=w82; i<12; ++i) (*rr++) += (*cs++);
  /* #152: @82 = dense(@26) */
  casadi_project((&w26), casadi_s6, w82, casadi_s4, w);
  /* #153: @83 = (@8*@68) */
  for (i=0, rr=w83, cs=w68; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #154: @82 = (@82+@83) */
  for (i=0, rr=w82, cs=w83; i<12; ++i) (*rr++) += (*cs++);
  /* #155: @83 = dense(@27) */
  casadi_project((&w27), casadi_s7, w83, casadi_s4, w);
  /* #156: @84 = (@8*@69) */
  for (i=0, rr=w84, cs=w69; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #157: @83 = (@83+@84) */
  for (i=0, rr=w83, cs=w84; i<12; ++i) (*rr++) += (*cs++);
  /* #158: @84 = dense(@28) */
  casadi_project((&w28), casadi_s8, w84, casadi_s4, w);
  /* #159: @85 = (@8*@70) */
  for (i=0, rr=w85, cs=w70; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #160: @84 = (@84+@85) */
  for (i=0, rr=w84, cs=w85; i<12; ++i) (*rr++) += (*cs++);
  /* #161: @85 = dense(@29) */
  casadi_project((&w29), casadi_s9, w85, casadi_s4, w);
  /* #162: @86 = (@8*@71) */
  for (i=0, rr=w86, cs=w71; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #163: @85 = (@85+@86) */
  for (i=0, rr=w85, cs=w86; i<12; ++i) (*rr++) += (*cs++);
  /* #164: @86 = dense(@30) */
  casadi_project((&w30), casadi_s10, w86, casadi_s4, w);
  /* #165: @87 = (@8*@72) */
  for (i=0, rr=w87, cs=w72; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #166: @86 = (@86+@87) */
  for (i=0, rr=w86, cs=w87; i<12; ++i) (*rr++) += (*cs++);
  /* #167: @87 = dense(@31) */
  casadi_project((&w31), casadi_s11, w87, casadi_s4, w);
  /* #168: @88 = (@8*@73) */
  for (i=0, rr=w88, cs=w73; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #169: @87 = (@87+@88) */
  for (i=0, rr=w87, cs=w88; i<12; ++i) (*rr++) += (*cs++);
  /* #170: @88 = dense(@32) */
  casadi_project((&w32), casadi_s12, w88, casadi_s4, w);
  /* #171: @89 = (@8*@74) */
  for (i=0, rr=w89, cs=w74; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #172: @88 = (@88+@89) */
  for (i=0, rr=w88, cs=w89; i<12; ++i) (*rr++) += (*cs++);
  /* #173: @89 = dense(@33) */
  casadi_project((&w33), casadi_s13, w89, casadi_s4, w);
  /* #174: @90 = (@8*@75) */
  for (i=0, rr=w90, cs=w75; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #175: @89 = (@89+@90) */
  for (i=0, rr=w89, cs=w90; i<12; ++i) (*rr++) += (*cs++);
  /* #176: @90 = dense(@34) */
  casadi_project((&w34), casadi_s14, w90, casadi_s4, w);
  /* #177: @91 = (@8*@76) */
  for (i=0, rr=w91, cs=w76; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #178: @90 = (@90+@91) */
  for (i=0, rr=w90, cs=w91; i<12; ++i) (*rr++) += (*cs++);
  /* #179: @91 = dense(@35) */
  casadi_project((&w35), casadi_s15, w91, casadi_s4, w);
  /* #180: @92 = (@8*@77) */
  for (i=0, rr=w92, cs=w77; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #181: @91 = (@91+@92) */
  for (i=0, rr=w91, cs=w92; i<12; ++i) (*rr++) += (*cs++);
  /* #182: @92 = dense(@36) */
  casadi_project((&w36), casadi_s16, w92, casadi_s4, w);
  /* #183: @93 = (@8*@78) */
  for (i=0, rr=w93, cs=w78; i<12; ++i) (*rr++)  = (w8*(*cs++));
  /* #184: @92 = (@92+@93) */
  for (i=0, rr=w92, cs=w93; i<12; ++i) (*rr++) += (*cs++);
  /* #185: @37 = horzcat(@5, @79, @80, @81, @82, @83, @84, @85, @86, @87, @88, @89, @90, @91, @92) */
  rr=w37;
  for (i=0, cs=w5; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w79; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w80; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w81; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w82; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w84; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w85; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w86; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w87; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w88; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w89; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w90; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w91; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w92; i<12; ++i) *rr++ = *cs++;
  /* #186: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #187: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #188: @52 = fwd15_f(@6, @2, @20, @37, @51) */
  arg1[0]=w6;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w37;
  arg1[4]=w51;
  res1[0]=w52;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #189: {@6, @5, @79, @80, @81, @82, @83, @84, @85, @86, @87, @88, @89, @90, @91} = horzsplit(@52) */
  casadi_copy(w52, 12, w6);
  casadi_copy(w52+12, 12, w5);
  casadi_copy(w52+24, 12, w79);
  casadi_copy(w52+36, 12, w80);
  casadi_copy(w52+48, 12, w81);
  casadi_copy(w52+60, 12, w82);
  casadi_copy(w52+72, 12, w83);
  casadi_copy(w52+84, 12, w84);
  casadi_copy(w52+96, 12, w85);
  casadi_copy(w52+108, 12, w86);
  casadi_copy(w52+120, 12, w87);
  casadi_copy(w52+132, 12, w88);
  casadi_copy(w52+144, 12, w89);
  casadi_copy(w52+156, 12, w90);
  casadi_copy(w52+168, 12, w91);
  /* #190: @92 = (2.*@6) */
  for (i=0, rr=w92, cs=w6; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #191: @0 = (@0+@92) */
  for (i=0, rr=w0, cs=w92; i<12; ++i) (*rr++) += (*cs++);
  /* #192: @20 = zeros(12x1,0nz) */
  /* #193: @6 = (@10*@6) */
  for (i=0, rr=w6, cs=w6; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #194: @92 = (@10*@5) */
  for (i=0, rr=w92, cs=w5; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #195: @93 = (@10*@79) */
  for (i=0, rr=w93, cs=w79; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #196: @94 = dense(@25) */
  casadi_project((&w25), casadi_s5, w94, casadi_s4, w);
  /* #197: @95 = (@10*@80) */
  for (i=0, rr=w95, cs=w80; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #198: @94 = (@94+@95) */
  for (i=0, rr=w94, cs=w95; i<12; ++i) (*rr++) += (*cs++);
  /* #199: @95 = dense(@26) */
  casadi_project((&w26), casadi_s6, w95, casadi_s4, w);
  /* #200: @96 = (@10*@81) */
  for (i=0, rr=w96, cs=w81; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #201: @95 = (@95+@96) */
  for (i=0, rr=w95, cs=w96; i<12; ++i) (*rr++) += (*cs++);
  /* #202: @96 = dense(@27) */
  casadi_project((&w27), casadi_s7, w96, casadi_s4, w);
  /* #203: @97 = (@10*@82) */
  for (i=0, rr=w97, cs=w82; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #204: @96 = (@96+@97) */
  for (i=0, rr=w96, cs=w97; i<12; ++i) (*rr++) += (*cs++);
  /* #205: @97 = dense(@28) */
  casadi_project((&w28), casadi_s8, w97, casadi_s4, w);
  /* #206: @98 = (@10*@83) */
  for (i=0, rr=w98, cs=w83; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #207: @97 = (@97+@98) */
  for (i=0, rr=w97, cs=w98; i<12; ++i) (*rr++) += (*cs++);
  /* #208: @98 = dense(@29) */
  casadi_project((&w29), casadi_s9, w98, casadi_s4, w);
  /* #209: @99 = (@10*@84) */
  for (i=0, rr=w99, cs=w84; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #210: @98 = (@98+@99) */
  for (i=0, rr=w98, cs=w99; i<12; ++i) (*rr++) += (*cs++);
  /* #211: @99 = dense(@30) */
  casadi_project((&w30), casadi_s10, w99, casadi_s4, w);
  /* #212: @100 = (@10*@85) */
  for (i=0, rr=w100, cs=w85; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #213: @99 = (@99+@100) */
  for (i=0, rr=w99, cs=w100; i<12; ++i) (*rr++) += (*cs++);
  /* #214: @100 = dense(@31) */
  casadi_project((&w31), casadi_s11, w100, casadi_s4, w);
  /* #215: @101 = (@10*@86) */
  for (i=0, rr=w101, cs=w86; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #216: @100 = (@100+@101) */
  for (i=0, rr=w100, cs=w101; i<12; ++i) (*rr++) += (*cs++);
  /* #217: @101 = dense(@32) */
  casadi_project((&w32), casadi_s12, w101, casadi_s4, w);
  /* #218: @102 = (@10*@87) */
  for (i=0, rr=w102, cs=w87; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #219: @101 = (@101+@102) */
  for (i=0, rr=w101, cs=w102; i<12; ++i) (*rr++) += (*cs++);
  /* #220: @102 = dense(@33) */
  casadi_project((&w33), casadi_s13, w102, casadi_s4, w);
  /* #221: @103 = (@10*@88) */
  for (i=0, rr=w103, cs=w88; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #222: @102 = (@102+@103) */
  for (i=0, rr=w102, cs=w103; i<12; ++i) (*rr++) += (*cs++);
  /* #223: @103 = dense(@34) */
  casadi_project((&w34), casadi_s14, w103, casadi_s4, w);
  /* #224: @104 = (@10*@89) */
  for (i=0, rr=w104, cs=w89; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #225: @103 = (@103+@104) */
  for (i=0, rr=w103, cs=w104; i<12; ++i) (*rr++) += (*cs++);
  /* #226: @104 = dense(@35) */
  casadi_project((&w35), casadi_s15, w104, casadi_s4, w);
  /* #227: @105 = (@10*@90) */
  for (i=0, rr=w105, cs=w90; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #228: @104 = (@104+@105) */
  for (i=0, rr=w104, cs=w105; i<12; ++i) (*rr++) += (*cs++);
  /* #229: @105 = dense(@36) */
  casadi_project((&w36), casadi_s16, w105, casadi_s4, w);
  /* #230: @106 = (@10*@91) */
  for (i=0, rr=w106, cs=w91; i<12; ++i) (*rr++)  = (w10*(*cs++));
  /* #231: @105 = (@105+@106) */
  for (i=0, rr=w105, cs=w106; i<12; ++i) (*rr++) += (*cs++);
  /* #232: @52 = horzcat(@6, @92, @93, @94, @95, @96, @97, @98, @99, @100, @101, @102, @103, @104, @105) */
  rr=w52;
  for (i=0, cs=w6; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w92; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w93; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w94; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w95; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w101; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w102; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w103; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w104; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w105; i<12; ++i) *rr++ = *cs++;
  /* #233: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #234: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #235: @37 = fwd15_f(@7, @2, @20, @52, @51) */
  arg1[0]=w7;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w52;
  arg1[4]=w51;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #236: {@7, @6, @92, @93, @94, @95, @96, @97, @98, @99, @100, @101, @102, @103, @104} = horzsplit(@37) */
  casadi_copy(w37, 12, w7);
  casadi_copy(w37+12, 12, w6);
  casadi_copy(w37+24, 12, w92);
  casadi_copy(w37+36, 12, w93);
  casadi_copy(w37+48, 12, w94);
  casadi_copy(w37+60, 12, w95);
  casadi_copy(w37+72, 12, w96);
  casadi_copy(w37+84, 12, w97);
  casadi_copy(w37+96, 12, w98);
  casadi_copy(w37+108, 12, w99);
  casadi_copy(w37+120, 12, w100);
  casadi_copy(w37+132, 12, w101);
  casadi_copy(w37+144, 12, w102);
  casadi_copy(w37+156, 12, w103);
  casadi_copy(w37+168, 12, w104);
  /* #237: @0 = (@0+@7) */
  for (i=0, rr=w0, cs=w7; i<12; ++i) (*rr++) += (*cs++);
  /* #238: @0 = (@1*@0) */
  for (i=0, rr=w0, cs=w0; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #239: @20 = zeros(12x1,0nz) */
  /* #240: @65 = (2.*@65) */
  for (i=0, rr=w65, cs=w65; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #241: @9 = (@9+@65) */
  for (i=0, rr=w9, cs=w65; i<12; ++i) (*rr++) += (*cs++);
  /* #242: @5 = (2.*@5) */
  for (i=0, rr=w5, cs=w5; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #243: @9 = (@9+@5) */
  for (i=0, rr=w9, cs=w5; i<12; ++i) (*rr++) += (*cs++);
  /* #244: @9 = (@9+@6) */
  for (i=0, rr=w9, cs=w6; i<12; ++i) (*rr++) += (*cs++);
  /* #245: @9 = (@1*@9) */
  for (i=0, rr=w9, cs=w9; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #246: @66 = (2.*@66) */
  for (i=0, rr=w66, cs=w66; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #247: @17 = (@17+@66) */
  for (i=0, rr=w17, cs=w66; i<12; ++i) (*rr++) += (*cs++);
  /* #248: @79 = (2.*@79) */
  for (i=0, rr=w79, cs=w79; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #249: @17 = (@17+@79) */
  for (i=0, rr=w17, cs=w79; i<12; ++i) (*rr++) += (*cs++);
  /* #250: @17 = (@17+@92) */
  for (i=0, rr=w17, cs=w92; i<12; ++i) (*rr++) += (*cs++);
  /* #251: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #252: @92 = dense(@25) */
  casadi_project((&w25), casadi_s5, w92, casadi_s4, w);
  /* #253: @67 = (2.*@67) */
  for (i=0, rr=w67, cs=w67; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #254: @53 = (@53+@67) */
  for (i=0, rr=w53, cs=w67; i<12; ++i) (*rr++) += (*cs++);
  /* #255: @80 = (2.*@80) */
  for (i=0, rr=w80, cs=w80; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #256: @53 = (@53+@80) */
  for (i=0, rr=w53, cs=w80; i<12; ++i) (*rr++) += (*cs++);
  /* #257: @53 = (@53+@93) */
  for (i=0, rr=w53, cs=w93; i<12; ++i) (*rr++) += (*cs++);
  /* #258: @53 = (@1*@53) */
  for (i=0, rr=w53, cs=w53; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #259: @92 = (@92+@53) */
  for (i=0, rr=w92, cs=w53; i<12; ++i) (*rr++) += (*cs++);
  /* #260: @53 = dense(@26) */
  casadi_project((&w26), casadi_s6, w53, casadi_s4, w);
  /* #261: @68 = (2.*@68) */
  for (i=0, rr=w68, cs=w68; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #262: @54 = (@54+@68) */
  for (i=0, rr=w54, cs=w68; i<12; ++i) (*rr++) += (*cs++);
  /* #263: @81 = (2.*@81) */
  for (i=0, rr=w81, cs=w81; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #264: @54 = (@54+@81) */
  for (i=0, rr=w54, cs=w81; i<12; ++i) (*rr++) += (*cs++);
  /* #265: @54 = (@54+@94) */
  for (i=0, rr=w54, cs=w94; i<12; ++i) (*rr++) += (*cs++);
  /* #266: @54 = (@1*@54) */
  for (i=0, rr=w54, cs=w54; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #267: @53 = (@53+@54) */
  for (i=0, rr=w53, cs=w54; i<12; ++i) (*rr++) += (*cs++);
  /* #268: @54 = dense(@27) */
  casadi_project((&w27), casadi_s7, w54, casadi_s4, w);
  /* #269: @69 = (2.*@69) */
  for (i=0, rr=w69, cs=w69; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #270: @55 = (@55+@69) */
  for (i=0, rr=w55, cs=w69; i<12; ++i) (*rr++) += (*cs++);
  /* #271: @82 = (2.*@82) */
  for (i=0, rr=w82, cs=w82; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #272: @55 = (@55+@82) */
  for (i=0, rr=w55, cs=w82; i<12; ++i) (*rr++) += (*cs++);
  /* #273: @55 = (@55+@95) */
  for (i=0, rr=w55, cs=w95; i<12; ++i) (*rr++) += (*cs++);
  /* #274: @55 = (@1*@55) */
  for (i=0, rr=w55, cs=w55; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #275: @54 = (@54+@55) */
  for (i=0, rr=w54, cs=w55; i<12; ++i) (*rr++) += (*cs++);
  /* #276: @55 = dense(@28) */
  casadi_project((&w28), casadi_s8, w55, casadi_s4, w);
  /* #277: @70 = (2.*@70) */
  for (i=0, rr=w70, cs=w70; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #278: @56 = (@56+@70) */
  for (i=0, rr=w56, cs=w70; i<12; ++i) (*rr++) += (*cs++);
  /* #279: @83 = (2.*@83) */
  for (i=0, rr=w83, cs=w83; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #280: @56 = (@56+@83) */
  for (i=0, rr=w56, cs=w83; i<12; ++i) (*rr++) += (*cs++);
  /* #281: @56 = (@56+@96) */
  for (i=0, rr=w56, cs=w96; i<12; ++i) (*rr++) += (*cs++);
  /* #282: @56 = (@1*@56) */
  for (i=0, rr=w56, cs=w56; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #283: @55 = (@55+@56) */
  for (i=0, rr=w55, cs=w56; i<12; ++i) (*rr++) += (*cs++);
  /* #284: @56 = dense(@29) */
  casadi_project((&w29), casadi_s9, w56, casadi_s4, w);
  /* #285: @71 = (2.*@71) */
  for (i=0, rr=w71, cs=w71; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #286: @57 = (@57+@71) */
  for (i=0, rr=w57, cs=w71; i<12; ++i) (*rr++) += (*cs++);
  /* #287: @84 = (2.*@84) */
  for (i=0, rr=w84, cs=w84; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #288: @57 = (@57+@84) */
  for (i=0, rr=w57, cs=w84; i<12; ++i) (*rr++) += (*cs++);
  /* #289: @57 = (@57+@97) */
  for (i=0, rr=w57, cs=w97; i<12; ++i) (*rr++) += (*cs++);
  /* #290: @57 = (@1*@57) */
  for (i=0, rr=w57, cs=w57; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #291: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<12; ++i) (*rr++) += (*cs++);
  /* #292: @57 = dense(@30) */
  casadi_project((&w30), casadi_s10, w57, casadi_s4, w);
  /* #293: @72 = (2.*@72) */
  for (i=0, rr=w72, cs=w72; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #294: @58 = (@58+@72) */
  for (i=0, rr=w58, cs=w72; i<12; ++i) (*rr++) += (*cs++);
  /* #295: @85 = (2.*@85) */
  for (i=0, rr=w85, cs=w85; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #296: @58 = (@58+@85) */
  for (i=0, rr=w58, cs=w85; i<12; ++i) (*rr++) += (*cs++);
  /* #297: @58 = (@58+@98) */
  for (i=0, rr=w58, cs=w98; i<12; ++i) (*rr++) += (*cs++);
  /* #298: @58 = (@1*@58) */
  for (i=0, rr=w58, cs=w58; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #299: @57 = (@57+@58) */
  for (i=0, rr=w57, cs=w58; i<12; ++i) (*rr++) += (*cs++);
  /* #300: @58 = dense(@31) */
  casadi_project((&w31), casadi_s11, w58, casadi_s4, w);
  /* #301: @73 = (2.*@73) */
  for (i=0, rr=w73, cs=w73; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #302: @59 = (@59+@73) */
  for (i=0, rr=w59, cs=w73; i<12; ++i) (*rr++) += (*cs++);
  /* #303: @86 = (2.*@86) */
  for (i=0, rr=w86, cs=w86; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #304: @59 = (@59+@86) */
  for (i=0, rr=w59, cs=w86; i<12; ++i) (*rr++) += (*cs++);
  /* #305: @59 = (@59+@99) */
  for (i=0, rr=w59, cs=w99; i<12; ++i) (*rr++) += (*cs++);
  /* #306: @59 = (@1*@59) */
  for (i=0, rr=w59, cs=w59; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #307: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<12; ++i) (*rr++) += (*cs++);
  /* #308: @59 = dense(@32) */
  casadi_project((&w32), casadi_s12, w59, casadi_s4, w);
  /* #309: @74 = (2.*@74) */
  for (i=0, rr=w74, cs=w74; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #310: @60 = (@60+@74) */
  for (i=0, rr=w60, cs=w74; i<12; ++i) (*rr++) += (*cs++);
  /* #311: @87 = (2.*@87) */
  for (i=0, rr=w87, cs=w87; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #312: @60 = (@60+@87) */
  for (i=0, rr=w60, cs=w87; i<12; ++i) (*rr++) += (*cs++);
  /* #313: @60 = (@60+@100) */
  for (i=0, rr=w60, cs=w100; i<12; ++i) (*rr++) += (*cs++);
  /* #314: @60 = (@1*@60) */
  for (i=0, rr=w60, cs=w60; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #315: @59 = (@59+@60) */
  for (i=0, rr=w59, cs=w60; i<12; ++i) (*rr++) += (*cs++);
  /* #316: @60 = dense(@33) */
  casadi_project((&w33), casadi_s13, w60, casadi_s4, w);
  /* #317: @75 = (2.*@75) */
  for (i=0, rr=w75, cs=w75; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #318: @61 = (@61+@75) */
  for (i=0, rr=w61, cs=w75; i<12; ++i) (*rr++) += (*cs++);
  /* #319: @88 = (2.*@88) */
  for (i=0, rr=w88, cs=w88; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #320: @61 = (@61+@88) */
  for (i=0, rr=w61, cs=w88; i<12; ++i) (*rr++) += (*cs++);
  /* #321: @61 = (@61+@101) */
  for (i=0, rr=w61, cs=w101; i<12; ++i) (*rr++) += (*cs++);
  /* #322: @61 = (@1*@61) */
  for (i=0, rr=w61, cs=w61; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #323: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<12; ++i) (*rr++) += (*cs++);
  /* #324: @61 = dense(@34) */
  casadi_project((&w34), casadi_s14, w61, casadi_s4, w);
  /* #325: @76 = (2.*@76) */
  for (i=0, rr=w76, cs=w76; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #326: @62 = (@62+@76) */
  for (i=0, rr=w62, cs=w76; i<12; ++i) (*rr++) += (*cs++);
  /* #327: @89 = (2.*@89) */
  for (i=0, rr=w89, cs=w89; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #328: @62 = (@62+@89) */
  for (i=0, rr=w62, cs=w89; i<12; ++i) (*rr++) += (*cs++);
  /* #329: @62 = (@62+@102) */
  for (i=0, rr=w62, cs=w102; i<12; ++i) (*rr++) += (*cs++);
  /* #330: @62 = (@1*@62) */
  for (i=0, rr=w62, cs=w62; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #331: @61 = (@61+@62) */
  for (i=0, rr=w61, cs=w62; i<12; ++i) (*rr++) += (*cs++);
  /* #332: @62 = dense(@35) */
  casadi_project((&w35), casadi_s15, w62, casadi_s4, w);
  /* #333: @77 = (2.*@77) */
  for (i=0, rr=w77, cs=w77; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #334: @63 = (@63+@77) */
  for (i=0, rr=w63, cs=w77; i<12; ++i) (*rr++) += (*cs++);
  /* #335: @90 = (2.*@90) */
  for (i=0, rr=w90, cs=w90; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #336: @63 = (@63+@90) */
  for (i=0, rr=w63, cs=w90; i<12; ++i) (*rr++) += (*cs++);
  /* #337: @63 = (@63+@103) */
  for (i=0, rr=w63, cs=w103; i<12; ++i) (*rr++) += (*cs++);
  /* #338: @63 = (@1*@63) */
  for (i=0, rr=w63, cs=w63; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #339: @62 = (@62+@63) */
  for (i=0, rr=w62, cs=w63; i<12; ++i) (*rr++) += (*cs++);
  /* #340: @63 = dense(@36) */
  casadi_project((&w36), casadi_s16, w63, casadi_s4, w);
  /* #341: @78 = (2.*@78) */
  for (i=0, rr=w78, cs=w78; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #342: @64 = (@64+@78) */
  for (i=0, rr=w64, cs=w78; i<12; ++i) (*rr++) += (*cs++);
  /* #343: @91 = (2.*@91) */
  for (i=0, rr=w91, cs=w91; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #344: @64 = (@64+@91) */
  for (i=0, rr=w64, cs=w91; i<12; ++i) (*rr++) += (*cs++);
  /* #345: @64 = (@64+@104) */
  for (i=0, rr=w64, cs=w104; i<12; ++i) (*rr++) += (*cs++);
  /* #346: @64 = (@1*@64) */
  for (i=0, rr=w64, cs=w64; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #347: @63 = (@63+@64) */
  for (i=0, rr=w63, cs=w64; i<12; ++i) (*rr++) += (*cs++);
  /* #348: @37 = horzcat(@0, @9, @17, @92, @53, @54, @55, @56, @57, @58, @59, @60, @61, @62, @63) */
  rr=w37;
  for (i=0, cs=w0; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w92; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w57; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w58; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w60; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w61; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w63; i<12; ++i) *rr++ = *cs++;
  /* #349: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #350: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #351: @52 = fwd15_f(@3, @2, @20, @37, @51) */
  arg1[0]=w3;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w37;
  arg1[4]=w51;
  res1[0]=w52;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #352: {@3, @64, @104, @91, @78, @103, @90, @77, @102, @89, @76, @101, @88, @75, @100} = horzsplit(@52) */
  casadi_copy(w52, 12, w3);
  casadi_copy(w52+12, 12, w64);
  casadi_copy(w52+24, 12, w104);
  casadi_copy(w52+36, 12, w91);
  casadi_copy(w52+48, 12, w78);
  casadi_copy(w52+60, 12, w103);
  casadi_copy(w52+72, 12, w90);
  casadi_copy(w52+84, 12, w77);
  casadi_copy(w52+96, 12, w102);
  casadi_copy(w52+108, 12, w89);
  casadi_copy(w52+120, 12, w76);
  casadi_copy(w52+132, 12, w101);
  casadi_copy(w52+144, 12, w88);
  casadi_copy(w52+156, 12, w75);
  casadi_copy(w52+168, 12, w100);
  /* #353: @20 = zeros(12x1,0nz) */
  /* #354: @87 = (@12*@3) */
  for (i=0, rr=w87, cs=w3; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #355: @87 = (@0+@87) */
  for (i=0, rr=w87, cr=w0, cs=w87; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #356: @74 = (@12*@64) */
  for (i=0, rr=w74, cs=w64; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #357: @74 = (@9+@74) */
  for (i=0, rr=w74, cr=w9, cs=w74; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #358: @99 = (@12*@104) */
  for (i=0, rr=w99, cs=w104; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #359: @99 = (@17+@99) */
  for (i=0, rr=w99, cr=w17, cs=w99; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #360: @86 = (@12*@91) */
  for (i=0, rr=w86, cs=w91; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #361: @86 = (@92+@86) */
  for (i=0, rr=w86, cr=w92, cs=w86; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #362: @73 = (@12*@78) */
  for (i=0, rr=w73, cs=w78; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #363: @73 = (@53+@73) */
  for (i=0, rr=w73, cr=w53, cs=w73; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #364: @98 = (@12*@103) */
  for (i=0, rr=w98, cs=w103; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #365: @98 = (@54+@98) */
  for (i=0, rr=w98, cr=w54, cs=w98; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #366: @85 = (@12*@90) */
  for (i=0, rr=w85, cs=w90; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #367: @85 = (@55+@85) */
  for (i=0, rr=w85, cr=w55, cs=w85; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #368: @72 = (@12*@77) */
  for (i=0, rr=w72, cs=w77; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #369: @72 = (@56+@72) */
  for (i=0, rr=w72, cr=w56, cs=w72; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #370: @97 = (@12*@102) */
  for (i=0, rr=w97, cs=w102; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #371: @97 = (@57+@97) */
  for (i=0, rr=w97, cr=w57, cs=w97; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #372: @84 = (@12*@89) */
  for (i=0, rr=w84, cs=w89; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #373: @84 = (@58+@84) */
  for (i=0, rr=w84, cr=w58, cs=w84; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #374: @71 = (@12*@76) */
  for (i=0, rr=w71, cs=w76; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #375: @71 = (@59+@71) */
  for (i=0, rr=w71, cr=w59, cs=w71; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #376: @96 = (@12*@101) */
  for (i=0, rr=w96, cs=w101; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #377: @96 = (@60+@96) */
  for (i=0, rr=w96, cr=w60, cs=w96; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #378: @83 = (@12*@88) */
  for (i=0, rr=w83, cs=w88; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #379: @83 = (@61+@83) */
  for (i=0, rr=w83, cr=w61, cs=w83; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #380: @70 = (@12*@75) */
  for (i=0, rr=w70, cs=w75; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #381: @70 = (@62+@70) */
  for (i=0, rr=w70, cr=w62, cs=w70; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #382: @95 = (@12*@100) */
  for (i=0, rr=w95, cs=w100; i<12; ++i) (*rr++)  = (w12*(*cs++));
  /* #383: @95 = (@63+@95) */
  for (i=0, rr=w95, cr=w63, cs=w95; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #384: @52 = horzcat(@87, @74, @99, @86, @73, @98, @85, @72, @97, @84, @71, @96, @83, @70, @95) */
  rr=w52;
  for (i=0, cs=w87; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w86; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w85; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w72; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w84; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w95; i<12; ++i) *rr++ = *cs++;
  /* #385: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #386: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #387: @37 = fwd15_f(@13, @2, @20, @52, @51) */
  arg1[0]=w13;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w52;
  arg1[4]=w51;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #388: {@13, @87, @74, @99, @86, @73, @98, @85, @72, @97, @84, @71, @96, @83, @70} = horzsplit(@37) */
  casadi_copy(w37, 12, w13);
  casadi_copy(w37+12, 12, w87);
  casadi_copy(w37+24, 12, w74);
  casadi_copy(w37+36, 12, w99);
  casadi_copy(w37+48, 12, w86);
  casadi_copy(w37+60, 12, w73);
  casadi_copy(w37+72, 12, w98);
  casadi_copy(w37+84, 12, w85);
  casadi_copy(w37+96, 12, w72);
  casadi_copy(w37+108, 12, w97);
  casadi_copy(w37+120, 12, w84);
  casadi_copy(w37+132, 12, w71);
  casadi_copy(w37+144, 12, w96);
  casadi_copy(w37+156, 12, w83);
  casadi_copy(w37+168, 12, w70);
  /* #389: @95 = (2.*@13) */
  for (i=0, rr=w95, cs=w13; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #390: @3 = (@3+@95) */
  for (i=0, rr=w3, cs=w95; i<12; ++i) (*rr++) += (*cs++);
  /* #391: @20 = zeros(12x1,0nz) */
  /* #392: @13 = (@16*@13) */
  for (i=0, rr=w13, cs=w13; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #393: @13 = (@0+@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #394: @95 = (@16*@87) */
  for (i=0, rr=w95, cs=w87; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #395: @95 = (@9+@95) */
  for (i=0, rr=w95, cr=w9, cs=w95; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #396: @82 = (@16*@74) */
  for (i=0, rr=w82, cs=w74; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #397: @82 = (@17+@82) */
  for (i=0, rr=w82, cr=w17, cs=w82; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #398: @69 = (@16*@99) */
  for (i=0, rr=w69, cs=w99; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #399: @69 = (@92+@69) */
  for (i=0, rr=w69, cr=w92, cs=w69; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #400: @94 = (@16*@86) */
  for (i=0, rr=w94, cs=w86; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #401: @94 = (@53+@94) */
  for (i=0, rr=w94, cr=w53, cs=w94; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #402: @81 = (@16*@73) */
  for (i=0, rr=w81, cs=w73; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #403: @81 = (@54+@81) */
  for (i=0, rr=w81, cr=w54, cs=w81; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #404: @68 = (@16*@98) */
  for (i=0, rr=w68, cs=w98; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #405: @68 = (@55+@68) */
  for (i=0, rr=w68, cr=w55, cs=w68; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #406: @93 = (@16*@85) */
  for (i=0, rr=w93, cs=w85; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #407: @93 = (@56+@93) */
  for (i=0, rr=w93, cr=w56, cs=w93; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #408: @80 = (@16*@72) */
  for (i=0, rr=w80, cs=w72; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #409: @80 = (@57+@80) */
  for (i=0, rr=w80, cr=w57, cs=w80; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #410: @67 = (@16*@97) */
  for (i=0, rr=w67, cs=w97; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #411: @67 = (@58+@67) */
  for (i=0, rr=w67, cr=w58, cs=w67; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #412: @79 = (@16*@84) */
  for (i=0, rr=w79, cs=w84; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #413: @79 = (@59+@79) */
  for (i=0, rr=w79, cr=w59, cs=w79; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #414: @66 = (@16*@71) */
  for (i=0, rr=w66, cs=w71; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #415: @66 = (@60+@66) */
  for (i=0, rr=w66, cr=w60, cs=w66; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #416: @6 = (@16*@96) */
  for (i=0, rr=w6, cs=w96; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #417: @6 = (@61+@6) */
  for (i=0, rr=w6, cr=w61, cs=w6; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #418: @5 = (@16*@83) */
  for (i=0, rr=w5, cs=w83; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #419: @5 = (@62+@5) */
  for (i=0, rr=w5, cr=w62, cs=w5; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #420: @65 = (@16*@70) */
  for (i=0, rr=w65, cs=w70; i<12; ++i) (*rr++)  = (w16*(*cs++));
  /* #421: @65 = (@63+@65) */
  for (i=0, rr=w65, cr=w63, cs=w65; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #422: @37 = horzcat(@13, @95, @82, @69, @94, @81, @68, @93, @80, @67, @79, @66, @6, @5, @65) */
  rr=w37;
  for (i=0, cs=w13; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w95; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w82; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w69; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w94; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w81; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w93; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w80; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w79; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w66; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<12; ++i) *rr++ = *cs++;
  /* #423: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #424: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #425: @52 = fwd15_f(@14, @2, @20, @37, @51) */
  arg1[0]=w14;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w37;
  arg1[4]=w51;
  res1[0]=w52;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #426: {@14, @13, @95, @82, @69, @94, @81, @68, @93, @80, @67, @79, @66, @6, @5} = horzsplit(@52) */
  casadi_copy(w52, 12, w14);
  casadi_copy(w52+12, 12, w13);
  casadi_copy(w52+24, 12, w95);
  casadi_copy(w52+36, 12, w82);
  casadi_copy(w52+48, 12, w69);
  casadi_copy(w52+60, 12, w94);
  casadi_copy(w52+72, 12, w81);
  casadi_copy(w52+84, 12, w68);
  casadi_copy(w52+96, 12, w93);
  casadi_copy(w52+108, 12, w80);
  casadi_copy(w52+120, 12, w67);
  casadi_copy(w52+132, 12, w79);
  casadi_copy(w52+144, 12, w66);
  casadi_copy(w52+156, 12, w6);
  casadi_copy(w52+168, 12, w5);
  /* #427: @65 = (2.*@14) */
  for (i=0, rr=w65, cs=w14; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #428: @3 = (@3+@65) */
  for (i=0, rr=w3, cs=w65; i<12; ++i) (*rr++) += (*cs++);
  /* #429: @20 = zeros(12x1,0nz) */
  /* #430: @14 = (@18*@14) */
  for (i=0, rr=w14, cs=w14; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #431: @14 = (@0+@14) */
  for (i=0, rr=w14, cr=w0, cs=w14; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #432: @65 = (@18*@13) */
  for (i=0, rr=w65, cs=w13; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #433: @65 = (@9+@65) */
  for (i=0, rr=w65, cr=w9, cs=w65; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #434: @7 = (@18*@95) */
  for (i=0, rr=w7, cs=w95; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #435: @7 = (@17+@7) */
  for (i=0, rr=w7, cr=w17, cs=w7; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #436: @105 = (@18*@82) */
  for (i=0, rr=w105, cs=w82; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #437: @105 = (@92+@105) */
  for (i=0, rr=w105, cr=w92, cs=w105; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #438: @106 = (@18*@69) */
  for (i=0, rr=w106, cs=w69; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #439: @106 = (@53+@106) */
  for (i=0, rr=w106, cr=w53, cs=w106; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #440: @107 = (@18*@94) */
  for (i=0, rr=w107, cs=w94; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #441: @107 = (@54+@107) */
  for (i=0, rr=w107, cr=w54, cs=w107; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #442: @108 = (@18*@81) */
  for (i=0, rr=w108, cs=w81; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #443: @108 = (@55+@108) */
  for (i=0, rr=w108, cr=w55, cs=w108; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #444: @109 = (@18*@68) */
  for (i=0, rr=w109, cs=w68; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #445: @109 = (@56+@109) */
  for (i=0, rr=w109, cr=w56, cs=w109; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #446: @110 = (@18*@93) */
  for (i=0, rr=w110, cs=w93; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #447: @110 = (@57+@110) */
  for (i=0, rr=w110, cr=w57, cs=w110; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #448: @111 = (@18*@80) */
  for (i=0, rr=w111, cs=w80; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #449: @111 = (@58+@111) */
  for (i=0, rr=w111, cr=w58, cs=w111; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #450: @112 = (@18*@67) */
  for (i=0, rr=w112, cs=w67; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #451: @112 = (@59+@112) */
  for (i=0, rr=w112, cr=w59, cs=w112; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #452: @113 = (@18*@79) */
  for (i=0, rr=w113, cs=w79; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #453: @113 = (@60+@113) */
  for (i=0, rr=w113, cr=w60, cs=w113; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #454: @114 = (@18*@66) */
  for (i=0, rr=w114, cs=w66; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #455: @114 = (@61+@114) */
  for (i=0, rr=w114, cr=w61, cs=w114; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #456: @115 = (@18*@6) */
  for (i=0, rr=w115, cs=w6; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #457: @115 = (@62+@115) */
  for (i=0, rr=w115, cr=w62, cs=w115; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #458: @116 = (@18*@5) */
  for (i=0, rr=w116, cs=w5; i<12; ++i) (*rr++)  = (w18*(*cs++));
  /* #459: @116 = (@63+@116) */
  for (i=0, rr=w116, cr=w63, cs=w116; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #460: @52 = horzcat(@14, @65, @7, @105, @106, @107, @108, @109, @110, @111, @112, @113, @114, @115, @116) */
  rr=w52;
  for (i=0, cs=w14; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w105; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w106; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w107; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w108; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w109; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w110; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w111; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w112; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w113; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w114; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w115; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w116; i<12; ++i) *rr++ = *cs++;
  /* #461: @50 = horzcat(@38, @39, @40, @21, @22, @23, @41, @42, @43, @44, @45, @46, @47, @48, @49) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #462: @51 = dense(@50) */
  casadi_project(w50, casadi_s3, w51, casadi_s2, w);
  /* #463: @37 = fwd15_f(@15, @2, @20, @52, @51) */
  arg1[0]=w15;
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=w52;
  arg1[4]=w51;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #464: {@15, @14, @65, @7, @105, @106, @107, @108, @109, @110, @111, @112, @113, @114, @115} = horzsplit(@37) */
  casadi_copy(w37, 12, w15);
  casadi_copy(w37+12, 12, w14);
  casadi_copy(w37+24, 12, w65);
  casadi_copy(w37+36, 12, w7);
  casadi_copy(w37+48, 12, w105);
  casadi_copy(w37+60, 12, w106);
  casadi_copy(w37+72, 12, w107);
  casadi_copy(w37+84, 12, w108);
  casadi_copy(w37+96, 12, w109);
  casadi_copy(w37+108, 12, w110);
  casadi_copy(w37+120, 12, w111);
  casadi_copy(w37+132, 12, w112);
  casadi_copy(w37+144, 12, w113);
  casadi_copy(w37+156, 12, w114);
  casadi_copy(w37+168, 12, w115);
  /* #465: @3 = (@3+@15) */
  for (i=0, rr=w3, cs=w15; i<12; ++i) (*rr++) += (*cs++);
  /* #466: @3 = (@11*@3) */
  for (i=0, rr=w3, cs=w3; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #467: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<12; ++i) (*rr++) += (*cs++);
  /* #468: @117 = @0[0, 1, 2, 3, 4, 5, 6, 9] */
  for (cii=casadi_s17, rr=w117, ss=w0; cii!=casadi_s17+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #469: (@19[0, 15, 30, 45, 60, 75, 90, 99] = @117) */
  for (cii=casadi_s18, rr=w19, ss=w117; cii!=casadi_s18+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #470: @87 = (2.*@87) */
  for (i=0, rr=w87, cs=w87; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #471: @64 = (@64+@87) */
  for (i=0, rr=w64, cs=w87; i<12; ++i) (*rr++) += (*cs++);
  /* #472: @13 = (2.*@13) */
  for (i=0, rr=w13, cs=w13; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #473: @64 = (@64+@13) */
  for (i=0, rr=w64, cs=w13; i<12; ++i) (*rr++) += (*cs++);
  /* #474: @64 = (@64+@14) */
  for (i=0, rr=w64, cs=w14; i<12; ++i) (*rr++) += (*cs++);
  /* #475: @64 = (@11*@64) */
  for (i=0, rr=w64, cs=w64; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #476: @9 = (@9+@64) */
  for (i=0, rr=w9, cs=w64; i<12; ++i) (*rr++) += (*cs++);
  /* #477: @117 = @9[0, 1, 2, 3, 4, 5, 7, 10] */
  for (cii=casadi_s19, rr=w117, ss=w9; cii!=casadi_s19+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #478: (@19[1, 16, 31, 46, 61, 76, 93, 101] = @117) */
  for (cii=casadi_s20, rr=w19, ss=w117; cii!=casadi_s20+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #479: @74 = (2.*@74) */
  for (i=0, rr=w74, cs=w74; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #480: @104 = (@104+@74) */
  for (i=0, rr=w104, cs=w74; i<12; ++i) (*rr++) += (*cs++);
  /* #481: @95 = (2.*@95) */
  for (i=0, rr=w95, cs=w95; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #482: @104 = (@104+@95) */
  for (i=0, rr=w104, cs=w95; i<12; ++i) (*rr++) += (*cs++);
  /* #483: @104 = (@104+@65) */
  for (i=0, rr=w104, cs=w65; i<12; ++i) (*rr++) += (*cs++);
  /* #484: @104 = (@11*@104) */
  for (i=0, rr=w104, cs=w104; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #485: @17 = (@17+@104) */
  for (i=0, rr=w17, cs=w104; i<12; ++i) (*rr++) += (*cs++);
  /* #486: @117 = @17[0, 1, 2, 3, 4, 5, 8, 11] */
  for (cii=casadi_s21, rr=w117, ss=w17; cii!=casadi_s21+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #487: (@19[2, 17, 32, 47, 62, 77, 96, 103] = @117) */
  for (cii=casadi_s22, rr=w19, ss=w117; cii!=casadi_s22+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #488: @99 = (2.*@99) */
  for (i=0, rr=w99, cs=w99; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #489: @91 = (@91+@99) */
  for (i=0, rr=w91, cs=w99; i<12; ++i) (*rr++) += (*cs++);
  /* #490: @82 = (2.*@82) */
  for (i=0, rr=w82, cs=w82; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #491: @91 = (@91+@82) */
  for (i=0, rr=w91, cs=w82; i<12; ++i) (*rr++) += (*cs++);
  /* #492: @91 = (@91+@7) */
  for (i=0, rr=w91, cs=w7; i<12; ++i) (*rr++) += (*cs++);
  /* #493: @91 = (@11*@91) */
  for (i=0, rr=w91, cs=w91; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #494: @92 = (@92+@91) */
  for (i=0, rr=w92, cs=w91; i<12; ++i) (*rr++) += (*cs++);
  /* #495: @118 = @92[:6] */
  for (rr=w118, ss=w92+0; ss!=w92+6; ss+=1) *rr++ = *ss;
  /* #496: (@19[3:93:15] = @118) */
  for (rr=w19+3, ss=w118; rr!=w19+93; rr+=15) *rr = *ss++;
  /* #497: @86 = (2.*@86) */
  for (i=0, rr=w86, cs=w86; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #498: @78 = (@78+@86) */
  for (i=0, rr=w78, cs=w86; i<12; ++i) (*rr++) += (*cs++);
  /* #499: @69 = (2.*@69) */
  for (i=0, rr=w69, cs=w69; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #500: @78 = (@78+@69) */
  for (i=0, rr=w78, cs=w69; i<12; ++i) (*rr++) += (*cs++);
  /* #501: @78 = (@78+@105) */
  for (i=0, rr=w78, cs=w105; i<12; ++i) (*rr++) += (*cs++);
  /* #502: @78 = (@11*@78) */
  for (i=0, rr=w78, cs=w78; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #503: @53 = (@53+@78) */
  for (i=0, rr=w53, cs=w78; i<12; ++i) (*rr++) += (*cs++);
  /* #504: @118 = @53[:6] */
  for (rr=w118, ss=w53+0; ss!=w53+6; ss+=1) *rr++ = *ss;
  /* #505: (@19[4:94:15] = @118) */
  for (rr=w19+4, ss=w118; rr!=w19+94; rr+=15) *rr = *ss++;
  /* #506: @73 = (2.*@73) */
  for (i=0, rr=w73, cs=w73; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #507: @103 = (@103+@73) */
  for (i=0, rr=w103, cs=w73; i<12; ++i) (*rr++) += (*cs++);
  /* #508: @94 = (2.*@94) */
  for (i=0, rr=w94, cs=w94; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #509: @103 = (@103+@94) */
  for (i=0, rr=w103, cs=w94; i<12; ++i) (*rr++) += (*cs++);
  /* #510: @103 = (@103+@106) */
  for (i=0, rr=w103, cs=w106; i<12; ++i) (*rr++) += (*cs++);
  /* #511: @103 = (@11*@103) */
  for (i=0, rr=w103, cs=w103; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #512: @54 = (@54+@103) */
  for (i=0, rr=w54, cs=w103; i<12; ++i) (*rr++) += (*cs++);
  /* #513: @118 = @54[:6] */
  for (rr=w118, ss=w54+0; ss!=w54+6; ss+=1) *rr++ = *ss;
  /* #514: (@19[5:95:15] = @118) */
  for (rr=w19+5, ss=w118; rr!=w19+95; rr+=15) *rr = *ss++;
  /* #515: @98 = (2.*@98) */
  for (i=0, rr=w98, cs=w98; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #516: @90 = (@90+@98) */
  for (i=0, rr=w90, cs=w98; i<12; ++i) (*rr++) += (*cs++);
  /* #517: @81 = (2.*@81) */
  for (i=0, rr=w81, cs=w81; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #518: @90 = (@90+@81) */
  for (i=0, rr=w90, cs=w81; i<12; ++i) (*rr++) += (*cs++);
  /* #519: @90 = (@90+@107) */
  for (i=0, rr=w90, cs=w107; i<12; ++i) (*rr++) += (*cs++);
  /* #520: @90 = (@11*@90) */
  for (i=0, rr=w90, cs=w90; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #521: @55 = (@55+@90) */
  for (i=0, rr=w55, cs=w90; i<12; ++i) (*rr++) += (*cs++);
  /* #522: @118 = @55[:6] */
  for (rr=w118, ss=w55+0; ss!=w55+6; ss+=1) *rr++ = *ss;
  /* #523: (@19[6:96:15] = @118) */
  for (rr=w19+6, ss=w118; rr!=w19+96; rr+=15) *rr = *ss++;
  /* #524: @85 = (2.*@85) */
  for (i=0, rr=w85, cs=w85; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #525: @77 = (@77+@85) */
  for (i=0, rr=w77, cs=w85; i<12; ++i) (*rr++) += (*cs++);
  /* #526: @68 = (2.*@68) */
  for (i=0, rr=w68, cs=w68; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #527: @77 = (@77+@68) */
  for (i=0, rr=w77, cs=w68; i<12; ++i) (*rr++) += (*cs++);
  /* #528: @77 = (@77+@108) */
  for (i=0, rr=w77, cs=w108; i<12; ++i) (*rr++) += (*cs++);
  /* #529: @77 = (@11*@77) */
  for (i=0, rr=w77, cs=w77; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #530: @56 = (@56+@77) */
  for (i=0, rr=w56, cs=w77; i<12; ++i) (*rr++) += (*cs++);
  /* #531: @118 = @56[:6] */
  for (rr=w118, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  /* #532: (@19[7:97:15] = @118) */
  for (rr=w19+7, ss=w118; rr!=w19+97; rr+=15) *rr = *ss++;
  /* #533: @72 = (2.*@72) */
  for (i=0, rr=w72, cs=w72; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #534: @102 = (@102+@72) */
  for (i=0, rr=w102, cs=w72; i<12; ++i) (*rr++) += (*cs++);
  /* #535: @93 = (2.*@93) */
  for (i=0, rr=w93, cs=w93; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #536: @102 = (@102+@93) */
  for (i=0, rr=w102, cs=w93; i<12; ++i) (*rr++) += (*cs++);
  /* #537: @102 = (@102+@109) */
  for (i=0, rr=w102, cs=w109; i<12; ++i) (*rr++) += (*cs++);
  /* #538: @102 = (@11*@102) */
  for (i=0, rr=w102, cs=w102; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #539: @57 = (@57+@102) */
  for (i=0, rr=w57, cs=w102; i<12; ++i) (*rr++) += (*cs++);
  /* #540: @118 = @57[:6] */
  for (rr=w118, ss=w57+0; ss!=w57+6; ss+=1) *rr++ = *ss;
  /* #541: (@19[8:98:15] = @118) */
  for (rr=w19+8, ss=w118; rr!=w19+98; rr+=15) *rr = *ss++;
  /* #542: @97 = (2.*@97) */
  for (i=0, rr=w97, cs=w97; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #543: @89 = (@89+@97) */
  for (i=0, rr=w89, cs=w97; i<12; ++i) (*rr++) += (*cs++);
  /* #544: @80 = (2.*@80) */
  for (i=0, rr=w80, cs=w80; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #545: @89 = (@89+@80) */
  for (i=0, rr=w89, cs=w80; i<12; ++i) (*rr++) += (*cs++);
  /* #546: @89 = (@89+@110) */
  for (i=0, rr=w89, cs=w110; i<12; ++i) (*rr++) += (*cs++);
  /* #547: @89 = (@11*@89) */
  for (i=0, rr=w89, cs=w89; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #548: @58 = (@58+@89) */
  for (i=0, rr=w58, cs=w89; i<12; ++i) (*rr++) += (*cs++);
  /* #549: @119 = @58[:7] */
  for (rr=w119, ss=w58+0; ss!=w58+7; ss+=1) *rr++ = *ss;
  /* #550: (@19[9, 24, 39, 54, 69, 84, 91] = @119) */
  for (cii=casadi_s23, rr=w19, ss=w119; cii!=casadi_s23+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #551: @84 = (2.*@84) */
  for (i=0, rr=w84, cs=w84; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #552: @76 = (@76+@84) */
  for (i=0, rr=w76, cs=w84; i<12; ++i) (*rr++) += (*cs++);
  /* #553: @67 = (2.*@67) */
  for (i=0, rr=w67, cs=w67; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #554: @76 = (@76+@67) */
  for (i=0, rr=w76, cs=w67; i<12; ++i) (*rr++) += (*cs++);
  /* #555: @76 = (@76+@111) */
  for (i=0, rr=w76, cs=w111; i<12; ++i) (*rr++) += (*cs++);
  /* #556: @76 = (@11*@76) */
  for (i=0, rr=w76, cs=w76; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #557: @59 = (@59+@76) */
  for (i=0, rr=w59, cs=w76; i<12; ++i) (*rr++) += (*cs++);
  /* #558: @119 = @59[0, 1, 2, 3, 4, 5, 7] */
  for (cii=casadi_s24, rr=w119, ss=w59; cii!=casadi_s24+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #559: (@19[10, 25, 40, 55, 70, 85, 94] = @119) */
  for (cii=casadi_s25, rr=w19, ss=w119; cii!=casadi_s25+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #560: @71 = (2.*@71) */
  for (i=0, rr=w71, cs=w71; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #561: @101 = (@101+@71) */
  for (i=0, rr=w101, cs=w71; i<12; ++i) (*rr++) += (*cs++);
  /* #562: @79 = (2.*@79) */
  for (i=0, rr=w79, cs=w79; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #563: @101 = (@101+@79) */
  for (i=0, rr=w101, cs=w79; i<12; ++i) (*rr++) += (*cs++);
  /* #564: @101 = (@101+@112) */
  for (i=0, rr=w101, cs=w112; i<12; ++i) (*rr++) += (*cs++);
  /* #565: @101 = (@11*@101) */
  for (i=0, rr=w101, cs=w101; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #566: @60 = (@60+@101) */
  for (i=0, rr=w60, cs=w101; i<12; ++i) (*rr++) += (*cs++);
  /* #567: @119 = @60[0, 1, 2, 3, 4, 5, 8] */
  for (cii=casadi_s26, rr=w119, ss=w60; cii!=casadi_s26+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #568: (@19[11, 26, 41, 56, 71, 86, 97] = @119) */
  for (cii=casadi_s27, rr=w19, ss=w119; cii!=casadi_s27+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #569: @96 = (2.*@96) */
  for (i=0, rr=w96, cs=w96; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #570: @88 = (@88+@96) */
  for (i=0, rr=w88, cs=w96; i<12; ++i) (*rr++) += (*cs++);
  /* #571: @66 = (2.*@66) */
  for (i=0, rr=w66, cs=w66; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #572: @88 = (@88+@66) */
  for (i=0, rr=w88, cs=w66; i<12; ++i) (*rr++) += (*cs++);
  /* #573: @88 = (@88+@113) */
  for (i=0, rr=w88, cs=w113; i<12; ++i) (*rr++) += (*cs++);
  /* #574: @88 = (@11*@88) */
  for (i=0, rr=w88, cs=w88; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #575: @61 = (@61+@88) */
  for (i=0, rr=w61, cs=w88; i<12; ++i) (*rr++) += (*cs++);
  /* #576: @117 = @61[0, 1, 2, 3, 4, 5, 6, 9] */
  for (cii=casadi_s17, rr=w117, ss=w61; cii!=casadi_s17+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #577: (@19[12, 27, 42, 57, 72, 87, 92, 100] = @117) */
  for (cii=casadi_s28, rr=w19, ss=w117; cii!=casadi_s28+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #578: @83 = (2.*@83) */
  for (i=0, rr=w83, cs=w83; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #579: @75 = (@75+@83) */
  for (i=0, rr=w75, cs=w83; i<12; ++i) (*rr++) += (*cs++);
  /* #580: @6 = (2.*@6) */
  for (i=0, rr=w6, cs=w6; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #581: @75 = (@75+@6) */
  for (i=0, rr=w75, cs=w6; i<12; ++i) (*rr++) += (*cs++);
  /* #582: @75 = (@75+@114) */
  for (i=0, rr=w75, cs=w114; i<12; ++i) (*rr++) += (*cs++);
  /* #583: @75 = (@11*@75) */
  for (i=0, rr=w75, cs=w75; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #584: @62 = (@62+@75) */
  for (i=0, rr=w62, cs=w75; i<12; ++i) (*rr++) += (*cs++);
  /* #585: @117 = @62[0, 1, 2, 3, 4, 5, 7, 10] */
  for (cii=casadi_s19, rr=w117, ss=w62; cii!=casadi_s19+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #586: (@19[13, 28, 43, 58, 73, 88, 95, 102] = @117) */
  for (cii=casadi_s29, rr=w19, ss=w117; cii!=casadi_s29+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #587: @70 = (2.*@70) */
  for (i=0, rr=w70, cs=w70; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #588: @100 = (@100+@70) */
  for (i=0, rr=w100, cs=w70; i<12; ++i) (*rr++) += (*cs++);
  /* #589: @5 = (2.*@5) */
  for (i=0, rr=w5, cs=w5; i<12; ++i) *rr++ = (2.* *cs++ );
  /* #590: @100 = (@100+@5) */
  for (i=0, rr=w100, cs=w5; i<12; ++i) (*rr++) += (*cs++);
  /* #591: @100 = (@100+@115) */
  for (i=0, rr=w100, cs=w115; i<12; ++i) (*rr++) += (*cs++);
  /* #592: @100 = (@11*@100) */
  for (i=0, rr=w100, cs=w100; i<12; ++i) (*rr++)  = (w11*(*cs++));
  /* #593: @63 = (@63+@100) */
  for (i=0, rr=w63, cs=w100; i<12; ++i) (*rr++) += (*cs++);
  /* #594: @117 = @63[0, 1, 2, 3, 4, 5, 8, 11] */
  for (cii=casadi_s21, rr=w117, ss=w63; cii!=casadi_s21+8; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #595: (@19[14, 29, 44, 59, 74, 89, 98, 104] = @117) */
  for (cii=casadi_s30, rr=w19, ss=w117; cii!=casadi_s30+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #596: output[1][0] = @19 */
  casadi_copy(w19, 105, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int casadi_erk4_chain_nm3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void casadi_erk4_chain_nm3_incref(void) {
}

CASADI_SYMBOL_EXPORT void casadi_erk4_chain_nm3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int casadi_erk4_chain_nm3_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int casadi_erk4_chain_nm3_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* casadi_erk4_chain_nm3_name_in(casadi_int i){
  switch (i) {
    case 0: return "x0";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* casadi_erk4_chain_nm3_name_out(casadi_int i){
  switch (i) {
    case 0: return "xf";
    case 1: return "sensxu";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* casadi_erk4_chain_nm3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s31;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* casadi_erk4_chain_nm3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s32;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int casadi_erk4_chain_nm3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1478;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
