/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int engine_ls_cost(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void engine_ls_cost_incref(void);
void engine_ls_cost_decref(void);
casadi_int engine_ls_cost_n_out(void);
casadi_int engine_ls_cost_n_in(void);
const char* engine_ls_cost_name_in(casadi_int i);
const char* engine_ls_cost_name_out(casadi_int i);
const casadi_int* engine_ls_cost_sparsity_in(casadi_int i);
const casadi_int* engine_ls_cost_sparsity_out(casadi_int i);
int engine_ls_cost_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
