# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License. #
#
# This service rings the buzzer controlled by the EPS #

uint16 frequency              # Frequency of buzz in kHz
uint16 MIN_FREQUENCY = 1000   # Minimum frequency
uint16 MAX_FREQUENCY = 2000   # Maximum frequency

uint16 duration               # Duration of buzz in seconds
uint16 MIN_DURATION  = 1      # Minimum duration
uint16 MAX_DURATION  = 10     # Maximum duration

---

bool success                  # Was the command accepted
string status_message         # Error message, if needed
