/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* pendulum_ode_expl_vde_adj:(i0[4],i1[4],i2)->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][2] : 0;
  a1=cos(a0);
  a2=1.0791000000000002e+01;
  a3=arg[1] ? arg[1][3] : 0;
  a4=8.0000000000000004e-01;
  a5=1.1000000000000001e+00;
  a6=1.0000000000000001e-01;
  a7=cos(a0);
  a7=(a6*a7);
  a8=cos(a0);
  a9=(a7*a8);
  a5=(a5-a9);
  a9=(a4*a5);
  a10=(a3/a9);
  a11=(a2*a10);
  a1=(a1*a11);
  a11=sin(a0);
  a12=arg[2] ? arg[2][0] : 0;
  a13=(a12*a10);
  a11=(a11*a13);
  a1=(a1-a11);
  a11=cos(a0);
  a13=-8.0000000000000016e-02;
  a14=cos(a0);
  a14=(a13*a14);
  a15=arg[0] ? arg[0][3] : 0;
  a16=(a15*a10);
  a17=(a15*a16);
  a18=(a14*a17);
  a11=(a11*a18);
  a1=(a1+a11);
  a11=sin(a0);
  a18=sin(a0);
  a17=(a18*a17);
  a17=(a13*a17);
  a11=(a11*a17);
  a1=(a1-a11);
  a11=sin(a0);
  a14=(a14*a18);
  a18=(a14*a15);
  a17=(a18*a15);
  a19=cos(a0);
  a20=(a12*a19);
  a17=(a17+a20);
  a20=sin(a0);
  a2=(a2*a20);
  a17=(a17+a2);
  a17=(a17/a9);
  a17=(a17/a9);
  a17=(a17*a3);
  a4=(a4*a17);
  a17=sin(a0);
  a17=(a13*a17);
  a3=(a17*a15);
  a9=(a3*a15);
  a2=9.8100000000000009e-01;
  a20=cos(a0);
  a20=(a2*a20);
  a21=sin(a0);
  a22=(a20*a21);
  a9=(a9+a22);
  a9=(a9+a12);
  a9=(a9/a5);
  a9=(a9/a5);
  a12=arg[1] ? arg[1][1] : 0;
  a9=(a9*a12);
  a4=(a4+a9);
  a7=(a7*a4);
  a11=(a11*a7);
  a1=(a1-a11);
  a11=sin(a0);
  a8=(a8*a4);
  a6=(a6*a8);
  a11=(a11*a6);
  a1=(a1-a11);
  a11=cos(a0);
  a12=(a12/a5);
  a20=(a20*a12);
  a11=(a11*a20);
  a1=(a1+a11);
  a11=sin(a0);
  a21=(a21*a12);
  a2=(a2*a21);
  a11=(a11*a2);
  a1=(a1-a11);
  a0=cos(a0);
  a11=(a15*a12);
  a15=(a15*a11);
  a13=(a13*a15);
  a0=(a0*a13);
  a1=(a1+a0);
  if (res[0]!=0) res[0][2]=a1;
  a18=(a18*a10);
  a14=(a14*a16);
  a18=(a18+a14);
  a14=arg[1] ? arg[1][2] : 0;
  a18=(a18+a14);
  a3=(a3*a12);
  a18=(a18+a3);
  a17=(a17*a11);
  a18=(a18+a17);
  if (res[0]!=0) res[0][3]=a18;
  a19=(a19*a10);
  a19=(a19+a12);
  if (res[0]!=0) res[0][4]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void pendulum_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_expl_vde_adj_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
