/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_ode_impl_ode_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {4, 4, 0, 0, 1, 3, 6, 0, 1, 3, 1, 2, 3};
static const casadi_int casadi_s4[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[6] = {4, 1, 0, 2, 1, 3};
static const casadi_int casadi_s6[3] = {4, 0, 0};

/* pendulum_ode_impl_ode_jac_x_xdot_u_z:(i0[4],i1[4],i2,i3[])->(o0[4x4,6nz],o1[4x4,4nz],o2[4x1,2nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=-1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0] ? arg[0][3] : 0;
  a2=-8.0000000000000016e-02;
  a3=arg[0] ? arg[0][2] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a4=(a1*a4);
  a4=(a1*a4);
  a5=9.8100000000000009e-01;
  a6=cos(a3);
  a6=(a5*a6);
  a7=cos(a3);
  a7=(a6*a7);
  a8=sin(a3);
  a9=sin(a3);
  a5=(a5*a9);
  a5=(a8*a5);
  a7=(a7-a5);
  a4=(a4+a7);
  a7=1.1000000000000001e+00;
  a5=1.0000000000000001e-01;
  a9=cos(a3);
  a9=(a5*a9);
  a10=cos(a3);
  a11=(a9*a10);
  a7=(a7-a11);
  a4=(a4/a7);
  a11=sin(a3);
  a11=(a2*a11);
  a12=(a11*a1);
  a13=(a12*a1);
  a6=(a6*a8);
  a13=(a13+a6);
  a6=arg[2] ? arg[2][0] : 0;
  a13=(a13+a6);
  a13=(a13/a7);
  a13=(a13/a7);
  a8=sin(a3);
  a5=(a5*a8);
  a10=(a10*a5);
  a5=sin(a3);
  a9=(a9*a5);
  a10=(a10+a9);
  a13=(a13*a10);
  a4=(a4-a13);
  a4=(-a4);
  if (res[0]!=0) res[0][1]=a4;
  a4=cos(a3);
  a4=(a2*a4);
  a13=cos(a3);
  a13=(a4*a13);
  a9=sin(a3);
  a5=sin(a3);
  a2=(a2*a5);
  a2=(a9*a2);
  a13=(a13-a2);
  a13=(a1*a13);
  a13=(a1*a13);
  a2=sin(a3);
  a2=(a6*a2);
  a13=(a13-a2);
  a2=1.0791000000000002e+01;
  a5=cos(a3);
  a5=(a2*a5);
  a13=(a13+a5);
  a5=8.0000000000000004e-01;
  a8=(a5*a7);
  a13=(a13/a8);
  a4=(a4*a9);
  a9=(a4*a1);
  a14=(a9*a1);
  a15=cos(a3);
  a6=(a6*a15);
  a14=(a14+a6);
  a3=sin(a3);
  a2=(a2*a3);
  a14=(a14+a2);
  a14=(a14/a8);
  a14=(a14/a8);
  a5=(a5*a10);
  a14=(a14*a5);
  a13=(a13-a14);
  a13=(-a13);
  if (res[0]!=0) res[0][2]=a13;
  a11=(a1*a11);
  a11=(a11+a12);
  a11=(a11/a7);
  a11=(-a11);
  if (res[0]!=0) res[0][3]=a11;
  if (res[0]!=0) res[0][4]=a0;
  a1=(a1*a4);
  a1=(a1+a9);
  a1=(a1/a8);
  a1=(-a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=1.;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a1;
  if (res[1]!=0) res[1][3]=a1;
  a7=(1./a7);
  a7=(-a7);
  if (res[2]!=0) res[2][0]=a7;
  a15=(a15/a8);
  a15=(-a15);
  if (res[2]!=0) res[2][1]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_ode_impl_ode_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void pendulum_ode_impl_ode_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_ode_impl_ode_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_impl_ode_jac_x_xdot_u_z_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_ode_impl_ode_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_impl_ode_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_ode_impl_ode_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_impl_ode_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_ode_impl_ode_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_ode_impl_ode_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
