[package]
name = "t_renderer"
version = "0.1.0"
authors = ["andrea.zanelli <andrea.zanelli@imtek.uni-freiburg.de>"]
edition = "2018"

[dependencies]
tera = "0.11"
serde_json = "1.0"

[profile.release]
opt-level = 'z'
