// Autogenerated file, see write_tunable_param_functions for details

#include "ctl_tunable_funcs.h"
#include <config_reader/config_reader.h>
#include <ros/console.h>
#include <msg_conversions/msg_conversions.h>

// Do config setup and add includes
void ctl_ReadParams(config_reader::ConfigReader* config,  RT_MODEL_ctl_controller0_T* ctl) {

  auto & p = ctl->defaultParam;

  if (!msg_conversions::config_read_array(config, "tun_accel_gain", 3 , p->tun_accel_gain))
    ROS_FATAL("Unspecified tun_accel_gain.");
  if (!msg_conversions::config_read_array(config, "tun_alpha_gain", 3 , p->tun_alpha_gain))
    ROS_FATAL("Unspecified tun_alpha_gain.");
  if (!config->GetReal("tun_ctl_att_sat_lower", &p->tun_ctl_att_sat_lower))
    ROS_FATAL("Unspecified tun_ctl_att_sat_lower.");
  if (!config->GetReal("tun_ctl_att_sat_upper", &p->tun_ctl_att_sat_upper))
    ROS_FATAL("Unspecified tun_ctl_att_sat_upper.");
  if (!config->GetReal("tun_ctl_linear_force_limit", &p->tun_ctl_linear_force_limit))
    ROS_FATAL("Unspecified tun_ctl_linear_force_limit.");
  if (!config->GetReal("tun_ctl_pos_sat_lower", &p->tun_ctl_pos_sat_lower))
    ROS_FATAL("Unspecified tun_ctl_pos_sat_lower.");
  if (!config->GetReal("tun_ctl_pos_sat_upper", &p->tun_ctl_pos_sat_upper))
    ROS_FATAL("Unspecified tun_ctl_pos_sat_upper.");
  if (!config->GetReal("tun_ctl_stopped_pos_thresh", &p->tun_ctl_stopped_pos_thresh))
    ROS_FATAL("Unspecified tun_ctl_stopped_pos_thresh.");
  if (!config->GetReal("tun_ctl_stopped_quat_thresh", &p->tun_ctl_stopped_quat_thresh))
    ROS_FATAL("Unspecified tun_ctl_stopped_quat_thresh.");
  if (!config->GetReal("tun_ctl_stopping_omega_thresh", &p->tun_ctl_stopping_omega_thresh))
    ROS_FATAL("Unspecified tun_ctl_stopping_omega_thresh.");
  if (!config->GetReal("tun_ctl_stopping_vel_thresh", &p->tun_ctl_stopping_vel_thresh))
    ROS_FATAL("Unspecified tun_ctl_stopping_vel_thresh.");
  if (!config->GetReal("tun_truth_q_omega_filt_enable", &p->tun_truth_q_omega_filt_enable))
    ROS_FATAL("Unspecified tun_truth_q_omega_filt_enable.");
  if (!config->GetReal("tun_truth_velocity_filt_enable", &p->tun_truth_velocity_filt_enable))
    ROS_FATAL("Unspecified tun_truth_velocity_filt_enable.");
  bool debug_ctl_use_truth;
  if (!config->GetBool("tun_debug_ctl_use_truth", &debug_ctl_use_truth))
  ROS_FATAL("Unspecified tun_debug_ctl_use_truth.");
  p->tun_debug_ctl_use_truth = debug_ctl_use_truth;
}
