% Copyright (c) 2017, United States Government, as represented by the
% Administrator of the National Aeronautics and Space Administration.
%
% All rights reserved.
%
% The Astrobee platform is licensed under the Apache License, Version 2.0
% (the "License"); you may not use this file except in compliance with the
% License. You may obtain a copy of the License at
%
%     http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
% WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
% License for the specific language governing permissions and limitations
% under the License.

function cellInfo = bus_defs(varargin) 
% BUS_DEFS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'act_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'act_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_impeller_speed_cmd', 2, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_servo_pwm_cmd', 12, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_nozzle_theta', 12, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_predicted_force_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'act_predicted_torque_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'bpm_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'bpm_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_motor_curr', 2, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_servo_curr', 12, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_torque_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_force_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_motor_speed', 2, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bpm_nozzle_theta', 12, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cmc_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cmc_state_cmd_a', 1, 'Bus: cmc_state_cmd', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmc_state_cmd_b', 1, 'Bus: cmc_state_cmd', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmc_mode_cmd', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('0 - Idle\n1 - Stopping\n2 - Nominal')}; ...
{'speed_gain_cmd', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'localization_mode_cmd', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('0 - Nominal\n1 - Docking\n2 - Perching')}; ...
{'att_kp', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'att_ki', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'omega_kd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pos_kp', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pos_ki', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vel_kd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'center_of_mass', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'inertia_matrix', [3 3], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'mass', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cmc_state_cmd', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'P_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'V_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'A_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'quat_ISS2B', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'omega_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'alpha_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cmd_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cmd_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmd_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmd_mode', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'speed_gain_cmd', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmd_B_inuse', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_pos', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_vel', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_accel', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_quat', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_omega', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_alpha', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'ctl_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'body_force_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'body_accel_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pos_err', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pos_err_int', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'body_torque_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'body_alpha_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'att_err', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'att_err_mag', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'att_err_int', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ctl_status', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_error_pos', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_error_att', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_error_vel', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'traj_error_omega', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cvs_handrail_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cvs_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_landmarks', [50 3], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_observations', [50 3], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_valid_flag', 50, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_3d_knowledge_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Flag that allows the estimator to infer knowledge along the handrail.')}; ...
{'cvs_handrail_local_pos', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_handrail_local_quat', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_handrail_update_global_pose_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cvs_landmark_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cvs_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_landmarks', [50 3], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_observations', [50 2], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_valid_flag', 50, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cvs_optical_flow_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cvs_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_observations', [50 2 16], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_valid_flag', [50 16], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_id_tag', 50, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'cvs_registration_pulse', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'cvs_ar_tag_pulse', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_landmark_pulse', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_optical_flow_pulse', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cvs_handrail_pulse', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'env_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'P_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('meters'), ''}; ...
{'V_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'A_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s/s'), ''}; ...
{'A_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s/s'), ''}; ...
{'A_B_ECI_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Q_ISS2B', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'omega_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad/sec'), ''}; ...
{'omega_B_ECI_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'alpha_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s/s'), ''}; ...
{'fan_torques_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Nm'), sprintf('Fan torques in the body frame')}; ...
{'fan_forces_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), sprintf('Fan forces in the body frame')}; ...
    } ...
  } ...
  { ... 
    'ex_time_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'imu_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'imu_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'imu_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'imu_A_B_ECI_sensor', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s^2'), sprintf('IMU accelerometer measurement')}; ...
{'imu_accel_bias', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'imu_omega_B_ECI_sensor', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), sprintf('IMU angular rate')}; ...
{'imu_gyro_bias', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'imu_validity_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('none'), sprintf('flag or status field. Not sure yet.')}; ...
{'imu_sat_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'kfl_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'quat_ISS2B', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'omega_B_ISS_B', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'gyro_bias', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'V_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'A_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'accel_bias', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'P_B_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'confidence', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aug_state_enum', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ml_quat_ISS2cam', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ml_P_cam_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'of_quat_ISS2cam', [16 4], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Dimensions should equal [ase_of_num_aug 4]')}; ...
{'of_P_cam_ISS_ISS', [16 3], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Dimensions should equal [ase_of_num_aug 4]')}; ...
{'cov_diag', 117, 'ase_cov_datatype', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'kfl_status', 1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Bit masked status byte')}; ...
{'update_OF_tracks_cnt', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'update_ML_features_cnt', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'of_mahal_distance', 50, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ml_mahal_distance', 50, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'hr_P_hr_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'hr_quat_ISS2hr', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'P_EST_ISS_ISS', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Position of the estimator frame relative to the ISS frame in the ISS frame')}; ...
    } ...
  } ...
  { ... 
    'vis_msg', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'vis_timestamp_sec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_timestamp_nsec', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_pos', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_quat', 4, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_lin_vel', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_ang_vel', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'vis_validity_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
