
on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

name: Release MATLAB 

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    name: Build release
    needs: create_release 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        include:
          - os: ubuntu-latest
            platform: linux 
          - os: macos-latest
            platform: mac
          - os: windows-2019
            platform: windows 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Build and package MATLAB interface
        uses: matlab-actions/run-command@v1
        with:
          command: cd interfaces/daqp-matlab, make_daqp, make_daqp('package')

      - name: Upload tarballs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./interfaces/daqp-matlab/daqp-matlab-${{ matrix.platform}}64.tar.gz
          asset_name: daqp-matlab-${{ matrix.platform}}64.tar.gz
          asset_content_type: application/gzip
