/* Copyright (c) 2017, United States Government, as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * 
 * All rights reserved.
 * 
 * The Astrobee platform is licensed under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

// Autogenerated from FMECA! DO NOT CHANGE!

#ifndef FF_UTIL_FF_FAULTS_H_
#define FF_UTIL_FF_FAULTS_H_

#include <string>

namespace ff_util {

enum FaultKeys {
  VELOCITY_TOO_HIGH,
  HEARTBEAT_MISSING,
  INITIALIZATION_FAILED,
  UNKNOWN_FAULT_KEY,
  LOAD_TOO_HIGH,
  DISK_CONFIG_INVALID,
  DISK_USAGE_HIGH,
  DISK_USAGE_TOO_HIGH,
  MEMORY_USAGE_TOO_HIGH,
  TEMPERATURE_TOO_HIGH,
  TIME_DIFF_TOO_HIGH,
  IMU_ACCEL_ABOVE_LIMITS,
  LOCALIZATION_PIPELINE_UNSTABLE,
  ESTIMATE_CONFIDENCE_TOO_LOW,
  NO_COMMUNICATION_HAZCAM,
  NO_COMMUNICATION_SPEEDCAM,
  KINETIC_ENERGY_INCREASING,
  POSE_ESTIMATE_NON_PHYSICAL,
  BAD_GYRO_DATA,
  IMU_OVERTEMP,
  SELF_TEST_FAULT_CODE,
  HARDWARE_ERROR_FAULT_CODE,
  BAD_ACCEL_DATA,
  NO_IMU_DATA_PACKETS
};

constexpr int kFaultKeysSize = 24;

static std::string fault_keys[] = {
    "VELOCITY_TOO_HIGH",
    "HEARTBEAT_MISSING",
    "INITIALIZATION_FAILED",
    "UNKNOWN_FAULT_KEY",
    "LOAD_TOO_HIGH",
    "DISK_CONFIG_INVALID",
    "DISK_USAGE_HIGH",
    "DISK_USAGE_TOO_HIGH",
    "MEMORY_USAGE_TOO_HIGH",
    "TEMPERATURE_TOO_HIGH",
    "TIME_DIFF_TOO_HIGH",
    "IMU_ACCEL_ABOVE_LIMITS",
    "LOCALIZATION_PIPELINE_UNSTABLE",
    "ESTIMATE_CONFIDENCE_TOO_LOW",
    "NO_COMMUNICATION_HAZCAM",
    "NO_COMMUNICATION_SPEEDCAM",
    "KINETIC_ENERGY_INCREASING",
    "POSE_ESTIMATE_NON_PHYSICAL",
    "BAD_GYRO_DATA",
    "IMU_OVERTEMP",
    "SELF_TEST_FAULT_CODE",
    "HARDWARE_ERROR_FAULT_CODE",
    "BAD_ACCEL_DATA",
    "NO_IMU_DATA_PACKETS"
};

}  // namespace ff_util

#endif  // FF_UTIL_FF_FAULTS_H_
