# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This message describes the ARM action offered by the PERCHING ARM

uint8 mode                                    # What to do
uint8 DEPLOY              = 1                 # Deploy the arm
uint8 STOW                = 2                 # Retract the arm
uint8 OPEN                = 3                 # Open the gripper
uint8 CLOSE               = 4                 # Close the gripper
uint8 CALIBRATE           = 5                 # Calibrate the gripper
uint8 PAN_TILT            = 6                 # Pan/tilt the arm
uint8 PAN                 = 7                 # Pan the arm
uint8 TILT                = 8                 # Tilt the arm
float32 pan                                   # Pan value (radians)
float32 tilt                                  # Tilt value (radians)
---
int32 response
int32 SUCCESS             =  1                # Successfully completed
int32 PREEMPTED           =  0                # Action was preempted
int32 CANCELLED           = -1                # Callee cancelled action
int32 BACKDRIVE_DETECTED  = -2                # External force detected
int32 RUNTIME_ERROR       = -3                # Could not complete action
int32 SERIAL_COMM_ERROR   = -4                # I: Communication error
int32 OUT_OF_BOUNDS       = -5                # I: Infeasible command
int32 INVALID_COMMAND     = -6                # I: Invalid command
---
float32 percentage_complete                   # Percentage complete
###################################################################
