# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This message describes the ARM action offered by the PERCHING ARM

uint8 command                                 # What to do
uint8 ARM_STOP            = 0                 # Stop the arm (vel = 0)
uint8 ARM_DEPLOY          = 1                 # Deploy the arm
uint8 ARM_STOW            = 2                 # Retract the arm
uint8 ARM_PAN             = 3                 # Pan the arm
uint8 ARM_TILT            = 4                 # Tilt the arm
uint8 ARM_MOVE            = 5                 # Pan and tilt the
uint8 GRIPPER_CALIBRATE   = 6                 # Calibrate the gripper
uint8 GRIPPER_SET         = 7                 # Set the gripper value
uint8 GRIPPER_OPEN        = 8                 # Open the gripper
uint8 GRIPPER_CLOSE       = 9                 # Open the gripper

float32 pan                                   # PAN from -90 to +90
float32 tilt                                  # TILT from -30 to +90
float32 gripper                               # SET from 20 to 45

---

int32 response
int32 SUCCESS             =  1                # Successfully completed
int32 PREEMPTED           =  0                # Action was preempted
int32 INVALID_COMMAND     = -1                # Invalid command
int32 BAD_TILT_VALUE      = -2                # Invalid value for tilt
int32 BAD_PAN_VALUE       = -3                # Invalid value for pan
int32 BAD_GRIPPER_VALUE   = -4                # Invalid value for gripper
int32 NOT_ALLOWED         = -5                # Not allowed
int32 NEED_TO_CALIBRATE   = -6                # Cannot OPEN/CLOSE/SET gripper
int32 TILT_FAILED         = -7                # Tilt command failed
int32 PAN_FAILED          = -8                # Pan command failed
int32 GRIPPER_FAILED      = -9                # Gripper command failed
int32 CALIBRATE_FAILED    = -10               # Gripper calibrate failed
int32 COMMUNICATION_ERROR = -11               # Cannot communicate with arm
int32 COLLISION_AVOIDED   = -12               # No panning when tilt < 90

---

ff_msgs/ArmState state                        # Complete state

float32 pan                                   # Current PAN value
float32 tilt                                  # Current TILT value
float32 gripper                               # Current GRIPPER value