# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This message describes the PLAN action offered by the PLANNER

geometry_msgs/PoseStamped[] states            # Desired state sequence

bool faceforward                              # Face-forward trajectory?
bool check_obstacles                          # Check against obstacles?

float32 desired_vel                           # Desired (max) velocity
float32 desired_accel                         # Desired (max) accel
float32 desired_omega                         # Desired (max) omega
float32 desired_alpha                         # Desired (max) alpha
float32 desired_rate                          # Desired rate

duration max_time                             # Max generation time

---

int32 response                                # Response
int32 ALREADY_THERE                    =  3
int32 CANCELLED                        =  2
int32 SUCCESS                          =  1
int32 PREEMPTED                        =  0
int32 NOT_ENOUGH_STATES                = -1
int32 OBSTACLES_NOT_SUPPORTED          = -2
int32 BAD_STATE_TRANSITION             = -3
int32 CANNOT_LOAD_FLIGHT_DATA          = -4
int32 CANNOT_LOAD_GENERAL_CONFIG       = -5
int32 NO_PATH_EXISTS                   = -6
int32 PROBLEM_CONNECTING_TO_SERVICES   = -7
int32 BAD_ARGUMENTS                    = -8

ff_msgs/ControlState[] segment                # Output segment

---

float32 perc_complete                                 # Percentage complete
float32 secs_remaining                                # Seconds remaining
