# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This message is the SWITCH action offered by the LOCALIZATION_MANAGER

string pipeline                              # The requested localization pipeline
string NONE               = "no"
string MAPPED_LANDMARKS   = "ml"
string AR_TAGS            = "ar"
string HANDRAIL           = "hr"
string PERCH              = "pl"
string TRUTH              = "gt"

---

int32 response
int32 PIPELINE_ALREADY_ACTIVE         =  2   # We are already on this mode
int32 SUCCESS                         =  1   # The switch was successful
int32 PREEMPTED                       =  0   # We were preempted by another switch request
int32 CANCELLED                       = -1   # We cancelled our own switch request
int32 PIPELINE_NOT_FOUND              = -2   # Mode not valid. Check the string?
int32 COULD_NOT_ENABLE_NEW_PIPELINE   = -3   # Could not enable pipeline
int32 COULD_NOT_SWITCH_EKF            = -4   # Could not switch EKF to the goal input
int32 COULD_NOT_ENABLE_OPTICAL_FLOW   = -5   # Could not enable optical flow
int32 COULD_NOT_DISABLE_OLD_PIPELINE  = -6   # Could not enable pipeline
int32 COULD_NOT_CANCEL                = -7   # Could not enable pipeline
int32 HAD_TO_FALLBACK                 = -8   # Current pipeline was failing to had to fallback
int32 PIPELINE_NOT_STABLE             = -9   # Measurement not received in T
int32 EKF_NOT_STABLE                  = -10  # Measurement not received in T
int32 BAD_STATE_TRANSITION            = -11  # Measurement not received in T

---