# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# 
# All rights reserved.
# 
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Undock action for the Docking node

# Goal
std_msgs/Header header

---
# Result
std_msgs/Header header
int32 status

int32 UNKNOWN          = 0

# success codes
int32 UNDOCKED         = 1
int32 ALREADY_UNDOCKED = 2     # success!

# error codes
int32 ACTION_IN_PROGRESS = -101  # we are already trying to dock
int32 DOCK_HW_ERROR      = -102  # i2c error or something with dock

# localization error codes
int32 NO_FEATURES      = -201  # could not get a location lock

---
# Feedback
std_msgs/Header header
float32 progress  # distance from dock? something?

int32 status      # one of the status codes below, typically increases

int32 UNKNOWN          = 0
int32 SWITCHING_CAMERA = 1
int32 SWITCHING_MODE   = 2
int32 WAITING_FOR_LOC  = 3
int32 RESETTING_BIAS   = 4
int32 ACTIVATING_PMC   = 5
int32 ACTUATING_DOCK   = 6
int32 EGRESSING        = 7
int32 MAX_STATE        = 7
